### ISSUE TITLE
FileNotFoundException: export-common

### ISSUE THREAD

**Issue by rexxarM** [Tencent/sluaunreal#10]
This `lua-wrapper.exe` can not be running on macOS(10.13.6) anymore, but the previous version worked.

Is there changed while building the executable file? 

Or is there missing files associated with `export-common.dll` which didn't upload?

➜  Tools mono lua-wrapper.exe 
Does not support running on the current platform.
System.IO.FileNotFoundException: Could not load file or assembly 'export-common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
File name: 'export-common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
at export_unreal.ExportUnreal.Start () [0x00001] in <8d2974b7de164bf39e78a81a0ce17755>:0 
at export_unreal.Program.Main () [0x0011f] in <8d2974b7de164bf39e78a81a0ce17755>:0

**Comment by pangweiwei** [comment]
fixed
