### ISSUE TITLE
luaobject::push

### ISSUE THREAD

**Issue by xinbay** [Tencent/sluaunreal#101]
你好
   在使用lua导出的时候发现，有一些类型没有重载
   能在版本中添加导出 添加 lua_pushlstring吗，
还有使用defluaclass 导出的时候，发现也没有办法导出TSharedPtr
可以提供支持吗

**Comment by pangweiwei** [comment]
TSharedPtr 已经支持了，你pull

**Comment by xinbay** [comment]
tks 已经支持
