### ISSUE TITLE
DefLuaClass 问题

### ISSUE THREAD

**Issue by xinbay** [Tencent/sluaunreal#102]
你好，
     在使用DefLuaClass的过程中，有一些函数参数使用DefLuaMethod无法推到，于是想使用
DefLuaMethod_With_Lambda进行一步的封装，但是发现，Lambda无法传递参数，luafunc中始终取的是usedata类型。
 是否可以提供lambda的参数支持

**Comment by pangweiwei** [comment]
DefLuaMethod_With_Lambda 可以支持参数，和luafunc没有关系呀

**Comment by xinbay** [comment]
@pangweiwei 
是不是我的调用方法有问题
DefLuaMethod_With_Lambda(FuncName, false, [](const char* a)->TSharedPtr<FHandle> {
			
			Log::Log(a)
		})

在lua中调用  a: FuncName("abcde")

lua 中报错 on bad self (string expected, got FManager)
查看代码中发现
static int LuaCFunction(lua_State* L) {
            // check and get obj ptr;
            void* p = LuaObject::checkUD<T>(L,1);
            using f = FunctionBind<decltype(&invoke), invoke, 2>;
            return f::invoke(L,p);
        }

**Comment by pangweiwei** [comment]
lambda 函数你要第一个放入参数FManager*，不会自动给你传入的

**Comment by xinbay** [comment]
感谢帮助
