### ISSUE TITLE
LuaDelegate问题

### ISSUE THREAD

**Issue by xinbay** [Tencent/sluaunreal#103]
定义DECLARE_DELEGATE(FTestDelegate);
静态类方法
static void Load(FTestDelegate a);
	static void Callback();
通过DefLuaMethod(Load, &TraceLog::Load)
		DefLuaMethod(Callback, &TraceLog::Callback)
绑定
执行的时候发现 IsBound为false。

lua代码
local cb = slua.createDelegate(function()
        print("****************************************") 
    end)

TraceLog.Load(cb)
    TraceLog.Callback()

@pangweiwei 是DECLARE_DELEGATE还不支持吗

**Comment by pangweiwei** [comment]
直接使用TFunction 参考testcase

**Comment by xinbay** [comment]
问题解决了， 忘记关闭。多谢。
