### ISSUE TITLE
getFromTable模板参数R为bool时有歧义

### ISSUE THREAD

**Issue by tary** [Tencent/sluaunreal#104]
https://github.com/Tencent/sluaunreal/blob/9b30d30e13930823e0ff4f3ab739f051eeeb5307/Plugins/slua_unreal/Source/slua_unreal/Public/LuaVar.h#L160
https://github.com/Tencent/sluaunreal/blob/9b30d30e13930823e0ff4f3ab739f051eeeb5307/Plugins/slua_unreal/Source/slua_unreal/Public/LuaVar.h#L173

**Comment by tary** [comment]
可以考虑
`void getFromTable(T key, R& target) const`
改为
`void getFromTable(T key, R& target, bool rawget=false) const`

**Comment by pangweiwei** [comment]
getFromTable<bool>(...)

**Comment by tary** [comment]
用 `bool result =  getFromTable(T key) `不会有问题. 但是 `void getFromTable(T key, R& target) const`这个函数在R是`bool`时(加上`< bool >`)也会用带返回值的那个定义,导致target不会被赋值.
