### ISSUE TITLE
请问能简要的解释一下多线程GC的实现思路吗，看代码有点不理解。。。

### ISSUE THREAD

**Issue by ShrimpABC** [Tencent/sluaunreal#105]

**Comment by ShrimpABC** [comment]
看代码，通过enableMultiThreadGC来判断是否开启多线程GC。多线程GC开启时，在子线程中的AddReferencedObjects的函数里进行异步GC。但LuaBase::tick是在主线程调用的，它会进行LUA_GCSTEP，无论是否开启多线程GC，这样做会有冲突吗？

**Comment by pangweiwei** [comment]
AddReferencedObjects 虽然发生在另外一个线程，但其实在主线程tick会wait其他线程gc结束（有很多线程同时做很多工作，包括gc），这是不会产生线程竞争。

**Comment by ShrimpABC** [comment]
好的，明白了，多谢大佬！
