### ISSUE TITLE
请教require module 的问题

### ISSUE THREAD

**Issue by wangyhbupt** [Tencent/sluaunreal#106]
当require某个文件夹中的某个文件的时候，我习惯于修改package.path，使其包含那个文件夹
但是，在使用slua的时候，我发现，只有在Content/Lua下的文件可以加载到，其他的文件夹下的文件都加载不到，请问这是什么原因？
如下图，要加载的pathtest.lua就放在Content/Lua/1目录下
![image](https://user-images.githubusercontent.com/35680535/56862367-a694c500-69dc-11e9-8579-3fc1a0265079.png)

**Comment by pangweiwei** [comment]
这取决于你的loader，在游戏环境下，你的文件很可能不来源于物理物件，而是pak，或者zip，或者其他打包的文件，所以你需要修改loader，让loader识别的你require 后面的path来加载文件。

**Comment by wangyhbupt** [comment]
多谢解答
目前我的解决方法是，在loader里面把LuaState的packaget.path解析出来，自己拼路径去加载。
