### ISSUE TITLE
iOS偶现崩溃，多数是checkUD这里崩溃，感觉是gc的问题导致，请问gc有什么需要注意的吗？编辑器下几乎没有出现过，android也很几乎没见过

### ISSUE THREAD

**Issue by zengdelang** [Tencent/sluaunreal#108]
![webwxgetmsgimg](https://user-images.githubusercontent.com/4466062/56941163-440b0880-6b45-11e9-915a-dd004628c04d.jpg)

**Comment by pangweiwei** [comment]
贴图看不清，另外是什么版本？

**Comment by zengdelang** [comment]
晚些时候我再把图截小点，目前初步判断是上层框架的问题，应该是多个table引用了相同的__cppinst的，可能某个对象销毁了，其他的table还是访问了这个__cppinst导致的，不过这个是FVector2D的有点想不通

**Comment by zengdelang** [comment]
![webwxgetmsgimg](https://user-images.githubusercontent.com/4466062/56955433-f8bc1e80-6b73-11e9-94e3-057fc814020b.jpg)

**Comment by zengdelang** [comment]
目前初步定位到问题是，框架层注册了__gc函数，在iOS中大概不到5分钟就自动崩溃，注释掉__gc函数就不会崩溃，安卓没有这个问题
![image](https://user-images.githubusercontent.com/4466062/56955503-35881580-6b74-11e9-8bde-164e46b90511.png)

**Comment by zengdelang** [comment]
引擎是4.21，slua版本应该是前几天的最新版本

**Comment by pangweiwei** [comment]
在__GC函数中不能再发生error，否则可能异常，看你的调用栈，就是在gc函数里发生了checkudata的异常。

**Comment by pangweiwei** [comment]
你要保证在_InternalDestroy里不发生任何error

**Comment by zengdelang** [comment]
目前已经废除了在__gc函数中做清理的做法了，改成手动清理，崩溃应该没有了
