### ISSUE TITLE
Actor对象被删除，Lua访问错误的问题，android下还发现一次崩溃

### ISSUE THREAD

**Issue by zengdelang** [Tencent/sluaunreal#109]
在Lua中引用一个Actor对象，当Actor被销毁并回收后，在Lua端访问会报错
arg 1 had been freed(0000020BA2488100), can't be used
在lua中使用判空操作无效，userdata在lua中不为空，这个报错在android中出现一次崩溃，显示Fatal Error，请问这个问题怎么解决

**Comment by zengdelang** [comment]
Fatal Error的提示是在lua自定义的__index中调用了cppinst的变量，cppinst被释放导致checkUD提示arg1 had been freed，是因为不能在元方法中出现错误吗？

**Comment by zengdelang** [comment]
经过验证，发现确实不能在元方法中产生错误，编辑器下也会闪退，如
  mt.__index = function(t, k)
        local v = vtbl[k]
        if v then
            return v
        end

        local f = 1 +"1"

        if t.__cppinst then
            local v = t.__cppinst[k]
            if type(v) == "function" then
                rawset(t, k, v)
            end
            return v
        end
    end

另外在lua中判断一个UObject对象是否有效，可以添加帮助函数
	int LuaHelperLibrary::IsValid(lua_State* L)
	{
		if(lua_isuserdata(L, 1))
		{
			const auto Obj = LuaObject::checkUD<UObject>(L, 1, false);
			return LuaObject::push(L, ::IsValid(Obj));
		}
		if (lua_istable(L, 1)) 
		{
			lua_getfield(L, 1, SLUA_CPPINST);
			if (lua_type(L, -1) == LUA_TUSERDATA)
			{
				const auto Obj = LuaObject::checkUD<UObject>(L, lua_absindex(L, -1), false);
				return LuaObject::push(L, ::IsValid(Obj));
			}
		}
		return LuaObject::push(L, false);
	}

**Comment by pangweiwei** [comment]
Actor会在world切换的时候，被free掉，你的逻辑要保证actor在world被切换修不能再访问actor
slua会报告这个错误，是保护性的，知道这个ud已经被free了，只报告脚本错误，不至于崩溃。

不过可以考虑增加一个isValid的脚本方法，判断一个uobject时候还有效。

**Comment by zengdelang** [comment]
Actor不一定是在world切换的时候free，自己动态生成的actor在需要的时候调用DestroyActor，UE4的GC大概1分钟会执行一次然后真正释放Actor，如果一个模块动态生成的Actor，另一个模块引用在这种情况下仅仅依靠判断为空是不够的，崩溃问题经过我测试应该是在__index的元方法中报错导致的，编辑器下也会崩溃

**Comment by pangweiwei** [comment]
嗯，主动DestroyActor也会

**Comment by pangweiwei** [comment]
fixed, I add a function isValid to test ud is valid, if ud had been free or destroyed, isValid return false.
