### ISSUE TITLE
请问经过反射系统导出给lua的类有方便进行down cast（父类到子类）的方式吗？

### ISSUE THREAD

**Issue by ShrimpABC** [Tencent/sluaunreal#110]

**Comment by ShrimpABC** [comment]
也就是说在lua脚本中，怎样方便地将一个父类cast成子类呢？是否要通过cppbinding来导出cast函数呢？

**Comment by pangweiwei** [comment]
在反射系统中，不存在需要downcast的使用可能呀，一个UObject*被push后，在lua内可以调用他的子类的方法的

**Comment by ShrimpABC** [comment]
好的，了解了。之前还在以做蓝图的思维方式考虑问题。。。谢谢！
