### ISSUE TITLE
请问slua默认的枚举导出规则？

### ISSUE THREAD

**Issue by JamesHuang0331** [Tencent/sluaunreal#111]
发现在UE中反射的UENUM，slua并不是都导出到了UEnums全局表中。而且有一些非反射的枚举，slua也导出了。
例如我们项目使用到的这个枚举就没有导出：
![image](https://user-images.githubusercontent.com/7420251/57291750-9e323d80-70f2-11e9-9fce-7dc95787c3f0.png)

我自己通过UE的反射机制收集到的枚举有800多条，但是UEnums中只有500多条。
请问slua是如何决定要导出哪些枚举的？为何不通过UE的反射机制来收集需要导出的枚举呢？

**Comment by pangweiwei** [comment]
原来的设计， UEnums是自动导出了是没有标记UENUM标签的非反射enum，标记了UENUM标签的enum可以通过反射系统import，不过后来cppbinding也支持了enum，考虑可以直接手写cppbinding导出想要的enum。

所以目前UENUM全局表是个多余的设计，未来考虑删除。

**Comment by pangweiwei** [comment]
已经删除了。

目前不再存在UENUM全局表，所有反射enum，通过import导出，所有native enum，通过cppbinding导出。

**Comment by JamesHuang0331** [comment]
反馈一个问题。我刚试了下import一个枚举无效。看了一下import的代码。目前的import只会去寻找UClass和UScriptStruct，不会去寻找UEnum。看是否可以添加对UEnum反射的支持？
