### ISSUE TITLE
LuaPanda调试器支持的问题

### ISSUE THREAD

**Issue by ShrimpABC** [Tencent/sluaunreal#113]
LuaPanda支持 lua / C 双调试引擎。如果使用slua demo里加载lua文件的方式（setLoadFileDelegate）的话，会出现报错“Slua: Error: Can't load file libpdebug”，也就是无法使用LuaPanda的C调试库。请问有什么办法能加载这个库呢？

**Comment by stuartwang** [comment]
我们测试一下，有结论稍后回复

**Comment by ShrimpABC** [comment]
好的，麻烦了！

**Comment by stuartwang** [comment]
> Slua: Error: Can't load file libpdebug

我们今天测试了这个问题.

LuaPanda调试器由lua文件和一个可选的C库"libpdebug.dll"组成, 这个库的作用是提升调试效率, 它被放在LuaPanda VSCode插件中。在lua文件中会自动尝试引用"libpdebug", 即使引用不到, 也可以正常调试。

setLoadFileDelegate是slua提供给用户自行查找和加载lua文件的接口。调试器require("libpdebug")时，进入了LoadFileDelegate代理方法，LoadFileDelegate回调可能是把libpdebug当做了lua文件在package.path中查找, 所以报错。

但这个报错不影响功能。如果不使用chook. 可以修改launch.json中userCHook:false 。就不会再报错

**Comment by ShrimpABC** [comment]
好的，那之后有计划支持chook吗？

**Comment by stuartwang** [comment]
会支持。我们最近处理一下，给出使用方法或升级调试器解决

**Comment by ShrimpABC** [comment]
OK，明白了，谢谢！

**Comment by stuartwang** [comment]
我们今天重新做了测试，报错的原因是state.setLoadFileDelegate中没有处理.so/dll。 这个报错不影响c库的使用，使用LuaPanda.getInfo()可以看到c库被正确加载了。
用户在重写setLoadFileDelegate时注意处理一下.so/dll， 即可消除报错。
