### ISSUE TITLE
InpAxisEvt_Turn_K2Node_InputAxisEvent_157

### ISSUE THREAD

**Issue by huiger8723** [Tencent/sluaunreal#115]
这种函数名是怎么生成的，后面的157怎么来的

**Comment by pangweiwei** [comment]
blueprint动态生成的，取决于你在project setting里的配置，你是问的附带的那个 fps demo的问题吧？

**Comment by huiger8723** [comment]
嗯，是的，我是想问demo里面lua代码里面的这个函数名怎么生成的，我新建的项目写这个函数的时候名字应该怎么写？

**Comment by pangweiwei** [comment]
demo里的写法是我们找到的blueprint可以重载的key event的设置在lua里实现的方法，但我认为应该有更通用的做法，只不过写demo那个人没有研究（demo不是我写的），比如你可以在蓝图里挂在一个calllua的node，调用到你的lua代码。

**Comment by huiger8723** [comment]
意思是在蓝图里实现Axis的“Turn”这个函数，函数的具体实现里面在调用lua的代码吗？这种方法确实可以，我现在就是这么做的，只是研究demo的时候在好奇demo里面的函数名是怎么写的，谢谢了，兄弟
