### ISSUE TITLE
扩展FLuaBPVar的问题

### ISSUE THREAD

**Issue by ShrimpABC** [Tencent/sluaunreal#117]
我想在蓝图调用lua函数的时候能够传入UClass类型的参数，所以仿照CreateVarFromObject的写法新增了CreateVarFromUClass。测试发现，在蓝图的Event（如Event BeginPlay）中调用含有UClass参数的Lua函数后，通过CreateVarFromUClass创建的FLuaBPVar（UClass）在Event结束后没有调用gcClass(lua_State* L)进行GC，而在游戏关闭时才调用gcClass，请问是为什么啊？

另外测试了Lua调用蓝图函数，蓝图函数再调用Lua函数的情况。发现在这种情况下，UClass参数会被及时GC掉。
![捕获](https://user-images.githubusercontent.com/22850285/57700178-feddef00-768b-11e9-94df-0aa9b251aced.JPG)

**Comment by pangweiwei** [comment]
你通过CreateVarFromUClass传入的uclass是blueprint自己管理生命周期的，可能它还持有uclass的引用，又或者你传递到lua后，被lua变量持有，才会导致不能释放。

 

发件人: <noreply@github.com> 代表 ShrimpABC <notifications@github.com>
答复: Tencent/sluaunreal <reply@reply.github.com>
日期: 2019年5月14日 星期二 下午9:10
收件人: Tencent/sluaunreal <sluaunreal@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [Tencent/sluaunreal] 扩展FLuaBPVar的问题 (#117)

 

我想在蓝图调用lua函数的时候能够传入UClass类型的参数，所以仿照CreateVarFromObject的写法新增了CreateVarFromUClass。测试发现，在蓝图的Event（如Event BeginPlay）中调用含有UClass参数的Lua函数后，通过CreateVarFromUClass创建的UClass在Event结束后没有调用gcClass(lua_State* L)进行GC，而在游戏关闭时才调用这个UClass的GC，请问是为什么啊？

另外测试了Lua调用蓝图函数，蓝图函数再调用Lua函数的情况。发现在这种情况下，UClass参数会被及时GC掉。

**Comment by ShrimpABC** [comment]
查了一下，应该是蓝图还有UClass引用。如果把CallLuaMember放在蓝图函数内使用，对于UClass的引用会被解除，所以这种情况下会及时GC。谢谢！
