### ISSUE TITLE
lua脚本和c++实例不能统一

### ISSUE THREAD

**Issue by fdcumt** [Tencent/sluaunreal#118]
在slua中,如果我为每个类配置一个lua脚本, 那么在运行时候, 每个c++实例就可以有对应的lua脚本, 目前我们项目的逻辑都写在lua中, 但是在使用的时候需要通过lua脚本调用对应的c++实例. 有的时候也需要从c++实例调用对应lua脚本中的函数或变量
现在我做的方法是为每个类写了一个UFunction, 暴露luatable 给lua, 即可以通过c++实例获取对应的lua table, 但是, 这个写起来特别别扭, 每次都要多写好多额外的代码, 能不能有一个统一的接口, 来像原生的lua操作一样, 操作c++和lua中的成员和函数.(虽然CallLuaMember可以实现, 但只能用于lua函数, 不能调用lua变量, 并且,CallLuaMember在传入函数参数的方式也不友好, 必须是一个数组.... )

**Comment by fdcumt** [comment]
我现在的想法是在 luabase 的init函数内, 遍历对应的luatable, 并作为UFunction 或者UVariable存入c++实例中, 不过我还没有开始改, 不知道可不可行

**Comment by pangweiwei** [comment]
不明白你的需求，感觉你的需求使用cppbinding和luavar可以完成

发自我的 iPhone

**Comment by fdcumt** [comment]
我目前的需求是在lua中通过userdata可以调用c++中的成员变量和函数，也可以调用lua中的成员函数和变量，而且它们的用法就像原生lua一样方便

**Comment by pangweiwei** [comment]
还是没明白，你的困难是？

发自我的 iPhone

**Comment by zengdelang** [comment]
@fdcumt 你的需求应该是想通过LuaTable的self来调用C++对象的方法把，比如self:CppMethod(),分享下我的方案：
1 基于面向对象
-----------------------------------------------------------------------------
-- Lua面向对象基础实现
-- 
-- 实现一个类
--     local ParentClass = Class()            --实现一个叫ParentClass的类
--     function ParentClass:Ctor()            --定义构造函数
--     end
--     function ParentClass:Hello()           --定义一个类方法
--     end
--
--     local ChildClass = Class(ParentClass)  --实现一个叫ChildClass的类并继承于ParentClass
--     function ParentClass:Ctor(Index)       --定义构造函数
--         self.Index = Index
--     end
--     function ChildClass:ChildHello()       --定义一个类方法
--     end
--
-- 生成对象
--     local ParentInst = ParentClass()       --从ParentClass中生成一个对象
--     ParentInst:Hello()                   
--
--     local ChildInst = ChildClass(1)        --从ChildClass中生成一个对象
--     ChildInst:Hello()                      --调用父类的Hello方法
--     ChildInst:ChildHello()            
--     print(ChildInst.Index)
--
--     local ChildInst = ChildClass(2)        --从ChildClass中生成一个对象
--     ChildInst:Hello()                      --调用父类的Hello方法
--     ChildInst:ChildHello()            
--     print(ChildInst.Index)
-----------------------------------------------------------------------------

local _class={}

function Class(super)
    local ClassType={}
    ClassType.Ctor     = false
    ClassType.Super    = super

    local vtbl={}
    _class[ClassType]=vtbl

    setmetatable(ClassType,
            {
                __index = vtbl,

                __newindex = function(t,k,v)
                    vtbl[k]=v
                end,

                __call = function(ClassType, ...)
                    local obj={}
                    setmetatable(obj,{ __index = _class[ClassType]})
                    do
                        local create
                        create = function(c,...)
                            if c.Super then
                                create(c.Super,...)
                            end

                            if c.Ctor then
                                c.Ctor(obj,...)
                            end
                        end

                        create(ClassType, ...)
                    end
                    return obj
                end
            })

    if super then
        setmetatable(vtbl,
                {
                    __index = function(t,k)
                        local ret=_class[super][k]
                        vtbl[k]=ret
                        return ret
                    end
                })
    end

    return ClassType
end

2 实现一个绑定c++对象的类

-----------------------------------------------------------------------------
-- 继承自C++对象的Lua类实现
--
-- 使用方法:
--     local LuaClass = Class(CppBaseClass)
--     function LuaClass:Hello()               --定义一个Lua方法
--         self:CppMethod()                    --直接使用self调用C++对象的CppMethod方法
--     end
--
--     local LuaInst = LuaClass(cppInst)       --从LuaClass中生成一个对象并继承于cppInst这个C++对象
-----------------------------------------------------------------------------

---@class CppBaseClass : ObjectBase
CppBaseClass = Class(ObjectBase)

function CppBaseClass:Ctor(cppInst)
    local mt = getmetatable(self)
    local vtbl = mt.__index
    self.__vtbl = vtbl
    self.__cppinst = cppInst

    mt.__newindex = function (t,k,v)
        local cppinst = rawget(t, "__cppinst")
        if IsValid(cppinst) and cppinst[k] ~= nil then
            cppinst[k] = v
            return
        end
        rawset(t, k, v)
    end

    mt.__index = function(t, k)
        local v = vtbl[k]
        if v then
            return v
        end

        local cppinst = rawget(t, "__cppinst")
        if IsValid(cppinst) then
            local v = cppinst[k]
            if type(v) == "function" then
                rawset(t, k, v)
            end
            return v
        end
    end
end

--- 判断对象是否是有效的
function CppBaseClass:IsValid()
    -- 如果__cppinst在UE中已经无效，则该对象无效
    return IsValid(rawget(self, "__cppinst"))
end

return CppBaseClass

3 C++调用一个全局函数

--- 绑定Lua实现到C++对象上, 对应的模块内部类实现应该继承自CppBaseClass类或其子类
function BindLuaToObject(Obj)
    local objectClass = require(Obj.LuaPath)
    return objectClass(Obj)
end

Obj是C++对象，C++层调用，有一个LuaPath的蓝图可反射调用的变量，C++层保存返回的LuaTable

**Comment by fdcumt** [comment]
额，可能是我描述的不够清晰，或者slua已经有了我没找到，我明天贴几段代码，结合代码描述一下我的需求

**Comment by fdcumt** [comment]
@zengdelang 看来我真的没表达清晰。我目前遇到的问题是：在写ui逻辑的时候，每个userwidget对应一个lua脚本，ui的全部逻辑都在lua中，但是，在操作ui控件的时候，有些控件作为子控件add到父控件中，比如listview，我只能通过listview拿到子控件的c++指针，但是我不能通过这个指针操作它对应的luatable，我目前的方法是再通过这个指针拿到对应的laudable，而且我也不能通过这个luatable操作对应的c++成员

**Comment by zengdelang** [comment]
另外为了方便push一个c++实例对象的时候，能直接获取的table的做法，建议修改slua的下面的代码，自己实现的和Lua关联的c++类，实现一个自定义的蓝图接口ILuaTableObjectInterface，这样push一个c++对象到Lua中时，就能直接push一个LuaTable，在Lua中直接使用Table的方式来做
 
	int LuaObject::push(lua_State* L, UObject* obj) {
		if (!obj) { lua_pushnil(L); return 1; }

		ILuaTableObjectInterface* LuaTableObj = Cast<ILuaTableObjectInterface>(obj);
		if (LuaTableObj && ILuaTableObjectInterface::isValid(LuaTableObj))
		{
			return ILuaTableObjectInterface::push(L, LuaTableObj);
		}
		return pushGCObject<UObject*>(L, obj, "UObject", setupInstanceMT, gcObject);
	}

ULuaTableObjectInterface::ULuaTableObjectInterface(const class FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
{

}

bool ILuaTableObjectInterface::isValid(ILuaTableObjectInterface* luaTableObj)
{
	return luaTableObj && luaTableObj->LuaTable.isTable() && luaTableObj->LuaTable.isValid();
}

int ILuaTableObjectInterface::push(slua::lua_State* L, ILuaTableObjectInterface* luaTableObj)
{
	return slua::LuaObject::push(L, luaTableObj->LuaTable);
}

**Comment by zengdelang** [comment]
@fdcumt 你这个ListView的需求我也遇到了，我就是这么解决的，好使

**Comment by zengdelang** [comment]
不能通过这个luatable操作对应的c++成员，这个问题需要按照的面向对象的方式来搞，把lua和c++绑定在一起，就能通过table的self来直接访问c++成员（反射或静态导出）

**Comment by fdcumt** [comment]
@zengdelang 非常感谢, 受你启发, 我想到另个一个方法:
把luabase改成一个interface接口:
![image](https://user-images.githubusercontent.com/10294860/57711726-d9f47680-76a1-11e9-8de6-f232c497fb32.png)
![image](https://user-images.githubusercontent.com/10294860/57711749-eb3d8300-76a1-11e9-8a54-e1ce25763496.png)
然后在push的时候检查一下, 类似于你给的这段代码:
![image](https://user-images.githubusercontent.com/10294860/57711831-17590400-76a2-11e9-813c-940278a8231e.png)

由于checkvalue的时候, 都会检查是否是table
![image](https://user-images.githubusercontent.com/10294860/57711909-38215980-76a2-11e9-926f-e9e855ac0cff.png)

所以在lua脚本中, 我也可以传入luatable, 它会自动找到对应的UObject.

这样, 我在写lua逻辑的时候,它会优先调用lua的变量或者函数, 然后才是cpp的.
在c++层, 如果lua重写了, 根据以下规则, 也会优先调用lua代码.
![image](https://user-images.githubusercontent.com/10294860/57713094-6142e980-76a4-11e9-8760-a07f35ec586e.png)


不过, 要实现以上的内容, 还需要在__newindex的内容里面加东西
![image](https://user-images.githubusercontent.com/10294860/57713200-8e8f9780-76a4-11e9-8409-0b1c9701ad01.png)

在类似于__newindex的回调函数中
![image](https://user-images.githubusercontent.com/10294860/57713212-994a2c80-76a4-11e9-89ed-d5ce5377384e.png)

如果没有找到对应的变量, 就添加类似于这样的代码(当然,还得想办法取出来对应的luatable):
![image](https://user-images.githubusercontent.com/10294860/57713295-c565ad80-76a4-11e9-80ae-0d9646ab435d.png)

这样如果一个c++ class配置了一个lua脚本, 在lua层, 就可以把他们视为一个整体, 直接操作.


不知道以上方法行不行的通, 不过思路好像是对的, 明天试试.


还有我不使用"lua继承c++类"这种方式的原因是, 如果使用这种方法, 当我想在lua层重写一个c++方法的时候, 我还得再给这个c++添加一个lua脚本, 这样, 这个c++类就要对应两个lua脚本了, 会增加很多工作量.

类似于在使用ListView时候, 对于listview中的item, 必须重写这些方法:
![image](https://user-images.githubusercontent.com/10294860/57713979-132ee580-76a6-11e9-9c86-9d169be4129f.png)

**Comment by zengdelang** [comment]
嗯，看你需求了，我是没有使用LuaBase的，一方面是LuaBase还没支持的时候我就实现了自己LuaBaseActor等功能，如果你直接改LuaBase后续升级会比较麻烦，我是在slua的基础上又包装了一个插件，减少升级的难度，另外LuaBase的功能较弱并且在ProcessEvent中查找Lua实现，对于高频率的操作，比如ReceiveTick等感觉消耗大，我都是自己控制这些函数的导出，另外我在自己的LuaBaseActor基础上实现了Lua的RPC和属性同步，所以LuaBase不满足我的要求，我自己的C++类也只需要对应一个Lua脚本就行

**Comment by fdcumt** [comment]
@zengdelang 你的方法在lua脚本中进行赋值的时候, 如果没有在查找到相关变量, 会在lua表中添加新成员吗?
你现在是用继承方式, __index索引的是c++类, 你的__newindex索引的是什么? 如果也是c++类, 那么如果没找相关成员就会报错, 不会在lua表中insert一个成员
如果不是c++类,你就不能索引c++成员变量了.............

**Comment by pangweiwei** [comment]
目前LuaBase自实现的机制里，会搜索c++属性，如果没有会添加一个数据到table里。

**Comment by pangweiwei** [comment]
参考这里：https://github.com/Tencent/sluaunreal/blob/953edb6407def5602aeb792cd049858aab01809b/Plugins/slua_unreal/Source/slua_unreal/Private/LuaBase.cpp#L80

**Comment by fdcumt** [comment]
不好意思, 以前没仔细看过这块代码, 原来已经实现了这个功能(里面各种堆栈push和pop, 真的好复杂).
我还有一个问题, 就是为什么不把Luabase以接口的方式实现? 
如果以接口方式实现, 这写函数和变量就可以直接加UFunction或者UProperty, 而不用在子类里面重写了啊
![image](https://user-images.githubusercontent.com/10294860/57746543-240e4400-7704-11e9-8804-8e2888841f9b.png)

**Comment by pangweiwei** [comment]
UInterface不支持添加UProperty，同时使用了UInterface，一些宏展开无法工作，这是uht的限制。

 

发件人: <noreply@github.com> 代表 fu <notifications@github.com>
答复: Tencent/sluaunreal <reply@reply.github.com>
日期: 2019年5月15日 星期三 上午11:25
收件人: Tencent/sluaunreal <sluaunreal@noreply.github.com>
抄送: siney <sineysan@163.com>, Comment <comment@noreply.github.com>
主题: Re: [Tencent/sluaunreal] lua脚本和c++实例不能统一 (#118)

 

不好意思, 以前没仔细看过这块代码, 原来已经实现了这个功能(里面各种堆栈push和pop, 真的好复杂).
我还有一个问题, 就是为什么不把Luabase以接口的方式实现?
如果以接口方式实现, 这写函数和变量就可以直接加UFunction或者UProperty, 而不用在子类里面重写了啊

**Comment by zengdelang** [comment]
这里的工作原理是,给table的一个成员赋值的时候会调用newindex, 首先判断C++对象是否有同名成员，如果有，则更新C++的成员，否则将值直接设置到table上面
index元方法是当需要获取table的成员时调用，首先先从table的虚函数表vtbl中找同名成员，找到则返回，找不到再找c++对象的同名成员，如果是函数，则直接设置到table对象本身，避免下一次又通过反射去查找同名的函数
mt.__newindex = function (t,k,v)
    local cppinst = rawget(t, "__cppinst")
    if IsValid(cppinst) and cppinst[k] ~= nil then
        cppinst[k] = v
        return
    end
    rawset(t, k, v)
end

mt.__index = function(t, k)
    local v = vtbl[k]
    if v then
        return v
    end

    local cppinst = rawget(t, "__cppinst")
    if IsValid(cppinst) then
        local v = cppinst[k]
        if type(v) == "function" then
            rawset(t, k, v)
        end
        return v
    end
end

**Comment by fdcumt** [comment]
谢谢二位, 解释的都非常详尽了.

**Comment by 616050468** [comment]
> 嗯，看你需求了，我是没有使用LuaBase的，一方面是LuaBase还没支持的时候我就实现了自己LuaBaseActor等功能，如果你直接改LuaBase后续升级会比较麻烦，我是在slua的基础上又包装了一个插件，减少升级的难度，另外LuaBase的功能较弱并且在ProcessEvent中查找Lua实现，对于高频率的操作，比如ReceiveTick等感觉消耗大，我都是自己控制这些函数的导出，另外我在自己的LuaBaseActor基础上实现了Lua的RPC和属性同步，所以LuaBase不满足我的要求，我自己的C++类也只需要对应一个Lua脚本就行

请问具体是怎么实现在lua层的属性同步呀

**Comment by 616050468** [comment]
> 嗯，看你需求了，我是没有使用LuaBase的，一方面是LuaBase还没支持的时候我就实现了自己LuaBaseActor等功能，如果你直接改LuaBase后续升级会比较麻烦，我是在slua的基础上又包装了一个插件，减少升级的难度，另外LuaBase的功能较弱并且在ProcessEvent中查找Lua实现，对于高频率的操作，比如ReceiveTick等感觉消耗大，我都是自己控制这些函数的导出，另外我在自己的LuaBaseActor基础上实现了Lua的RPC和属性同步，所以LuaBase不满足我的要求，我自己的C++类也只需要对应一个Lua脚本就行

请问Lua的RPC和属性同步是怎么搞的，思路是怎样的？可否分享一下
