### ISSUE TITLE
存在严重的内存增长问题

### ISSUE THREAD

**Issue by zengdelang** [Tencent/sluaunreal#124]
只运行demo下面的脚本，在tick中调用GetOwner
![QQ浏览器截图20190518002726](https://user-images.githubusercontent.com/4466062/57942335-c0eb0000-7903-11e9-909f-5a16d027e6c4.png)
发现内存占用在1分钟后有几百kb的增长，注释掉tick中的GetOwner，发现内存占用平稳
![QQ浏览器截图20190518002840](https://user-images.githubusercontent.com/4466062/57942396-ea0b9080-7903-11e9-86d7-6fdb9bb5e8f9.png)

**Comment by pangweiwei** [comment]
我测试并没有发现你提到的问题

Slua:     owner   nil
Slua: Unreal engine GC, lua used 106 KB
Slua:     owner   nil
Slua: Unreal engine GC, lua used 107 KB
Slua:     owner   nil
Slua: Unreal engine GC, lua used 106 KB
Slua:     owner   nil
Slua: Unreal engine GC, lua used 107 KB
Slua:     owner   nil
Slua: Unreal engine GC, lua used 106 KB
Slua:     owner   nil
Slua: Unreal engine GC, lua used 107 KB
Slua:     owner   nil
Slua: Unreal engine GC, lua used 106 KB
Slua:     owner   nil
Slua: Unreal engine GC, lua used 107 KB
Slua:     owner   nil
Slua: Unreal engine GC, lua used 106 KB
Slua:     owner   nil
Slua: Unreal engine GC, lua used 107 KB

demo没有那么多内存占用，我看你有1M左右

**Comment by zengdelang** [comment]
我再测试下，这个问题是因为我在项目中也发现内存增长过快，除了粗暴的每一帧从C++中获取FVector导致的以外，我发现每一帧调用一个Actor的一个组件的反射方法也会不断增长内存，虽然比获取FVector要少很多，这是我昨晚使用slua的demo测试的，当时我是新建了一个关卡，把LuaBpActor拖进去测试，我也很奇怪怎么会有1m的内存占用，我在项目中初始打开也就几百kb，稍后我拉个最新demo试下

**Comment by zengdelang** [comment]
更新到最新版还有是内存增长问题
Slua: Unreal engine GC, lua used 142 KB
Slua: Unreal engine GC, lua used 255 KB
Slua: Unreal engine GC, lua used 204 KB
Slua: Unreal engine GC, lua used 176 KB
Slua: Unreal engine GC, lua used 249 KB
Slua: Unreal engine GC, lua used 254 KB
Slua: Unreal engine GC, lua used 209 KB
Slua: Unreal engine GC, lua used 149 KB
Slua: Unreal engine GC, lua used 277 KB

这次的测试方法，是声明了三个蓝图方法在lua中调用
function actor:ReceiveTick(dt)
    -- print("bpactor:ReceiveTick",self,dt)
    --local owner = self:GetOwner()
    self:GetBool()
    self:GetInt()
    self:GetFloat()
end

**Comment by morirain** [comment]
我做了同样的测试，没有出现这种情况

Slua: Unreal engine GC, lua used 156 KB
Slua: Unreal engine GC, lua used 156 KB
Slua: Unreal engine GC, lua used 156 KB
Slua: Unreal engine GC, lua used 156 KB
Slua: Unreal engine GC, lua used 156 KB
Slua: Unreal engine GC, lua used 156 KB
Slua: Unreal engine GC, lua used 156 KB
Slua: Unreal engine GC, lua used 156 KB
Slua: Unreal engine GC, lua used 156 KB
Slua: Unreal engine GC, lua used 156 KB
Slua: Unreal engine GC, lua used 155 KB
Slua: Unreal engine GC, lua used 155 KB
Slua: Unreal engine GC, lua used 155 KB
Slua: Unreal engine GC, lua used 155 KB
Slua: Unreal engine GC, lua used 155 KB

**Comment by zengdelang** [comment]
什么版本？我在4.21，4.22上测试都有这个问题

**Comment by pangweiwei** [comment]
我是4.21，不管是用LuaBpActor测试，还是用LuaActor测试，都没有问题。

**Comment by zengdelang** [comment]
我是在自己的电脑和公司的电脑都测试过，公司的电脑使用self:GetOwner倒是没什么内存增长，另一种情况有增长，比如在Actor中添加一个StaticMesh组件，lua中每一帧调用
function actor:ReceiveTick(dt)
    self.StaticMesh:GetOwner()
end

不过问题最严重的其实是从C++中获取结构体操作，比如
function actor:ReceiveTick(dt)
    self:k2_GetActorLocation()
end
这个内存增长最快，以及在Lua中从TArray中获取结构体，这有什么好的优化方案吗？这个问题导致基本不能在Lua中频繁的获取C++中的结构体进行运算

**Comment by pangweiwei** [comment]
结构体也没有问题，虽然每个结构体是单独的内存，但很快就被回收了，你看自带的例子也是大量操作结构体计算位置发自我的华为手机-------- 原始邮件 --------主题：Re: [Tencent/sluaunreal] 存在严重的内存增长问题 (#124)发件人：zengdelang 收件人：Tencent/sluaunreal 抄送：siney ,Comment 我是在自己的电脑和公司的电脑都测试过，公司的电脑使用self:GetOwner倒是没什么内存增长，另一种情况有增长，比如在Actor中添加一个StaticMesh组件，lua中每一帧调用
function actor:ReceiveTick(dt)
self.StaticMesh:GetOwner()
end
不过问题最严重的其实是从C++中获取结构体操作，比如
function actor:ReceiveTick(dt)
self:k2_GetActorLocation()
end
这个内存增长最快，以及在Lua中从TArray中获取结构体，这有什么好的优化方案吗？这个问题导致基本不能在Lua中频繁的获取C++中的结构体进行运算

**Comment by zengdelang** [comment]
并没有很快回收，我在项目中测试用多的话会四五分钟就跑到4，5m, 最多能跑到50,60m,只有我自己collectgarbage的时候才会看到下次占用变少，这是我自己使用上面的测试跑了几分钟的占用
Slua: Unreal engine GC, lua used 379 KB
Slua: Unreal engine GC, lua used 1141 KB
Slua: script run time 1
Slua: Unreal engine GC, lua used 1426 KB
Slua: Unreal engine GC, lua used 1710 KB
Slua: Unreal engine GC, lua used 2511 KB
Slua: Unreal engine GC, lua used 2052 KB
Slua: Unreal engine GC, lua used 2321 KB
Slua: Unreal engine GC, lua used 2341 KB
Slua: Unreal engine GC, lua used 2361 KB
Slua: Unreal engine GC, lua used 2798 KB
Slua: Unreal engine GC, lua used 2300 KB
Slua: Unreal engine GC, lua used 3049 KB
Slua: Unreal engine GC, lua used 3378 KB
Slua: Unreal engine GC, lua used 3752 KB

**Comment by pangweiwei** [comment]
lua的内存本来就不是立刻回收的，如果你collectgarbage可以回收，说明并不存在内存泄漏，只是你在lua内分配的内存还没来得及回收。

如果你在意这个，你可以在luastate.init(true)的时候打开，thread gc，这样内存会控制的好一点。

**Comment by zengdelang** [comment]
目前看来只能这样了，打算把频繁的操作还是让给c++和蓝图来做，避免频繁的内存分配和回收
