### ISSUE TITLE
lua-wrapper导出问题

### ISSUE THREAD

**Issue by ShrimpABC** [Tencent/sluaunreal#125]
1. 我想使用lua-wrapper导出引擎内的FGameplayTag和FGameplayTagContainer，按照说明导出后，重新build项目发现了新生成的LuaWrapper.cpp出现了编译错误，不知道lua-wrapper是否支持这样的USTRUCT导出呢？
2. 发现lua-wrapper导出的FGameplayTag中并没有包含它的静态函数RequestGameplayTag，请问在Lua中改如何调用它的静态函数呢？
![捕获](https://user-images.githubusercontent.com/22850285/57966370-7b6e1780-7983-11e9-915e-d365df159fd9.JPG)

**Comment by pangweiwei** [comment]
使用cppbinding，手写吧，类似：

DefLuaClass(IHttpResponse)
		DefLuaMethod(GetResponseCode, &IHttpResponse::GetResponseCode)
	EndDef(IHttpResponse, nullptr)

	DefLuaClass(IHttpRequest)
		DefLuaMethod(GetResponse, &IHttpRequest::GetResponse)
		DefLuaMethod(SetVerb, &IHttpRequest::SetVerb)
		DefLuaMethod(ProcessRequest, &IHttpRequest::ProcessRequest)
		DefLuaMethod(SetURL, &IHttpRequest::SetURL)
		DefLuaMethod(SetContent, &IHttpRequest::SetContent)
		DefLuaMethod(OnRequestProgress, &IHttpRequest::OnRequestProgress)
		DefLuaMethod(OnProcessRequestComplete, &IHttpRequest::OnProcessRequestComplete)
#if (ENGINE_MINOR_VERSION>=20) && (ENGINE_MAJOR_VERSION>=4)
		DefLuaMethod(OnHeaderReceived, &IHttpRequest::OnHeaderReceived)
#endif
	EndDef(IHttpRequest, nullptr)

	DefLuaClass(FHttpModule)
		DefLuaMethod_With_Lambda(Get, true, []()->FHttpModule* {
		return &FHttpModule::Get();
		})
		DefLuaMethod(CreateRequest, &FHttpModule::CreateRequest)
		DefLuaMethod(GetHttpTimeout, &FHttpModule::GetHttpTimeout)

	EndDef(FHttpModule,nullptr)

**Comment by ShrimpABC** [comment]
好的，另外想问一下是不是理论上cppbinding可以完全替代lua-wrapper呢

**Comment by pangweiwei** [comment]
是的，完全可以替代发自我的华为手机-------- 原始邮件 --------主题：Re: [Tencent/sluaunreal] lua-wrapper导出问题 (#125)发件人：ShrimpABC 收件人：Tencent/sluaunreal 抄送：siney ,Comment 好的，另外想问一下是不是理论上cppbinding可以完全替代lua-wrapper呢

**Comment by ShrimpABC** [comment]
OK，了解了，谢谢！
