### ISSUE TITLE
存在一些错误

### ISSUE THREAD

**Issue by morirain** [Tencent/sluaunreal#126]
在demo中测试以下代码
```
local KismetMath = import("KismetMathLibrary")
local newRotation = KismetMath:MakeRotFromX(FVector(-1, 0, 1))
print("adsasdfadsf",newRotation.Pitch, newRotation.Roll, newRotation.Yaw)
```
得到的结果一直是
`Slua:     adsasdfadsf 0.0 0.0 0.0`

如果改为在蓝图中调用，会得出正确的结果。

**Comment by pangweiwei** [comment]
你应该使用：
KismetMath.MakeRotFromX(FVector(-1, 0, 1))

**Comment by pangweiwei** [comment]
另外，我增加了类型检查，现在你使用 KismetMath:MakeRotFromX(FVector(-1, 0, 1)) 会报错
