### ISSUE TITLE
请教cppbinding的问题

### ISSUE THREAD

**Issue by ShrimpABC** [Tencent/sluaunreal#127]
我在使用cppbinding时，发现了传递参数错误的问题，具体是：
![捕获](https://user-images.githubusercontent.com/22850285/57999618-9322d880-7b08-11e9-9559-9120d65115bb.JPG)
首先绑定了自定义类Test，其中有函数Hit，接收FHitResult的指针作为参数。
在lua环境中有如下代码：
![捕获1](https://user-images.githubusercontent.com/22850285/57999794-3ecc2880-7b09-11e9-8607-839bd50c2d56.JPG)
输出的结果为0和12345，与预期不同。
在Hit函数内断点，发现参数Res疑似为野指针。
尝试将Res作为引用类型传入得出的结果也不对。
另外测试了将Hit函数作为ufunction放在反射系统支持的UClass里，这种情况下的输出是正确的。
请问是为什么呢？是不是我的用法有问题啊？

**Comment by pangweiwei** [comment]
使用FHitResult&

 

发件人: <noreply@github.com> 代表 ShrimpABC <notifications@github.com>
答复: Tencent/sluaunreal <reply@reply.github.com>
日期: 2019年5月20日 星期一 下午2:17
收件人: Tencent/sluaunreal <sluaunreal@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [Tencent/sluaunreal] 请教cppbinding的问题 (#127)

 

我在使用cppbinding时，发现了传递参数错误的问题，具体是：

首先绑定了自定义类Test，其中有函数Hit，接收FHitResult的指针作为参数。
在lua环境中有如下代码：

输出的结果为0和12345，与预期不同。
在Hit函数内断点，发现参数Res疑似为野指针。
尝试将Res作为引用类型传入得出的结果也不对。
另外测试了将Hit函数作为ufunction放在反射系统支持的UClass里，这种情况下的输出是正确的。
请问是为什么呢？是不是我的用法有问题啊？

**Comment by ShrimpABC** [comment]
使用FHitResult& Res的形式会出现编译错误，而const FHitResult& Res的形式虽然不会报错，但是结果也不符合预期

**Comment by pangweiwei** [comment]
目前 反射系统的结构体，不能和cppbinding的函数结合在一起混合使用。我要思考下如何支持。

**Comment by ShrimpABC** [comment]
好的，那我暂时将cppbinding的类改成UClass来使用吧

**Comment by pangweiwei** [comment]
我提交了一个patch，cppbinding函数支持支持ustruct参数

**Comment by ShrimpABC** [comment]
好快呀。。。谢谢，向大佬学习！
