### ISSUE TITLE
发现一个新版本的奇怪问题

### ISSUE THREAD

**Issue by ShrimpABC** [Tencent/sluaunreal#129]
我尝试将新版本(5.20日版本)的slua移入已有老版本slua的项目中，所以覆盖了slua_unreal文件夹并删除了文件夹下的Binaries和Intermediate文件夹重新build，发现有编译错误，具体如下：
![无标题](https://user-images.githubusercontent.com/22850285/58023402-44923000-7b42-11e9-9a2b-ce36ca5d3c02.png)

发现问题后，我又尝试build示例项目democpp，发现没有问题。但在我打开LuaWrapper.cpp后，出现了弹窗：
![无标题1](https://user-images.githubusercontent.com/22850285/58023624-d1d58480-7b42-11e9-91df-77cfdc8b4437.png)
点击 是 后rebuild，democpp也出现了与上图一样的编译错误，在discard掉luawrapper的修改之后，错误消失。

我使用的是vs2017进行编译的，之前版本的slua没有遇到过这种问题，不知是什么原因。

**Comment by pangweiwei** [comment]
fixed
