### ISSUE TITLE
我自己编写的使用BlueprintType的结构体和UPROPERTY标记的成员变量，传入lua的时候还需要手动CppBinding?

### ISSUE THREAD

**Issue by ttaw** [Tencent/sluaunreal#130]
USTRUCT(BlueprintType)
struct FDialogueRow
{
	GENERATED_USTRUCT_BODY()

	UPROPERTY(BlueprintReadWrite, EditAnywhere)
		int32 ID;
}
这样的结构体传入lua的话在编译时会有链接错误，加上DefLuaClass后可以通过，但是在lua中调用row.ID时提示can't get ID，这样的结构体变量还需要DefLuaProperty一下么？这种结构体不是可以使用反射功能的么？要是对每个成员变量加个getter/setter感觉太麻烦了。。。

**Comment by pangweiwei** [comment]
不需要

**Comment by pangweiwei** [comment]
参考SluaTestCase.h，及其使用方法。

**Comment by ttaw** [comment]
DefLuaClass需要加么？我不加这个会链接错误，提示
 error LNK2019: 无法解析的外部符号 "public: static struct slua::SimpleString __cdecl slua::TypeName<struct FDialogueRow,0>::value(void)" (?value@?$TypeName@UFDialogueRow@@$0A@@slua@@SA?AUSimpleString@2@XZ)，该符号在函数 "public: class slua::LuaVar __cdecl slua::LuaVar::call<class slua::LuaVar &,int const &,class FString const &,struct FDialogueRow const * const &,class UObjMapDataContainer * const &,class UWidgetBaseDialog * const &>(class slua::LuaVar &,int const &,class FString const &,struct FDialogueRow const * const &,class UObjMapDataContainer * const &,class UWidgetBaseDialog * const &)const " (??$call@AEAVLuaVar@slua@@AEBHAEBVFString@@AEBQEBUFDialogueRow@@AEBQEAVUObjMapDataContainer@@AEBQEAVUWidgetBaseDialog@@@LuaVar@slua@@QEBA?AV01@AEAV01@AEBHAEBVFString@@AEBQEBUFDialogueRow@@AEBQEAVUObjMapDataContainer@@AEBQEAVUWidgetBaseDialog@@@Z) 中被引用


c++调用lua时是这样写的：
FDialogueRow row;
		slua::LuaVar lfunc = luaSelfTable.getFromTable<slua::LuaVar>((const char*)TCHAR_TO_UTF8(*functionName), true);
		if (!lfunc.isValid())
			return false;
		lfunc.call(luaSelfTable, &Row);

**Comment by pangweiwei** [comment]
需要添加一个 typename，类似：
DefTypeName(FPrimaryAssetId);

参考 SluaUtil.h里的定义，新版需要添加类型信息，帮助做必要的类型检查。

**Comment by pangweiwei** [comment]
添加了这样的支持，目前可以在cppbinding里push UStruct了
