### ISSUE TITLE
请教在c++手动转换LuaVar到UProperty的问题

### ISSUE THREAD

**Issue by unicodecndddd** [Tencent/sluaunreal#131]
有需求要在得到lua的回调后(此时获得LuaVar)将其传递给蓝图的堆栈并转换成对应的类型。所以用到了slua里提供的check。代码类似如下：
DECLARE_FUNCTION(execFunction)
{
	Stack.MostRecentProperty = nullptr;
	Stack.MostRecentPropertyAddress = nullptr;
	Stack.StepCompiledIn<UProperty>(nullptr);

	UProperty* Property = Stack.MostRecentProperty
	auto checker = LuaObject::getChecker(Property);
	if (!checker) luaL_error(L, "Property %s type is not support", (const char*)TCHAR_TO_UTF8(*Property->GetClass()->GetName()));
	// set property value
	checker(L, Property, Ptr, 1);
	
	lua_pop(L, 1);
}
正常可以使用但是对于一些特殊的Property如UStrProperty就会报空指针错，发现错误在
    template<typename T>
    int checkUProperty(lua_State* L,UProperty* prop,uint8* parms,int i) {
        auto p = Cast<T>(prop);
        ensure(p);
        p->SetPropertyValue(parms,LuaObject::checkValue<typename T::TCppType>(L,i));
        return 0;
    }
发现把SetPropertyValue改为SetPropertyValue_InContainer就能正常使用。
查了一下资料好像是SetPropertyValue必须用于初始化的指针对象。

请问这边是不是设计如此？
另外如果我确实想要一个类似的功能目前有没有其他方法可以替代？

**Comment by pangweiwei** [comment]
主要是传入的 params的地址，SetPropertyValue_InContainer会计算offset，SetPropertyValue则认为params的起始地址就是String。

**Comment by pangweiwei** [comment]
另外，LuaVar提供了一个方法，是toProperty，不知道是不是就是你的需求？

**Comment by unicodecndddd** [comment]
嗯 我看了一下toProperty的实现，好像和我的写法是一样的。都是通过Property取到checker。最终都会调用到checkUProperty。

**Comment by unicodecndddd** [comment]
所以其实关键是我要手动给传入的地址做偏移是吗？

**Comment by unicodecndddd** [comment]
所以其实关键是我要手动给传入的地址做偏移是吗？

**Comment by unicodecndddd** [comment]
参考了一下slua里处理out参数类型的做法，改为如下：
`checker(L, Property, Ptr + Property->GetOffset_ForInternal(), 1);`
好像就能用了

**Comment by unicodecndddd** [comment]
感谢解答
