### ISSUE TITLE
编辑器下编写的蓝图函数库里的函数怎么调用

### ISSUE THREAD

**Issue by ttaw** [Tencent/sluaunreal#132]
现在有一个蓝图函数库LibraryBP在Content/BluePrints/ClassLib目录下，里边有一个不带任何参数的蓝图函数BPGetPlayerControllingCharacter，该怎么在lua中调用这个函数？
  我查了示例工程的lua代码，没有发现这样的操作。
  现在我使用
local player = import('/Game/BluePrints/ClassLib/LibraryBP.LibraryBP_C').BPGetPlayerControllingCharacter(worldContextObj) 发现在编辑器下可以成功，打包后import能成功，但是函数调用会出错退出。请问一下这种函数该怎么调用？

**Comment by morirain** [comment]
这样用
`slua.loadClass("/Game/Blueprints/Behavior/FL_FindNearestTarget.FL_FindNearestTarget")`

**Comment by ttaw** [comment]
这样只是获取一个class啊，里边的函数怎么调用呢？麻烦先不要关闭这个issue。

**Comment by morirain** [comment]
跟import一样用

**Comment by ttaw** [comment]
我试试打包后行不行，3x

**Comment by pangweiwei** [comment]
还有一个方法是loadObject，使用的是UE的LoadObject<T>方法

**Comment by ttaw** [comment]
刚刚测试了下，发现是蓝图原生化的问题。如果不开原生化，使用
local player = slua.loadClass('/Game/BluePrints/ClassLib/LibraryBP.LibraryBP').BPGetPlayerControllingCharacter(npc)
能成功。但是开了原生化，就不行了。这个能解决么？

**Comment by ttaw** [comment]
UClass *cls = LoadClass<UObject>(GetTransientPackage(), *objPath);
	if (cls == nullptr)
		return nullptr;
	UObject *obj = NewObject<UObject>(WorldContextObject->GetWorld(), cls, *(objPath));
我在c++里边这么写，然后lua里调用也不行。可能跟蓝图原生化有关系。

**Comment by pangweiwei** [comment]
> ```
> UClass *cls = LoadClass<UObject>(GetTransientPackage(), *objPath);
> if (cls == nullptr)
> 	return nullptr;
> UObject *obj = NewObject<UObject>(WorldContextObject->GetWorld(), cls, *(objPath));
> ```
> 
> 我在c++里边这么写，然后lua里调用也不行。可能跟蓝图原生化有关系。

你这种需要loadclass之后，在去构造它
local x = loadClasss(...)
x(world,objPath)

**Comment by ttaw** [comment]
还是不行，我是这样用的
    local cls = slua.loadClass('/Game/BluePrints/ClassLib/LibraryBP.LibraryBP')
	local obj = cls(npc:GetWorld(), '/Game/BluePrints/ClassLib/LibraryBP.LibraryBP') -- 第二个参数加不加都不行
	obj:BPGetPlayerControllingCharacter() -- 改成obj.BPGetPlayerControllingCharacter(npc)或者obj.BPGetPlayerControllingCharacter(npc:GetWorld())都不行

**Comment by ttaw** [comment]
现在问题就是：现在的方法在编辑器里运行没有任何问题。但是开启蓝图原生化并打包后调用会出错，囧

**Comment by morirain** [comment]
你把那个蓝图排除出原生化

**Comment by ttaw** [comment]
试了，排除了的话，那就可以。。。

**Comment by ttaw** [comment]
但是我以前用那个别的Lua库在原生化打包后，却是可以用的，用的上面我写那个C++的方法。。。

**Comment by pangweiwei** [comment]
我测试一下，原生化能用
LoadClass<UObject>(GetTransientPackage(), *objPath);
这样的c++调用，道理上lua也应该可以

**Comment by ttaw** [comment]
嗯，这样调用能获取到class或者object，但是随后的obj:BPGetPlayerControllingCharacter()函数调用会出错（在原生化打包的情况下）

**Comment by ttaw** [comment]
是不是slua的__index函数找函数名的时候不支持蓝图原生化呀？

**Comment by ttaw** [comment]
发现只要是在蓝图中新增加的函数，原生化打包后都无法通过lua调用。除了蓝图函数库外，我在actor蓝图里边新增的函数也不行。

**Comment by pangweiwei** [comment]
我测试是ok的，没有任何问题，你有什么报错？

**Comment by pangweiwei** [comment]
你看看在打包编译过程中，有没有类似这样的cpp文件被编译：
UATHelper: Packaging (Android（ETC2）):     [1/4] Module.NativizedAssets.gen.cpp [armv7-es2]
UATHelper: Packaging (Android（ETC2）):     [2/4] Module.NativizedAssets.cpp [armv7-es2]

这个就是原生化蓝图的cpp文件，我测试了windows和android平台都没有问题。

**Comment by ttaw** [comment]
我的报错就是在协程里边点击单步运行到下一行就退出了，没有什么提示。打包时nativizedassets.gen.cpp这种是有的，好几十个。不过我使用时对slua做过一些修改，我去看看原始版有没有这样的问题。

**Comment by ttaw** [comment]
我使用slua的github版测试了一下，还是不行，我的测试代码是这样的：
    local temp = actor
    local cls = slua.loadClass('/Game/LibBP.LibBP')
    local obj = cls(temp:GetWorld(), '/Game/LibBP.LibBP')
    local str = 'asdfasdfsdf'
    str = obj:GetTestString(temp:GetWorld()) -- 编辑器下使用obj.GetTestString会报错expect userdata at 2，改成obj:就可以了

    print(str) -- Test String OK
	
	
	复现步骤：
	1.下载sluaunreal工程，然后使用ue4.21登陆器更新版打开sluaunreal工程(打开时自动编译c++代码)
	2.在content目录下新建蓝图函数宏库LibBP，并增加函数GetTestString，添加字符串返回值，返回字符串“Test String OK”
	3.项目设置里把蓝图本地化方法改为inclusive，添加AdditionalNonAssetDirectoryToCopy路径为content目录下的lua文件夹
	4.在Test.lua文件的update函数中加入上述测试代码，lua文件update函数变成
local tt=0
function update(dt)
    tt=tt+dt
    
    TestActor.update(tt,actor)
    TestArray.update(tt)
    TestMap.update(tt)
    TestBp:update(tt)
	
    local temp = actor
    local cls = slua.loadClass('/Game/LibBP.LibBP')
    local obj = cls(temp:GetWorld(), '/Game/LibBP.LibBP')
    local str = 'asdfasdfsdf'
    str = obj:GetTestString(temp:GetWorld()) -- 编辑器下使用obj.GetTestString会报错expect userdata at 2，改成obj:就可以了

    print(str) -- Test String OK
end

	5.加入luapanda调试支持，复制luapanda和debugtool文件，并在Test.lua最末尾加入require("LuaPanda").start("127.0.0.1",8818)
。此时编辑器下运行调试可以看到打印出了Test String OK字符串
	6.打包win64项目并运行调试lua，发现在GetTestString函数这一行退出，无法执行下一步

**Comment by ttaw** [comment]
如果需要的话，我可以把工程代码和打包后的文件发上来。

**Comment by ttaw** [comment]
刚刚看log日志发现打包后报错：
bad argument #2 to 'GetTestString' (string expected, got UObject)
，这是说editor模式和打包模式参数传递方式不一样？

**Comment by pangweiwei** [comment]
GetTestString是什么样子的，是否需要传递world作为参数？

**Comment by ttaw** [comment]
GetTestString就是一个蓝图里没有任何参数的函数，它仅仅返回一个字符串Test String OK。不过以前lua调用的时候都要多传入一个world参数。

**Comment by ttaw** [comment]
str = obj:GetTestString(temp:GetWorld())  -- 报错bad argument #2 to 'GetTestString' (string expected, got UObject)
str = obj.GetTestString(temp:GetWorld())  -- 报错expect userdata at 2
str = obj.GetTestString() -- 报错expect userdata at 1
str = obj:GetTestString() -- expect userdata at 2

以上都是在原生化打包情况下测试的

**Comment by pangweiwei** [comment]
需要world参数的蓝图，都有一个slot是world context，是自动添加的，你的有吗？没有就不需要world

![企业微信截图_155857809222](https://user-images.githubusercontent.com/6227270/58221275-8d193b80-7d44-11e9-9d3e-47f87353fe13.png)

如下lua代码调用，

```lua
    local util = slua.loadClass("Blueprint'/Game/util.util'")
    util.Foo(world)
```

原生化设置：

![企业微信截图_15585782249249](https://user-images.githubusercontent.com/6227270/58221354-da95a880-7d44-11e9-9e55-c84f2bccd647.png)

**Comment by ttaw** [comment]
![image](https://user-images.githubusercontent.com/7946746/58221432-16c90900-7d45-11e9-900b-d82c63b13983.png)
我的函数是这样的，测试结果见上面的回答
使用你提供的方法测试结果是这样的：
   local cls = slua.loadClass('/Game/LibBP.LibBP')
    str = cls.GetTestString() -- 报错 expect userdata at 1
	str = cls.GetTestString(temp:GetWorld()) -- 报错bad argument #2 to 'GetTestString' (string expected, got UObject)

**Comment by ttaw** [comment]
刚刚测试了一下，发现竟然要这么调
    local str
    local cls = slua.loadClass('/Game/LibBP.LibBP')
    str = cls.GetTestString(temp:GetWorld(), str) 
真神奇。如果换成cls.GetTestString(temp:GetWorld(), str)就是前边不加str=的话，str值不会变。如果写成 str = cls.GetTestString(temp:GetWorld())，就会报错 bad argument #2 to 'GetTestString' (string expected, got UObject)。

**Comment by pangweiwei** [comment]
我看了下他生成的原生化代码

```c++
	UFUNCTION(BlueprintCallable, meta=(WorldContext="__WorldContext", Category, OverrideNativeName="GetTestString"))
	static void bpf__GetTestString__pf(UObject* bpp____WorldContext__pf, /*out*/ FString& bpp__Result__pf);
```
bpp__Result__pf 本来应该是返回值，他UE处理为FString&，即out类型的参数，目前slua出来out参数，需要传入参数，然后会在返回值额外返回out类型的参数。

如果没有原生化的函数没有这个问题。

**Comment by ttaw** [comment]
这样的设定以后会改吗？要是不改的话，我调用时加个nil就行（editor或者原生化打包都没问题）。

**Comment by pangweiwei** [comment]
不会修改，本来的语义就是为了支持T& 这样的参数，可能当做out类型参数，也可能需要先传入，再修改的可能，所以需要传入一个参数，只是对于原生化的蓝图函数，返回值当做out参数理解时，传入的参数没有意义，你可以传入nil。

**Comment by ttaw** [comment]
ok，thanks。
