### ISSUE TITLE
Fatal error: multiple Lua VMs detected

### ISSUE THREAD

**Issue by fdcumt** [Tencent/sluaunreal#134]
在MyGameInstance.cpp 文件中添加如下代码:
static int32 PrintLog(slua::lua_State * L)
{
	FString str;
	size_t len;
	const char* s = luaL_tolstring(L, 1, &len);
	if (s) str += UTF8_TO_TCHAR(s);
	slua::Log::Log("PrintLog %s", TCHAR_TO_UTF8(*str));
	return 0;
}

static const struct luaL_Reg reg_lib[] = {
	{"PrintLog", PrintLog}
};

static int luaopen_tool(lua_State *L) {
	luaL_newlib(L, reg_lib);
	lua_setglobal(L, "tool");
	return 0;
}

void UMyGameInstance::LuaStateInitCallback()
{
	slua::lua_State *L = state.getLuaState();
	luaL_requiref(L, "base", luaopen_tool, 1);
}

报错:Fatal error: multiple Lua VMs detected

**Comment by fdcumt** [comment]
![image](https://user-images.githubusercontent.com/10294860/58188461-33385780-7ceb-11e9-8d70-3affda4c979d.png)
这是我找到的解决方案, 但是我现在怎么把lua编成dll?  目前的lua是以lib的方式添加进来的. 我能不能以源码的方式加进来? 或者怎么把这个编成dll?

**Comment by fdcumt** [comment]
在window上, ue中的插件好像都编译成dll, 最终以链接的方式导进来, 但是在android和ios上, 我不知道他是否还是以动态库的方式加载的? 如果不是, 那么在ios或者android也存在这个问题.

**Comment by fdcumt** [comment]
在项目中遇到这个问题是, 我不想每次向lua中添加库都要改slua的插件, 这样到后期不好维护.
 我的目的是尽可能少的改动slua插件. 这样, 我通过暴露LuaStateInitCallback这个接口, 向lua中添加项目需要的接口, 像lua-protobuf, lua-cjson等模块. 但是现在一添加就遇到这个问题..........

**Comment by pangweiwei** [comment]
你的插件编译使用另外一个lua代码，你需要像luasocket一样修改代码，来使用外部模块，slua未来可能提供不标准虚拟机用以支持attribute，类型申明等特性，支持rpc这样的能力，例如：

@rpc(client,reliable)
function foo(value:int,name:string):string
end

目前这个能力已经在内部测试了。

**Comment by fdcumt** [comment]
参考luasocket, 我是这么改的: 并且提交了pr
就是手工建立一个table, 往里面塞函数. 其实luaL_requiref也是这么做的, 但是不知道手动写,会比luaL_requiref 效率差了多少

static int32 PrintLog(slua::lua_State *L)
{
	FString str;
	size_t len;
	const char* s = luaL_tolstring(L, 1, &len);
	if (s) str += UTF8_TO_TCHAR(s);
	slua::Log::Log("PrintLog %s", TCHAR_TO_UTF8(*str));
	return 0;
}

static int32 NewLuaLib(lua_State *L)
{
	luaL_Reg _LuaFuncs[] = {
		{"LuaNamePrintLog", PrintLog},
		{NULL, NULL}
	};
	lua_newtable(L);
	luaL_setfuncs(L, _LuaFuncs, 0);
	return 1;
}

void UMyGameInstance::LuaStateInitCallback()
{
	slua::lua_State *L = state.getLuaState();

	// 添加全局函数
	lua_pushcfunction(L, PrintLog);
	lua_setglobal(L, "PrintLog");

	// 以前是直接使用luaL_requiref, 现在要改成如下方式注册
	luaL_getsubtable(L, LUA_REGISTRYINDEX, LUA_PRELOAD_TABLE);
	lua_pushcfunction(L, NewLuaLib);
	lua_setfield(L, -2, "LuaNameTestNewLib");
	lua_pop(L, 1);
}

**Comment by pangweiwei** [comment]
你的pr是为了复现，你说的问题？

**Comment by fdcumt** [comment]
是为了,以后如果有人遇到类似的问题, demo中有解决的方法

**Comment by fdcumt** [comment]
这个pr是解决方法, demo可以正常运行的. 项目中我现在也是这么搞的, 但是不知道这个效率和luaL_newlib比差了多少. 并且android打包可以正常打包.

**Comment by pangweiwei** [comment]
luaL_newlib就等于你那2个函数，没差别。
