### ISSUE TITLE
在lua环境中给UClass的FVector成员赋值无效

### ISSUE THREAD

**Issue by ShrimpABC** [Tencent/sluaunreal#135]
例如，在C++中的UClass类里声明了如下变量：
UPROPERTY(EditAnywhere, BlueprintReadWrite)
FVector Test = FVector::ZeroVector;

尝试在lua环境中修改Test的值，如：
Test.Z = 100
随后检查Test值，发现Z并没有被修改

请问这是bug吗？

**Comment by pangweiwei** [comment]
这不是bug，struct你需要整体赋值，单独修改里面field，不会反映到c++中

**Comment by ShrimpABC** [comment]
好的，另外发现了两个编译问题，也在这里报给你吗？
