### ISSUE TITLE
发现两个编译问题

### ISSUE THREAD

**Issue by ShrimpABC** [Tencent/sluaunreal#136]
1. 编译slua_profile.cpp时会出现：
error C2653: “FEditorStyle”: 不是类或命名空间名称
在这个文件中加上#include "Editor/EditorStyle/Public/EditorStyle.h"后问题解决。

2. 修改LuaDelegate.cpp后触发重新build，会出现luaDelegate.h编译错误：
error C2988: 不可识别的模板声明/定义
error C2653: “LuaObject”: 不是类或命名空间名称
尝试将SluaUtil.h的
template<typename T, bool isUObject = std::is_base_of<UObject, T>::value>
	struct TypeName {
		static SimpleString value();
	};
和
struct SimpleString
拿出，单独放在一个新加的.h文件里，让SluaUtil.h和LuaDelegate.h都include这个文件。LuaDelegate.h还需要include LuaObject.h，完成上述操作后问题解决。

**Comment by pangweiwei** [comment]
你是那个版本的编译结果，最新的master上的版本，应该是ok的

**Comment by ShrimpABC** [comment]
周二的“fix #129“，给LuaDelegate.cpp里随便加个回车就可以重现

**Comment by ShrimpABC** [comment]
slua_profile.cpp也请记得修一下吧，重现方法是类似的，在slua_profile.cpp随便加点修改就会重现

**Comment by pangweiwei** [comment]
你说的 slua_profile.cpp 的问题，我没有发现，要不你更新到最新版试试？

**Comment by ShrimpABC** [comment]
用今天的最新版测了一下democpp，给slua_profile.cpp 加了个回车，还是会出“ error C2653: “FEditorStyle”: 不是类或命名空间名称”

**Comment by pangweiwei** [comment]
还是无法复现你提到的问题，不管是windows，mac，还是android，building都没有问题。
要不你提交一个pr吧，是否incluce "EditorStyle.h" 都无所谓。

**Comment by ShrimpABC** [comment]
好的，那我之后提一下pr，我和我的小伙伴都试了一下，确定是会报错的。
