### ISSUE TITLE
关于宏命名冲突

### ISSUE THREAD

**Issue by scriptkitz** [Tencent/sluaunreal#143]
llimits.h里定义的一些宏，比如MAX_SIZE等，虽然放在namespace里，但因为#define是全局作用的，会跟其他地方定义的变量名为MAX_SIZE的变量冲突导致编译错误，这种常用的名字很容易跟第三方的常量名冲突。。
我项目里用的第三方库有个变量static const int MAX_SIZE;，就提示冲突了。。
希望宏改下名字加个SLUA_前缀什么的。。

**Comment by pangweiwei** [comment]
那个代码是lua自带的代码，不方便修改。
你可以

#ifdef MAX_SIZE
#undef MAX_SIZE
#endif
