### ISSUE TITLE
Android编译报错

### ISSUE THREAD

**Issue by scriptkitz** [Tencent/sluaunreal#144]
LuaObject.h
		template<class T>
		static T checkValueOpt(lua_State* L, int p, const T& defaultValue=T()) {
			if (!typeMatched<T>(lua_type(L,p))) {
				return defaultValue;
                                          ^ error: returning address of local temporary object [-Werror, -Wrerun-stack-address]
			} else {
				return checkValue<T>(L, p);
			}
		}

**Comment by pangweiwei** [comment]
你的ndk太新了，只是返回一个nullptr而已。

建议r13-r16b都可以
