### ISSUE TITLE
sLua中使用TArray<UObject *>这种类型，GC会导致crush

### ISSUE THREAD

**Issue by cxzgb123** [Tencent/sluaunreal#145]
我在 C++中，定义了一个TArray<UObject *>的变量（UPROPERTY），在lua中遍历对象，在关卡结束后，gc会导致crush，是不是和这个变量的生命周期有关？是用这种类型的变量时，有没有生命需要注意的地方？wiki里没有例子，能写个么？谢谢~

**Comment by pangweiwei** [comment]
什么版本发自我的华为手机-------- 原始邮件 --------主题：[Tencent/sluaunreal] sLua中使用TArray这种类型，GC会导致crush (#145)发件人：robort 收件人：Tencent/sluaunreal 抄送：Subscribed 我在是用 C++中，定义了一个TArray<UObject *>的变量（UPROPERTY），在lua中遍历对象，在关卡结束后，gc会导致crush，是不是和这个变量的生命周期有关？是用这种类型的变量时，有没有生命需要注意的地方？wiki里没有例子，能写个么？谢谢~

**Comment by cxzgb123** [comment]
1.01之后的一个版本，git的提交版本号是 b4ed534102f13146715839c65490bf5372c02aa5

**Comment by pangweiwei** [comment]
请给出你的测试方法和重现步骤。

**Comment by cxzgb123** [comment]
定义了一个TArray<UObject *>的变量（UPROPERTY），在lua中遍历这个变量，然后切换场景的时候，就有几率会crush，堆栈截图如下
![image](https://user-images.githubusercontent.com/6659533/58774177-bd899100-85f2-11e9-9a46-07a97fbb35af.png)

**Comment by pangweiwei** [comment]
无法重现你的问题，建议你更新：

我只会脚本报错：

Slua: Error: ...y/Desktop/workspace/sluaunreal/Content/Lua/Map2Actor.lua:32: arg 1 had been freed(00000279D5286400), can't be used
stack traceback:
    [C]: in metamethod '__index'
    ...y/Desktop/workspace/sluaunreal/Content/Lua/Map2Actor.lua:32: in function 'callLastMapActorMethod'
    ...y/Desktop/workspace/sluaunreal/Content/Lua/Map2Actor.lua:28: in function <...y/Desktop/workspace/sluaunreal/Content/Lua/Map2Actor.lua:5>

**Comment by cxzgb123** [comment]
好的 非常感谢~
