### ISSUE TITLE
Lua中如何调用C++里带有标记UPROPERTY(BlueprintAssignable）的变量

### ISSUE THREAD

**Issue by kingkunkun** [Tencent/sluaunreal#147]
Lua中如何调用C++里带有标记 BlueprintAssignable的变量?如下
UPROPERTY(BlueprintAssignable, Category = "Components|Spine|Animation")
FSpineAnimationCompleteDelegate AnimationComplete; 

这种AnimationComplete只能在蓝图里调用，在Lua中也想使用有什么房方法吗？

**Comment by pangweiwei** [comment]
local handle = xxx.AnimationComplete:Add(function()end)
 xxx.AnimationComplete:Remove(handle)

**Comment by kingkunkun** [comment]
谢谢
