### ISSUE TITLE
C++（非蓝图）不支持out参数的函数么

### ISSUE THREAD

**Issue by AngeliaQing** [Tencent/sluaunreal#148]
非蓝图类，想要返回多个参数，使用了非const引用，编译报错
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	C2664	“RET (slua::lua_State *,void *,FString &&,LoadType &&,int &)”: 无法将参数 5 从“int”转换为“int &”	client	e:\h3d_mobile\ue4_lua\tests\ue4_lua\client\plugins\slua_unreal\source\slua_unreal\public\LuaCppBinding.h	181

**Comment by pangweiwei** [comment]
目前不支持，也没计划支持

**Comment by pangweiwei** [comment]
你可以考虑直接定义一个 static int some_function(lua_State* L)这样的lua方法，自己出来参数check和push，直接返回多个返回值
