### ISSUE TITLE
如何进行跨lua文件调用？

### ISSUE THREAD

**Issue by D3ZAX** [Tencent/sluaunreal#149]
假设有两个LuaActor ActorA和ActorB，分别绑定了两个lua脚本A.lua和B.lua，如果ActorA在蓝图中引用了ActorB，且在A.lua中需要频繁调用B.lua中的各种方法，有什么好方法吗？

目前看到例子中展示的是通过事件调用，但是感觉不太适合频繁的多方法调用......

**Comment by pangweiwei** [comment]
这是最基本的lua使用问题，你可以找本lua的书籍看看，不明白你的困惑在哪里

**Comment by D3ZAX** [comment]
额，我知道可以用lua栈来搞......也就是说这个要自己实现了......

我比较疑惑的是slua-unreal中为什么没有在LuaBase类中提供一个c++接口方便Lua脚本通过改接口获取其对应的lua表？这样的话LuaActor的易用性更强些，否则还是要自己实现一套LuaActor

**Comment by pangweiwei** [comment]
> 额，我知道可以用lua栈来搞......也就是说这个要自己实现了......

不需要呀，就是一个luastate，你直接xx.xxx不就访问到了？

> 我比较疑惑的是slua-unreal中为什么没有在LuaBase类中提供一个c++接口方便Lua脚本通过改接口获取其对应的lua表？这样的话LuaActor的易用性更强些，否则还是要自己实现一套LuaActor

LuaVar可以对应lua表，也提供了api操作它

**Comment by D3ZAX** [comment]
是这样，下面是个简单的例子：
---------------------------------------------------------------
LuaActorA蓝图：
![LuaActorA](https://user-images.githubusercontent.com/15343372/58936953-96be8c80-87a3-11e9-82dc-39ba3fd89f43.png)
---------------------------------------------------------------
LuaActorB蓝图：
![LuaActorB](https://user-images.githubusercontent.com/15343372/58936957-9aeaaa00-87a3-11e9-9ca2-e4dd776215c3.png)
----------------------------------------------------------------
A.lua：
local actorA = {}

local called = false

function actorA:ReceiveBeginPlay()
	self.bCanEverTick = true
    -- self.bCanBeDamaged = false
end

function actorA:Tick(dt)
	if not called then
		called = true
		-- 正常，为LuaActorB的引用
		print(self.LuaActorB)
		-- 无法获取lua中定义的方法LogB，返回nil
		print(self.LuaActorB.LogB)
		-- 无法获取lua中定义的属性b，返回nil
		print(self.LuaActorB.b)
		-- 正常调用，通过c++接口调用lua方法
		self.LuaActorB:CallLuaMember("LogB", nil)
		-- 无法调用，报错
		self.LuaActorB:LogB()
	end
end

function actorA:ReveiveEndPlay()
end

return actorA
--------------------------------------------------------------------
B.lua:
local actorB = {
	b = "1111"
}

function actorB:LogB()
	print("LogB from LuaActorB")
	print(self.b)
end

function actorB:ReceiveBeginPlay()
	-- self.bCanEverTick = true
    -- self.bCanBeDamaged = false
end

function actorB:Tick(dt)
end

function actorB:ReveiveEndPlay()
end

return actorB
-------------------------------------------------------------


问题就是目前的LuaActor调用Lua脚本时在A.lua中无法直接获得B.lua中的属性b或是方法LogB，调用方法必须通过CallLuaMember接口。

我注意到LuaBase类中有个属性luaSelfTable存下了对应的lua table，但是没发现有接口从lua脚本中获取到，只能自己实现，这里是我漏掉了什么吗？

如果LuaBase类中有对应的接口能在lua脚本中调用直接拿到luaSelfTable这个lua table，会方便很多......

**Comment by pangweiwei** [comment]
明白你的问题了，我思考下

**Comment by pangweiwei** [comment]
我增加了__luaPart属性，访问LuaActor对应的lua table，不过我想后续接续优化可以不用__luaPart，直接通过ud.xxx来访问LuaPart的数据，不过这样做可能index查找不到的时候，非常浪费。
我再评估一下。

**Comment by D3ZAX** [comment]
好的，谢谢

**Comment by D3ZAX** [comment]
额，更新后lua wrapper工具生成的代码编译会报错，能否把luawrapper也更新下？ 谢谢！

**Comment by fdcumt** [comment]
@pangweiwei 这个问题就是#118 
如果你增加获取lua table的接口, 然后通过再对其进行操作, 这种方式会特别不方便, 尤其是操作widget的时候.
一种解决思路在问题#118中也提出了, 这种解决方法是把c++和lua table 统一起来使用, 对使用者来说是透明的.

关键点在这:
![image](https://user-images.githubusercontent.com/10294860/59171307-00101800-8b75-11e9-9a8e-050273d81c07.png)

注意, 为了节省搜寻的效率, 在lua中使用变量的时候, 要在lua class的构造函数ctor中对变量进行定义.

**Comment by pangweiwei** [comment]
嗯，直接push table也许是个好做法。

**Comment by pangweiwei** [comment]
Duplicate of #118
