### ISSUE TITLE
是否考虑提供一个ALuaActorComponent，有时候需要自己扩展Component。

### ISSUE THREAD

**Issue by scriptkitz** [Tencent/sluaunreal#151]
ALuaController
ALuaPlayerController
ALuaGameModeBase
这些都有了，希望提供一个ALuaActorComponent,自定义Componet时候用。

**Comment by pangweiwei** [comment]
你可以依葫芦画瓢做一个，目前没有提供支持，如果你支持了，可以提交pr。

**Comment by scriptkitz** [comment]
提交了 #156
