### ISSUE TITLE
Luad调用C++接口，调用链中调用NetMulticast的接口，不会调用到客户端上

### ISSUE THREAD

**Issue by cxzgb123** [Tencent/sluaunreal#154]
如题，在Luad调用C++接口，调用链中调用NetMulticast的接口，这个接口就只会在服务器上调用，不能调用到客户端上，我用了timer延迟了1秒调用这个NetMulticast的接口，就可以正常进行RPC调用了。

**Comment by pangweiwei** [comment]
目前还没有考虑rpc的支持，整个rpc的支持会在后续版本中完善，你可以参考一下#77，#78的feature描述，未来我们希望做到的目标。

**Comment by cxzgb123** [comment]
我不是在lua直接调用RPC，是调用了一个C++接口，这个C++接口调用了一个NetMulticast的RPC，这种情况下，出现了问题

**Comment by pangweiwei** [comment]
fix了
