### ISSUE TITLE
请教有关LuaArray的问题

### ISSUE THREAD

**Issue by ShrimpABC** [Tencent/sluaunreal#155]
我使用slua.Array(EPropertyClass.Int)在lua端创建了一个array，随后调用C++反射出的函数，该函数接收一个TArray的引用作为参数，在函数内会给这个array新增一个元素。调试发现，调用这个函数后，在lua端查看array的num，发现和调用c++函数前一样。

也就是说，如果想在C++函数里修改lua创建的array，应该怎样做呢？
![捕获2](https://user-images.githubusercontent.com/22850285/59668932-ee211b80-91eb-11e9-8f50-e23690fc2efc.JPG)
![捕获](https://user-images.githubusercontent.com/22850285/59668957-fa0cdd80-91eb-11e9-90a9-71618e2c9716.JPG)

**Comment by pangweiwei** [comment]
修改后的arr，会变成返回值

local arr = uactor:AddElement(arr)

**Comment by ShrimpABC** [comment]
OK，谢谢~
