### ISSUE TITLE
现在slua不支持unpack函数调用吗？

### ISSUE THREAD

**Issue by yelei8363** [Tencent/sluaunreal#159]
function YeTest(...)
	print("YeTest")
	local a = unpack(...)
end

YeTest()
这样的语句，会报unpack是空，我看slua底层代码是导出unpack，为什么我无法使用，是我那里用错了吗？

**Comment by pangweiwei** [comment]
slua使用的是lua5.3，unpack被使用到了table.unpack

**Comment by yelei8363** [comment]
好的，原来是lua5.3改了，谢谢
