### ISSUE TITLE
slua lua/luaconf_h 无法修改 extend c

### ISSUE THREAD

**Issue by nashnie** [Tencent/sluaunreal#16]
嗨你好，
我想修改lua目录下luaconf_h,如下
#define LUA_API extern "C" __declspec(dllexport)
导出.c的形式。
但是无法编译，请问该如何处理呢？
我的根本目的是想使用luastudio 断点调试 slua。

**Comment by pangweiwei** [comment]
sluauneal的api都已经包装在slua namespace下了，没有对外导出纯c的函数接口。

**Comment by pangweiwei** [comment]
这么做的目的是有些ue游戏自己也可能有lua方案，避免冲突。
