### ISSUE TITLE
slua 纯c++版本有链接地址么

### ISSUE THREAD

**Issue by AngeliaQing** [Tencent/sluaunreal#160]
请问slua 纯c++版本有链接地址么？

**Comment by pangweiwei** [comment]
什么是纯c++版本？

**Comment by AngeliaQing** [comment]
就是可以接c++服务器的slua版本，跟引擎没有关系的

**Comment by pangweiwei** [comment]
这部分没有提供，你可以使用任何传统c++ luabinding技术；虽然slua提供了的c++ binding能力，但slua更多的是解决和ue本身对象生命周期管理，类型转换，扩展UObject等能力。

**Comment by pangweiwei** [comment]
另外，我们内部有项目确实删除了ue的支持，只保留了c++部分能力，但这部分不是官方支持。
