### ISSUE TITLE
为什么有些标记了UCLASS和UFUNCTION的类，无法在slua中调用

### ISSUE THREAD

**Issue by yelei8363** [Tencent/sluaunreal#162]
有些标记了UCLASS和UFUNCTION的类，无法在slua中调用。比如UGameplayStatics、UBTFunctionLibrary等，

附加lua测试代码和报错：
lua:
print(UGameplayStatics.GetAllActorsOfClass)

报错:
Slua: Error: D:/UE4Work/UE422_AITree/Content//Lua/AI/AgroCheck.lua:10: attempt to index a nil value (global 'UGameplayStatics')

不知道是否是我理解有问题

**Comment by pangweiwei** [comment]
需要先import发自我的华为手机-------- 原始邮件 --------主题：[Tencent/sluaunreal] 为什么有些标记了UCLASS和UFUNCTION的类，无法在slua中调用 (#162)发件人：yelei8363 收件人：Tencent/sluaunreal 抄送：Subscribed 有些标记了UCLASS和UFUNCTION的类，无法在slua中调用。比如UGameplayStatics、UBTFunctionLibrary等，

附加lua测试代码和报错：

lua:

print(UGameplayStatics.GetAllActorsOfClass)

报错:

Slua: Error: D:/UE4Work/UE422_AITree/Content//Lua/AI/AgroCheck.lua:10: attempt to index a nil value (global 'UGameplayStatics')

不知道是否是我理解有问题
