### ISSUE TITLE
ue4多线程多个lua虚拟机Exception throw slua::lua_longjmp at memory location xxxx

### ISSUE THREAD

**Issue by dengzibiao** [Tencent/sluaunreal#163]
我修改了ue4开多个窗口代码，创建两个独立的窗口，创建了两个不同的World、GameInstance、GameMode等，lua init在GameInstance中，两个GameMode的tick调用lua update，每次Update都会抛出Exception throw slua::lua_longjmp at memory location xxxx

**Comment by pangweiwei** [comment]
Exception throw slua::lua_longjmp at memory location 这个报错是lua异常处理，lua异常处理使用try catch来处理异常跳转，出现这个报错，说明某些lua代码发生了异常，你只要修复lua代码错误就行了。

**Comment by dengzibiao** [comment]
我只开一个ue4窗口启动一个lua虚拟机就不会报错，启动两个后会有异常而且lua里面会有崩溃，怀疑是创建虚拟机中的静态变量和函数导致的------------------ 原始邮件 ------------------
发件人: "siney"<notifications@github.com>
发送时间: 2019年6月28日(星期五) 中午1:53
收件人: "Tencent/sluaunreal"<sluaunreal@noreply.github.com>;
抄送: "dengzibiao"<251275671@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [Tencent/sluaunreal] ue4多线程多个lua虚拟机Exception throw slua::lua_longjmp at memory location xxxx (#163)



Exception throw slua::lua_longjmp at memory location 这个报错是lua异常处理，lua异常处理使用try catch来处理异常跳转，出现这个报错，说明某些lua代码发生了异常，你只要修复lua代码错误就行了。
 
&mdash;

**Comment by pangweiwei** [comment]
你可以把你的代码提交到github fork，我看看。



发自我的 iPad

**Comment by dengzibiao** [comment]
只要把LuaBase.h文件里面的LuaVar metaTable改成非静态就能达到我的要求
