### ISSUE TITLE
使用CppBinding绑定结构体函数报错

### ISSUE THREAD

**Issue by NickCarter1990** [Tencent/sluaunreal#166]
我定义了如下结构体，并使用CppBinding的方法绑定。但是编译后报错，貌似是无法识别GetTest返回的Test结构体类型，请问大神这个该怎么处理？需要使用wrapper工具吗？

struct Test
{
public:
     Test(int v) { i = v; }
     Test GetTest()
     { 
          return Test(0);
     }
     int i;
}

DefLuaClass(Test)
DefLuaMethod(GetTest, &Test::GetTest)
EndDef(Test, nullptr)

**Comment by pangweiwei** [comment]
cppbinding仅支持返回指针，或者LuaOwnedPtr。

发自我的 iPad
