### ISSUE TITLE
LuaMap在IOS上崩溃

### ISSUE THREAD

**Issue by zengdelang** [Tencent/sluaunreal#169]
目前发现LuaMap在IOS上有崩溃，使用方法是在蓝图中声明的TMap变量，在Lua中读取这个变量的配置，发现LuaMap在GC时会崩溃，这个问题新版的slua有发现并解决吗？目前我这边的版本应该有一个月没有升级了
![image](https://user-images.githubusercontent.com/4466062/61055989-31eef580-a425-11e9-9dc7-fc4f01620277.png)
![image](https://user-images.githubusercontent.com/4466062/61056001-387d6d00-a425-11e9-9b2f-2a37f5469a67.png)
![image](https://user-images.githubusercontent.com/4466062/61056021-416e3e80-a425-11e9-872a-e9fb9011d9b7.png)
![image](https://user-images.githubusercontent.com/4466062/61056035-48954c80-a425-11e9-9960-e632d65ed564.png)
![image](https://user-images.githubusercontent.com/4466062/61056093-55b23b80-a425-11e9-96d1-7bad0658f4b8.png)

**Comment by zengdelang** [comment]
unreal 版本是4.22

**Comment by pangweiwei** [comment]
你可以看看代码的差异，有一些修改，不知道你的版本是否是最新的。

**Comment by zengdelang** [comment]
升级到最新还是有崩溃，有没有可能是使用的问题，其他普通的TMap<uint8,uint8>这种好像没有报过错误，现在的TMap是在蓝图中声明的一个变量，类似于TMap<uint8, BpStruct>, BpStruct是我用蓝图声明的一个结构体，结构类似如下，里面又是一个TMap
struct BpStruct
{
     TMap<uint8, FSoftObjectPath> Config
}

**Comment by zengdelang** [comment]
在Lua中也仅仅是通过下面的方式去读取配置
local eventInfo = self.Events:Get(displayMode)
    if eventInfo then
        for k, v in pairs(eventInfo.EventConfig) do
        end
    end

**Comment by pangweiwei** [comment]
BpStruct的完整定义是怎么样子的，就是你列出来那样？

**Comment by zengdelang** [comment]
BpStruct基本跟我列出来的一样，是用蓝图定义的一个结构体，key一个枚举类型， value是softObjectPath

**Comment by zengdelang** [comment]
另一种怀疑是，我使用了多个组件，这几个组件都有一个TMap的蓝图变量，都是命名成Events，但是对应的BpStruct是两个不同的结构体，BpStruct的定义基本相同，今天我尝试使用完LuaMap后立即Clear，发现编辑器也崩溃，而且崩溃概率反而增大了，有没有可能是蓝图变量名命名成一样的，导致查找或者释放的时候找错了

**Comment by pangweiwei** [comment]
我自行测试没有发现你说的crash

有如下定义：


USTRUCT(BlueprintType)
struct FBpStruct {
	GENERATED_BODY()
public:
	UPROPERTY(BlueprintReadWrite)
	TMap<uint8, FSoftObjectPath> Config;
};

同时存在如下属性：

UPROPERTY(BlueprintReadWrite)
	TMap<uint8, FBpStruct> structMap;


初始化时填充数据：

FBpStruct bpStruct;
	bpStruct.Config.Add(0, FSoftObjectPath(TEXT("WidgetBlueprint'/Game/LuaPanel.LuaPanel'")));
	structMap.Add(0, bpStruct);

在lua里使用：

for k,v in pairs(t.structMap) do
        print(k,v)
        for k,v in pairs(v.Config) do
            print(k,v)
        end
    end
    t.structMap:Clear()

你看你能够提供完整测试用例。

**Comment by zengdelang** [comment]
这个是有概率发生的，不是必现，而且FBpStruct我不是用C++声明的，而是在编辑器中建的蓝图结构体，TMap的数据也是配置在蓝图上的

**Comment by pangweiwei** [comment]
如果是蓝图的数据 LuaMap不应该clear之后清理数据的，数据的生命周期有蓝图自己管理，从你的调用栈看luamap试图destroy数据了，这是不正常的

**Comment by zengdelang** [comment]
现在是这样的，原先我是没有clear蓝图的TMap变量的，后来我尝试clear后，崩溃率就会提高，我只是单纯的读取配置，比如这样,  Anims是一个TMap变量，  AnimsConfig是一个蓝图结构体，AnimsConfig.Config是蓝图结构体内部的TMap变量
    local AnimsConfig = self.Anims:Get(displayMode)
    if AnimsConfig then
        for k, v in pairs(AnimsConfig .Config) do
              ...
        end
    end

   -- 加了这行似乎崩溃率提高
    self.Anims:Clear()

**Comment by zengdelang** [comment]
上面的代码就是初始化的时候访问下，其他就没有地方访问了

**Comment by pangweiwei** [comment]
tmap在gc的时候也会clear，如果是tmap管理的数据，所以概率低一些。
