### ISSUE TITLE
LuaDelegate::gc使用时没有Remove的会导致泄漏内存

### ISSUE THREAD

**Issue by tary** [Tencent/sluaunreal#17]
https://github.com/Tencent/sluaunreal/blob/e29016f60bb16b4aabacdd9a03511f1abf93c215/Plugins/slua_unreal/Source/slua_unreal/Private/LuaDelegate.cpp#L113-L116

这里是不是应该加个 LuaDelegate::Clear(L);回收掉没主动Remove的回调
```c++
    int LuaDelegate::gc(lua_State* L) {
    LuaDelegate::Clear(L); 
    CheckUD(LuaDelegateWrap,L,1); 
    delete UD; 
    return 0;  
```

**Comment by pangweiwei** [comment]
slua的设计需要你保证add和remove配对，否则会导致内存泄漏

**Comment by pangweiwei** [comment]
如果你在gc的时候，做了remove，可能导致一些event本来想收到，结果收不到了。

**Comment by pangweiwei** [comment]
你可以考虑如下写法：

local x= btn:AddListener(function() end)
如果x自动被gc后，remove的delegate，就感觉怪怪的
除非你这么写：
x= btn:AddListener(function() end)

但这样 event的remove依赖x的回收，有时需要即时控制。
