### ISSUE TITLE
蓝图类使用 CppBinding的问题

### ISSUE THREAD

**Issue by hbqzq** [Tencent/sluaunreal#171]
你好
考虑到蓝图函数的调用和CppBinding仍然存在效率差距，而且在项目规模较大的时候调用频率也会较高，这部分性能差距就会比较明显，所以有没有可能由使用者决定某些类型的某些方法是由CppBinding导出？slua_unreal在设计时是否考虑了此类需求？
目前如果我使用DefLuaClass 导出UCLASS时，会报编译错误：
error C2338: UObject class shouldn't use LuaCppBinding. Use REG_EXTENSION instead.
这个意思是不是推荐使用REG_EXTENSION方式重新注册函数或属性？

**Comment by hbqzq** [comment]
查看了源码，看来并不是，externsion method比UClass查询的时间靠后。。
有没有可能让用户根据情况选择静态代码的方式调用蓝图类型方法？

**Comment by pangweiwei** [comment]
UObject的方法扩展，只能使用externsion method，非UObject的绑定使用cppbinding。
如果你想修改查找顺序可以自行修改源代码。

**Comment by pangweiwei** [comment]
> 有没有可能让用户根据情况选择静态代码的方式调用蓝图类型方法？

externsion method 也是静态的方法，没有效率损失，只是他的查找靠后
