### ISSUE TITLE
C++调用Lua函数，参数传递问题

### ISSUE THREAD

**Issue by wangyhbupt** [Tencent/sluaunreal#172]
我在一个派生自slua_Luabase的类里面，想调用Lua中的函数，代码如下：
bool ULuaCameraModifier::ModifyCamera(float DeltaTime, struct FMinimalViewInfo& InOutPOV)
{
	m_modify_camera_lua_function = luaSelfTable.getFromTable<slua::LuaVar>("ModifyCamera", true);
	m_modify_camera_lua_function.call(luaSelfTable, DeltaTime, InOutPOV);
	return false;
}

编译报错：
1>LuaCameraModifier.cpp (0:07.92 at +0:00)
1>g:\unrealproject\mmo\plugins\slua_unreal\source\slua_unreal\public\LuaVar.h(306): error C2665: “slua::LuaObject::push”: 25 个重载中没有一个可以转换所有参数类型
1>g:\unrealproject\mmo\plugins\slua_unreal\source\slua_unreal\public\LuaObject.h(507): note: 可能是“int slua::LuaObject::push(slua::lua_State *,const slua::LuaLString &)”
1>g:\unrealproject\mmo\plugins\slua_unreal\source\slua_unreal\public\LuaObject.h(504): note: 或    “int slua::LuaObject::push(slua::lua_State *,UFunction *,UClass *)”
1>g:\unrealproject\mmo\plugins\slua_unreal\source\slua_unreal\public\LuaObject.h(503): note: 或    “int slua::LuaObject::push(slua::lua_State *,const slua::LuaVar &)”
1>g:\unrealproject\mmo\plugins\slua_unreal\source\slua_unreal\public\LuaObject.h(502): note: 或    “int slua::LuaObject::push(slua::lua_State *,const char *)”
1>g:\unrealproject\mmo\plugins\slua_unreal\source\slua_unreal\public\LuaObject.h(501): note: 或    “int slua::LuaObject::push(slua::lua_State *,const FName &)”
1>g:\unrealproject\mmo\plugins\slua_unreal\source\slua_unreal\public\LuaObject.h(500): note: 或    “int slua::LuaObject::push(slua::lua_State *,const FString &)”
1>g:\unrealproject\mmo\plugins\slua_unreal\source\slua_unreal\public\LuaObject.h(499): note: 或    “int slua::LuaObject::push(slua::lua_State *,const FText &)”
1>g:\unrealproject\mmo\plugins\slua_unreal\source\slua_unreal\public\LuaObject.h(498): note: 或    “int slua::LuaObject::push(slua::lua_State *,void *)”
1>g:\unrealproject\mmo\plugins\slua_unreal\source\slua_unreal\public\LuaObject.h(497): note: 或    “int slua::LuaObject::push(slua::lua_State *,uint32)”
1>g:\unrealproject\mmo\plugins\slua_unreal\source\slua_unreal\public\LuaObject.h(496): note: 或    “int slua::LuaObject::push(slua::lua_State *,bool)”
1>g:\unrealproject\mmo\plugins\slua_unreal\source\slua_unreal\public\LuaObject.h(495): note: 或    “int slua::LuaObject::push(slua::lua_State *,int)”
1>g:\unrealproject\mmo\plugins\slua_unreal\source\slua_unreal\public\LuaObject.h(494): note: 或    “int slua::LuaObject::push(slua::lua_State *,float)”
1>g:\unrealproject\mmo\plugins\slua_unreal\source\slua_unreal\public\LuaObject.h(493): note: 或    “int slua::LuaObject::push(slua::lua_State *,uint16)”
1>g:\unrealproject\mmo\plugins\slua_unreal\source\slua_unreal\public\LuaObject.h(492): note: 或    “int slua::LuaObject::push(slua::lua_State *,int16)”
1>g:\unrealproject\mmo\plugins\slua_unreal\source\slua_unreal\public\LuaObject.h(491): note: 或    “int slua::LuaObject::push(slua::lua_State *,uint8)”
1>g:\unrealproject\mmo\plugins\slua_unreal\source\slua_unreal\public\LuaObject.h(490): note: 或    “int slua::LuaObject::push(slua::lua_State *,int8)”
1>g:\unrealproject\mmo\plugins\slua_unreal\source\slua_unreal\public\LuaObject.h(489): note: 或    “int slua::LuaObject::push(slua::lua_State *,uint64)”
1>g:\unrealproject\mmo\plugins\slua_unreal\source\slua_unreal\public\LuaObject.h(488): note: 或    “int slua::LuaObject::push(slua::lua_State *,int64)”
1>g:\unrealproject\mmo\plugins\slua_unreal\source\slua_unreal\public\LuaObject.h(487): note: 或    “int slua::LuaObject::push(slua::lua_State *,double)”
1>g:\unrealproject\mmo\plugins\slua_unreal\source\slua_unreal\public\LuaObject.h(486): note: 或    “int slua::LuaObject::push(slua::lua_State *,slua::LuaStruct *)”
1>g:\unrealproject\mmo\plugins\slua_unreal\source\slua_unreal\public\LuaObject.h(485): note: 或    “int slua::LuaObject::push(slua::lua_State *,FScriptDelegate *)”
1>g:\unrealproject\mmo\plugins\slua_unreal\source\slua_unreal\public\LuaObject.h(482): note: 或    “int slua::LuaObject::push(slua::lua_State *,const UObject *)”
1>g:\unrealproject\mmo\plugins\slua_unreal\source\slua_unreal\public\LuaObject.h(481): note: 或    “int slua::LuaObject::push(slua::lua_State *,UObject *)”
1>g:\unrealproject\mmo\plugins\slua_unreal\source\slua_unreal\public\LuaVar.h(306): note: 尝试匹配参数列表“(slua::lua_State *, F)”时
1>        with
1>        [
1>            F=FMinimalViewInfo
1>        ]
1>g:\unrealproject\mmo\plugins\slua_unreal\source\slua_unreal\public\LuaVar.h(307): note: 参见对正在编译的函数 模板 实例化“int slua::LuaVar::pushArg<FMinimalViewInfo,>(F) const”的引用

这个FMinimalViewInfo 我已经通过LuaWrapper导出了，并且在Lua中也能正常使用，这里需要怎么处理一下呢？

**Comment by pangweiwei** [comment]
使用指针 & InOutPOV
