### ISSUE TITLE
BUG: loadUI加载LuaUserWidget有错误。

### ISSUE THREAD

**Issue by c506928109** [Tencent/sluaunreal#176]
通过loadUI加载一个LuaUserWidget，会提示Can‘t get a valid lua self table, push nil instead.

调试发现是在loadUI中并没有执行NativeStruct函数，导致luaSelfTable为空，尝试调用TakeWidget()，但在push时还是会报上面那个提示，断点查看在TakeWidget时，luaSelfTable是有值，但在push时已经被销毁，在push前已经调用过了NativeDestruct()，不确定是否是因为没有引用触发GC导致，堆栈信息中，被隐藏了。(不确定是不是触发的LUA的GC，因为刚创建出来就被GC应该不是走的UE的GC流程。)

目前我是在loadUI中加加入第三个参数Parent，创建出来的widget直接通过Parent AddChild保持引用和构建。Parent为空，AddToViewport()。

上述加TakeWidget的时机就在push上加了if(widget) widget->TakeWidget(); 

谢谢提供slua这样方便的工具。

**Comment by pangweiwei** [comment]
这个问题，在新版本已经修复了，之前也有人提到了，你可以更新。
