### ISSUE TITLE
针对具备继承关系的几个luaActor，如何对每个蓝图都绑定一个Lua脚本？

### ISSUE THREAD

**Issue by CherryBone** [Tencent/sluaunreal#177]
由于UE4蓝图具备可以非常方便使用的继承功能，因此项目内会经常将通用方法抽象至父蓝图中，那么，假如有这么几个LuaActor，LuaActor3继承自LuaActor2，LuaActor2继承自LuaActor1，若我为LuaActor2绑定一个脚本，并且为LuaActor3也绑定了一个脚本，此时LuaActor3的脚本会覆盖LuaActor2的，以至于Lua脚本的结构与蓝图结构不一致。所以想问下是否有途径可以让没个蓝图都绑定一个Lua脚本？
或者需要在Lua脚本上动手脚，使Lua实现继承，形成蓝图与Lua分别继承各自的父节点？

**Comment by pangweiwei** [comment]
这个功能技术上肯定没有问题，能实现，只是这样做了以后，可能造成隐形的效率开销，导致代码架构行效率问题，我建议你不要这么思考问题。

**Comment by CherryBone** [comment]
好的，了解了，谢谢
