### ISSUE TITLE
3D widget（EWidgetSpace=World） lua无法加载

### ISSUE THREAD

**Issue by Piscis-QJ** [Tencent/sluaunreal#182]
继#173修复后。
lua table在NativeOnInitialized加载。
但是如果是一个WidgetComponent里的userwidget，在世界渲染模式。在生成userwidget的时候，因为userwidget的PlayerContext为空，导致NativeOnInitialized不会被调用。
目前解决方案是在NativeConstruct里检测luatable是否被创建。

**Comment by pangweiwei** [comment]
你是构建动态一个Actor里有WidgetComponent？然后怎么拿到这个widget？

**Comment by Piscis-QJ** [comment]
Actor动态创建WidgetComponent，同时创建UserWidget，然后WidgetComponent调用SetWidget，将之前创建的UserWidget传入。以上都是在蓝图里运行的。

**Comment by pangweiwei** [comment]
你的问题我无法重现

···c++
void ULuaUserWidget::NativeOnInitialized()
{
	Super::NativeOnInitialized();
	if (!init(this, "LuaUserWidget", LuaStateName, LuaFilePath)) return;
}

void ULuaUserWidget::NativeConstruct()
{

	if (!getSelfTable().isValid() && !init(this, "LuaUserWidget", LuaStateName, LuaFilePath)) return;
	Super::NativeConstruct();
#if (ENGINE_MINOR_VERSION==18)
	bCanEverTick = postInit("bHasScriptImplementedTick", false);
#else
	bHasScriptImplementedTick = postInit("bHasScriptImplementedTick", false);
#endif
}
```

你的修复方案是类似上面的代码吗？

**Comment by Piscis-QJ** [comment]
是的。

**Comment by Piscis-QJ** [comment]
`void ULuaUserWidget::NativeConstruct()
{
	if (LuaFilePath != "" && !luaSelfTable.isValid())
	{
		init(this, "LuaUserWidget", LuaStateName, LuaFilePath);
	}
	Super::NativeConstruct();
	if (LuaFilePath != "")
	{
#if (ENGINE_MINOR_VERSION==18)
		bCanEverTick = postInit("bHasScriptImplementedTick", false);
#else
		bHasScriptImplementedTick = postInit("bHasScriptImplementedTick", false);
#endif
	}
}`
判断LuaFilePath为空，只是因为当前没用到lua，但后续可能会有。

**Comment by pangweiwei** [comment]
好的，感谢，我就按照你的fix方案提交
