### ISSUE TITLE
导出Http模块的问题

### ISSUE THREAD

**Issue by yanjia2304** [Tencent/sluaunreal#184]
![image](https://user-images.githubusercontent.com/11566445/63667432-4422c880-c806-11e9-8cc2-49c0b91080fa.png)

 导出红框内函数编译的时候会报错。
ue4 : 4.22.3
vs 2017

error LNK2019: unresolved external symbol "public: static int __cdecl slua::LuaObject::push<void,class TSharedPtr<class IHttpRequest,0>,int,int>(struct slua::lua_State *,class TBaseDelegate<void,class TSharedPtr<class IHttpRequest,0>,int,int> &)" (??$push@XV?$TSharedPtr@VIHttpRequest@@$0A@@@HH@LuaObject@slua@@SAHPEAUlua_State@1@AEAV?$TBaseDelegate@XV?$TSharedPtr@VIHttpRequest@@$0A@@@HH@@@Z) referenced in function "public: static int __cdecl slua::LuaCppBinding<class TBaseDelegate<void,class TSharedPtr<class IHttpRequest,0>,int,int> & (__cdecl IHttpRequest::*)(void),{[thunk]: __cdecl IHttpRequest::`vcall'{152,{flat}}' }',0},1>::LuaCFunction(struct slua::lua_State *)" (?LuaCFunction@?$LuaCppBinding@P8IHttpRequest@@EAAAEAV?$TBaseDelegate@XV?$TSharedPtr@VIHttpRequest@@$0A@@@HH@@XZ$H??_91@$BJI@AAA@$00@slua@@SAHPEAUlua_State@2@@Z)

请教是什么问题？

**Comment by pangweiwei** [comment]
你是不是在另外一个dll导出 http 模块？
即不在游戏所在的工程导出 http 模块？
