### ISSUE TITLE
lua弱引用表引用Actor时，即使Actor没被销毁，引用也会自动丢失

### ISSUE THREAD

**Issue by D3ZAX** [Tencent/sluaunreal#189]
演示示例：

----------------------------------------------------------------------------
场景Actor设置：
![image](https://user-images.githubusercontent.com/15343372/64328660-71d6f100-d000-11e9-83b4-176bc838a826.png)

-----------------------------------------------------------------------------
LuaActor.lua： 
local actor={}

function actor:ReceiveBeginPlay()
	self.bCanEverTick = true
	self.bCanBeDamaged = false

	self.weakref = setmetatable({}, {__mode="v"})
	self.weakref.actor = self.actor

	print("actor:ReceiveBeginPlay")
	print(self.actor)
	print(self.weakref.actor)
end

function actor:ReceiveEndPlay(reason)
	print("actor:ReceiveEndPlay")
end

function actor:Tick(dt)
	print("actor:Tick")
	print(self.actor)
	print(self.weakref.actor)
end

return actor

----------------------------------------------------------------------
结果日志：
![image](https://user-images.githubusercontent.com/15343372/64328880-d4c88800-d000-11e9-968c-63425fcca736.png)

**Comment by pangweiwei** [comment]
这个是符合设计的。

self.actor 等价于 self.getProperty("actor")，他返回的的UserData，自己并不会持有

当 返回的UserData被销毁后，weakref的value也被清理了。

**Comment by D3ZAX** [comment]
感谢解答！！！
