### ISSUE TITLE
LuaUserWidget使用问题

### ISSUE THREAD

**Issue by unicodecndddd** [Tencent/sluaunreal#190]
我们项目使用LuaUserWidget绑定Lua的方式进行开发。
目前LuaUserWidget在移除界面的时候会移除lua的绑定。
如果把数据都写在lua中的话，这个时候会丢失数据。
一般情况是没有问题的，但是我们的项目中有的界面被移出viewport后会缓存一段时间等下次再使用。这就造成了lua丢失。
尝试把解绑操作移动到LuaUserWidget销毁时，结果是无法自动销毁，似乎是luaUserWidget和绑定的lua会相互引用对方。
当然，这只是我们项目自身的问题，但还是想问一下slua是否会考虑把lua的解绑操作延后到userWidget销毁的时候？

**Comment by pangweiwei** [comment]
目前并不会在RemoveFromView的时候，解除lua绑定，而是在NativeDestruct才解除绑定。

```c++
void ULuaUserWidget::NativeDestruct() {
	Super::NativeDestruct();
	luaSelfTable.free();
}
```

**Comment by unicodecndddd** [comment]
我是调用的UUserWidget::RemoveFromViewport将userwidget移除界面。

**Comment by unicodecndddd** [comment]
然后SObjectWidget因为失去引用会被析构，同时调用对应的userwidget的NativeDestruct

**Comment by pangweiwei** [comment]
你可以考虑，在lua里引用住返回的userwidget，就不会被析构了。

**Comment by unicodecndddd** [comment]
谢谢解答。
其实我的问题就出在寻找一个合适的销毁时机。
我能想到的时间点只有两个：
第一个是RemoveFromViewport时；
第二个是LuaUserWidget失去引用后被Unreal销毁时。

前者因为上面所说的原因无法使用。后者又因为现在LuaUserWidget持有LuaVar，注册表会引用lua部分，而lua又引用了LuaUserWidget在lua中的ud，这就造成了循环引用。

解决方法暂时想到两种：
第一个是通过ui管理系统在确认界面已经退出时，遍历界面中的元素找出继承自LuaBase的类主动调用销毁；
第二个是将LuaUserWidget与lua之间的绑定换成弱引用，让两者的引用只有对方时能够被销毁。
因为不希望ui系统与slua耦合，我目前在尝试第二种方法。但实际写下来发现很难找到这样一个弱引用的结构。目前将LuaUserWidget在lua中的ud与对应的table在注册表中建立两张弱键表相互引用，勉强能实现两者都没引用时销毁。但是当table在lua中没有引用，LuaUserWidget在c++被引用，还是会销毁。

**Comment by pangweiwei** [comment]
你还可以考虑过把数据和ui分开的方案
ui 释放了，数据还可以保存着，ui重建了，把数据再绑定起来。
