### ISSUE TITLE
如何生成 IntelliSense  symbols，用于代码提示

### ISSUE THREAD

**Issue by tsyw1987** [Tencent/sluaunreal#192]
我自己通过ue4 class 反射能导出一部分提示信息吗？

**Comment by pangweiwei** [comment]
目前slua没有默认导出这部分信息，如果你自己导出了这部分信息是可以使用的，luapanda支持这部分信息用于提示信息。
我们目前正在考虑自动基于代码分析的IntelliSense symbols支持，不用导出静态的信息。

**Comment by stuartwang** [comment]
可以试下 luapanda 的 IntelliSense 功能
项目地址 https://github.com/Tencent/LuaPanda
文档 https://github.com/Tencent/LuaPanda/blob/master/Docs/Manual/lua-intellisense.md
如有疑问可以用issues给我们留言
