### ISSUE TITLE
IOS 打包问题

### ISSUE THREAD

**Issue by yanjia2304** [Tencent/sluaunreal#198]
![image](https://user-images.githubusercontent.com/11566445/64601609-d2df3a00-d3ef-11e9-87c0-5159e4bacd75.png)

请教大佬：
IOS打包总是会报错说 'lua/lua.hpp' file not found
Android打包没问题。

ue4.22.3
vs 2019

**Comment by pangweiwei** [comment]
添加类似这样的配置到你的Build.cs
```
            case UnrealTargetPlatform.IOS:
                {
                    PublicLibraryPaths.Add(Path.Combine(externalLib, "iOS"));
                    PublicAdditionalLibraries.Add("lua");
                    break;
                }

```

**Comment by yanjia2304** [comment]
![image](https://user-images.githubusercontent.com/11566445/64603304-c14b6180-d3f2-11e9-829d-2d4073f9f211.png)

slua_unreal.Build.cs 中已经有写了。

**Comment by pangweiwei** [comment]
添加到你的工程里面

**Comment by huiger8723** [comment]
非常抱歉又问这个，感觉作者写的很清楚了，但是我按照这么操作后就是不行，还是报同样的错，ue4.23.1，vs2017，和版本有关系吗

**Comment by mimiky** [comment]
> 非常抱歉又问这个，感觉作者写的很清楚了，但是我按照这么操作后就是不行，还是报同样的错，ue4.23.1，vs2017，和版本有关系吗

一样的问题 请问你解决了吗？
