### ISSUE TITLE
enableMultiThreadGC引发UGCObjectReferencer异常问题

### ISSUE THREAD

**Issue by kimixuchen** [Tencent/sluaunreal#201]
我最近在seamlesstravel过程中碰到了一个异常情况，发生在UGCObjectReferencer::AddReferencedObjects函数调用中：

	void UGCObjectReferencer::AddReferencedObjects(UObject* InThis, FReferenceCollector& Collector)
	{	
		UGCObjectReferencer* This = CastChecked<UGCObjectReferencer>(InThis);
		// Note we're not locking ReferencedObjectsCritical here because we guard
		// against adding new references during GC in AddObject and RemoveObject.
		// Let each registered object handle its AddReferencedObjects call
	
		for (FGCObject* Object : This->ReferencedObjects)
		{
			check(Object);
			Object->AddReferencedObjects(Collector);
		}
	
		Super::AddReferencedObjects( This, Collector );
	}

简单来说就是在遍历`This->ReferencedObjects`时UE报警里面有元素被删除了，进而引发了一些异常行为，通常是崩溃。断点调试发现在对LuaState执行AddReferencedObjects方法时，slua会根据enableMultiThreadGC设置判断是否要执行lua_gc，而lua_gc后又碰巧有一个LuaArray需要销毁，由于LuaArray继承自FGCObject，因此会执行`~FGCObject`方法，修改ReferencedObjects。

	void LuaObject::deleteFGCObject(lua_State* L, FGCObject * obj)
	{
    	if (!IsGarbageCollecting())
        	delete obj;
    	else {
        	auto ls = LuaState::get(L);
        	ls->deferDelete.Add(obj);
    	}
	}

最终，ReferencedObjects在遍历时有元素被删除了。

继续查看源码发现，`LuaObject::deleteFGCObject`会判断当前UE是否在gc，如果在gc会延迟delete掉FGCObject。但是`UGCObjectReferencer::AddReferencedObjects`函数并不只在UEGC时被调用，比如`UClass::CallAddReferencedObjects()`方法内部也有调用，本人就是在seamlesstravel时执行到了这里，然后出现异常的。是不是需要在`LuaState::AddReferencedObjects`里面多加一些判断？

**Comment by pangweiwei** [comment]
感觉上，最简单的修改策略是所有的FGCObject都延后delete能满足你的需求？

**Comment by kimixuchen** [comment]
貌似可行，都放在PostGarbageCollect时候清理。
另外我还有个问题，就是enableMultiThreadGC有哪些作用？
我理解上一种是在UE的GC的collect阶段，分配到UGCObjectReferencer的work thread有机会在collect阶段执行一下lua_gc，减轻main thread在onEngineGC时luagc的压力。另一种是在非UEGC时，只要有任何线程调用到了LuaState::AddReferencedObjects，比如上面的例子，就执行lua_gc，缩短luagc的间隔。
不知我想的是否准确？

**Comment by pangweiwei** [comment]
你想的是对的，非MultiThreadGC就是每帧tick做gc，MultiThreadGC就是分配 work thread去gc

**Comment by kimixuchen** [comment]
好的，谢谢！

**Comment by kimixuchen** [comment]
请问这个问题slua有后续修改计划不？

**Comment by pangweiwei** [comment]
在休假，回去后就修复。发自我的华为手机-------- 原始邮件 --------发件人： 徐晨 <notifications@github.com>日期： 2019年9月30日周一 下午2:24收件人： Tencent/sluaunreal <sluaunreal@noreply.github.com>抄送： siney <sineysan@163.com>, State change <state_change@noreply.github.com>主    题： Re: [Tencent/sluaunreal] enableMultiThreadGC引发UGCObjectReferencer异常问题 (#201)请问这个问题slua有后续修改计划不？

**Comment by kimixuchen** [comment]
你好，我本地运行了一下，发现把FGCObject都先放到deferDelete，PostGarbageCollect时销毁，可能也有问题。我在Editor中开一局游戏再关掉，luastate已经随着GameInstance销毁，但此时deferDelete里还有东西，这些FGCObject遗留在了UGCObjectReferencer中，无法被删除。而且LuaArray的成员也已被释放，再访问会出现地址错误，所以我Editor开第二局游戏就会崩溃。
另外，有没有FGCObject被多次加入deferDelete数组的隐患？

**Comment by pangweiwei** [comment]
嗯，是有问题发自我的华为手机-------- 原始邮件 --------发件人： 徐晨 <notifications@github.com>日期： 2019年10月10日周四 下午3:31收件人： Tencent/sluaunreal <sluaunreal@noreply.github.com>抄送： siney <sineysan@163.com>, State change <state_change@noreply.github.com>主    题： Re: [Tencent/sluaunreal] enableMultiThreadGC引发UGCObjectReferencer异常问题 (#201)你好，我本地运行了一下，发现把FGCObject都先放到deferDelete，PostGarbageCollect时销毁，可能也有问题。我在Editor中开一局游戏再关掉，luastate已经随着GameInstance销毁，但此时deferDelete里还有东西，这些FGCObject遗留在了UGCObjectReferencer中，无法被删除。而且LuaArray的成员也已被释放，再访问会出现地址错误，所以我Editor开第二局游戏就会崩溃。
另外，有没有FGCObject被多次加入deferDelete数组的隐患？

**Comment by pangweiwei** [comment]
有没有FGCObject被多次加入deferDelete数组的隐患？

这个是没有的，一个fgcobject只会添加一次，没有delete前，那段地址也不会被复用

我目前的思考就是在luastate close的时候，把deferDelete的内容删除，清空。

**Comment by kimixuchen** [comment]
嗯，明白了，谢谢！
