### ISSUE TITLE
LuaUserWidget 存在内存泄漏

### ISSUE THREAD

**Issue by D3ZAX** [Tencent/sluaunreal#207]
两种情况：
1、slua.loadUI出来后，若没有AddToViewport或是添加到父节点上，丢失lua引用后会造成内存泄漏，无法自动回收
2、LuaUserWidget 绑定按钮事件的lua方法中引用了自身的lua脚本，lua脚本中又引用了这个按钮。若不解绑而后过一段时间，从父节点上删除，丢失引用后，无法自动回收

判断方法：
重写BeginDestroy和FinishDestroy并打印日志，发现两者都不会调用

普通UserWidget则可以自动回收，BeginDestroy和FinishDestroy会自动调用

**Comment by D3ZAX** [comment]
建议把绑定的UObject在传到lua层时改为lightuserdata而不是新建的UserData，将内存管理全部交给C++层，在BeginDestroy时再彻底销毁绑定

**Comment by unicodecndddd** [comment]
我这边也遇到了同样的问题。但是解决的时候发现会产生其他问题。

**Comment by unicodecndddd** [comment]
但是这么修改有一个问题是：slua.loadUI出来后，若没有AddToViewport或是添加到父节点上，就等于LuaUserWidget没有引用，此时会被c++gc销毁。

**Comment by unicodecndddd** [comment]
如果想要在lua中引用住这个LuaUserWidget，似乎就又绕回开始的问题。
不知道还有没有其他方法，可以避免这个问题？

**Comment by D3ZAX** [comment]
但是正常的UserWidget就是load进来后不AddToViewport后就会被GC销毁啊，我觉得这不是问题，反而是和UE4的机制保持一致了

**Comment by D3ZAX** [comment]
但是如果你改luabase的话，会同时影响luaactor，luacomponent等其他lua组件，不知道是否会引起其他问题。是否该单独独立出一个luauserwidget的初始化方法？

**Comment by D3ZAX** [comment]
另外button绑定lua方法引用了ui绑定的luatable的情况你有没有试？貌似这种方法依然无法使ui被gc回收

**Comment by pangweiwei** [comment]
> 另外button绑定lua方法引用了ui绑定的luatable的情况你有没有试（需要先加到AddToViewport，然后过几秒再移除）？貌似这种方法依然无法使ui被gc回收

你这样是closure引用了 table，导致无法释放吧？
你可以在remove里，把upvalue置空。

**Comment by unicodecndddd** [comment]
我是在lua中写了一个统一的方法移除事件，所以没有遇到过第二个问题

**Comment by D3ZAX** [comment]
嗯，我试下

**Comment by unicodecndddd** [comment]
关于是否要把luauserwidget和luaactor分开的问题。
我是觉得现在的问题原因其实是luabase和table相互引用，导致不论是unreal还是lua的gc都无法正确销毁对方。这个问题在actor中也存在，只不过一般都是spawnactor然后k2_destroy不太会遇到而已。
当然会有什么问题，目前还不知道。。。。

**Comment by D3ZAX** [comment]
把upvalue置空确实可以释放，但问题是必须知道是哪些方法的upvalue引用住了ui，感觉并不直接使用。

我打算把所有luauserwidget在lua端的引用改为弱引用，然后完全把内存交给C++试试。这样至少可以防止内存泄漏，最多也就只是lua层报错。不然UI各种控件，各种绑定，很容易出现内存泄漏的情况。
