### ISSUE TITLE
Enumerator对LuaArray的引用导致gc两遍才能删除LuaArray

### ISSUE THREAD

**Issue by kimixuchen** [Tencent/sluaunreal#210]
你好，我发现一个问题，比如如下代码：
`function foo()
    local Datas = slua.array()
    for k,v in pairs(Datas) do
        --
    end
end`

会创建一个LuaArray和LuaArray::Enumerator，foo函数结束后理论上Enumerator和LuaArray都没有引用了。但是Enumerator创建时对LuaArray添加了一个引用，而且是通过一张全局表添加的，因此第一遍lua_gc时无法删除LuaArray，要再执行一次lua_gc才能删除。

在刚进入一个level，执行luaarray相关操作，然后立即切level，就会在luaarray删除之前就销毁前一个level，导致luaarray引用了被删除的数据，从而概率性引发崩溃。

**Comment by pangweiwei** [comment]
> luaarray引用了被删除的数据，从而概率性引发崩溃。

为什么？没理解。

**Comment by kimixuchen** [comment]
我遇到情况大致这样，luaarray是PlayerState数组，开了enableMultiThreadGC，然后进行下面的流程：
1. 进入到一个level，在fun中获取到luaarray并遍历，fun结束后理论上luaarray和enumerator在lua中都不该被引用了
2. 立即OpenLevel到一个新的level，从第一步到现在还没有发生过GC
3. UE调用到loadMap方法，内部
    3.1 把旧level的Actor都标记为PendingKill，包括PlayerState
    3.2 TrimMemory()，进行带清理的GC，lua也在此时gc，enumerator被清理掉，但luaarray由于有全局表的引用，在这轮不会被清理。enumerator析构时释放全局表对luaarray的引用。
4. 下次UE GC时，会先调用LuaArray::AddReferencedObjects方法，luaarray再去对PlayerState加引用，但此时PlayerState内存已经被释放了，因此访问它导致异常

**Comment by pangweiwei** [comment]
明白了，在obj  AddReferenced的时候判断一下
if (obj && obj->IsValidLowLevel())
应该就可以了。

**Comment by kimixuchen** [comment]
嗯，好的
