### ISSUE TITLE
最新主支在UE422 编译Android报错

### ISSUE THREAD

**Issue by AngeliaQing** [Tencent/sluaunreal#212]
最新主支在UE422 编译Android报错：
error: use of undeclared identifier 'TEXT'

具体如下：
`UATHelper: Packaging (Android (ETC1)):                ^
UATHelper: Packaging (Android (ETC1)):   In file included from H:/h3d_mobile/ue4_lua/trunk/client/Plugins/slua_unreal/Intermediate/Build/Android/UE4/Development/slua_unreal/Module.slua_unreal.cpp:14:
UATHelper: Packaging (Android (ETC1)):   H:\h3d_mobile\ue4_lua\trunk\client\Plugins\slua_unreal\Source\slua_unreal\Private\LuaProfiler.cpp(154,3):  error: use of undeclared identifier 'TEXT'
UATHelper: Packaging (Android (ETC1)):                   ensure(ls);
UATHelper: Packaging (Android (ETC1)):                   ^
UATHelper: Packaging (Android (ETC1)):   H:/Program Files (x86)/Epic Games/UE_4.22/Engine/Source/Runtime/Core/Public/Misc/AssertionMacros.h(318,97):  note: expanded from macro 'ensure'
UATHelper: Packaging (Android (ETC1)):           #define ensure(           InExpression                ) UE_ENSURE_IMPL( , false, InExpression, TEXT(""))
UATHelper: Packaging (Android (ETC1)):                                                                                                          ^
UATHelper: Packaging (Android (ETC1)):   In file included from H:/h3d_mobile/ue4_lua/trunk/client/Plugins/slua_unreal/Intermediate/Build/Android/UE4/Development/slua_unreal/Module.slua_unreal.cpp:14:
UATHelper: Packaging (Android (ETC1)):   H:\h3d_mobile\ue4_lua\trunk\client\Plugins\slua_unreal\Source\slua_unreal\Private\LuaProfiler.cpp(156,3):  error: use of undeclared identifier 'TEXT'
UATHelper: Packaging (Android (ETC1)):                   ensure(selfProfiler.isValid());
UATHelper: Packaging (Android (ETC1)):                   ^
UATHelper: Packaging (Android (ETC1)):   H:/Program Files (x86)/Epic Games/UE_4.22/Engine/Source/Runtime/Core/Public/Misc/AssertionMacros.h(318,97):  note: expanded from macro 'ensure'
UATHelper: Packaging (Android (ETC1)):           #define ensure(           InExpression                ) UE_ENSURE_IMPL( , false, InExpression, TEXT(""))
UATHelper: Packaging (Android (ETC1)):                                                                                                          ^
UATHelper: Packaging (Android (ETC1)):   In file included from H:/h3d_mobile/ue4_lua/trunk/client/Plugins/slua_unreal/Intermediate/Build/Android/UE4/Development/slua_unreal/Module.slua_unreal.cpp:14:
UATHelper: Packaging (Android (ETC1)):   H:\h3d_mobile\ue4_lua\trunk\client\Plugins\slua_unreal\Source\slua_unreal\Private\LuaProfiler.cpp(165,3):  error: use of undeclared identifier 'TEXT'
UATHelper: Packaging (Android (ETC1)):                   ensure(lua_gettop(L) == 0);`

**Comment by pangweiwei** [comment]
fixed
