### ISSUE TITLE
Android 打包出来崩溃

### ISSUE THREAD

**Issue by riceliu** [Tencent/sluaunreal#213]
打开弹框显示  Failed to open descriptor file ../../../democpp/democpp.uproject

**Comment by pangweiwei** [comment]
demo工程？ democpp/democpp.uproject 文件丢失？

**Comment by riceliu** [comment]
> demo工程？ democpp/democpp.uproject 文件丢失？

是demo工程， democpp.uproject 不是在项目的根目录吗？

**Comment by pangweiwei** [comment]
你是打包apk在安卓上跑，出现上面错误信息？

**Comment by riceliu** [comment]
我是通过vs DebugGame Android打包出来的apk
是这样打包吗？

**Comment by pangweiwei** [comment]
截个图看看
没有任何代码逻辑需要democpp.uproject，这个只是工程文件，打包后不需要这个文件。
