### ISSUE TITLE
如何在lua读取Table Row的表格数据？

### ISSUE THREAD

**Issue by gzbin7878at2016** [Tencent/sluaunreal#220]
我想在lua里面，读取蓝图定义的表格数据，请问下我需要怎么实现呢？
就是 GetDataTableRow这个蓝图函数怎么在lua实现，实现步骤及注意点？谢谢

**Comment by pangweiwei** [comment]
你如果知道这个函数用c++怎么调用，可以直接使用cppbinding，或者extersion方法扩展到lua里

参考，https://github.com/Tencent/sluaunreal/wiki/CppBinding-%E7%AE%80%E5%8D%95%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E

**Comment by gzbin7878at2016** [comment]
好的，我参考下

**Comment by parnny** [comment]
![image](https://user-images.githubusercontent.com/6868180/67670454-e863ef80-f9ae-11e9-88ff-edfc6440563f.png)
![image](https://user-images.githubusercontent.com/6868180/67670476-f0bc2a80-f9ae-11e9-8ba1-7efefa811d06.png)
![image](https://user-images.githubusercontent.com/6868180/67670532-0d586280-f9af-11e9-8ae6-e33db10cebe1.png)
![image](https://user-images.githubusercontent.com/6868180/67670564-1fd29c00-f9af-11e9-8d4a-a5407668737e.png)

在 UStructProperty* StructProp = Cast<UStructProperty>(Stack.MostRecentProperty); 这里获取为空指针, 导致后边真正获取数据的代码没有执行, 是我传参的方式不对吗,请教一下各位大佬

**Comment by pangweiwei** [comment]
你可以直接拖一个 蓝图调用 GetDataTableRowNames，传入你的DataTable，返回RowNames


```lua
    local data = slua.loadObject("DataTable'/Game/NewDataTable.NewDataTable'")
    local x = self:GetTableRow(data)
```

**Comment by gzbin7878at2016** [comment]
thx

**Comment by FTQZS** [comment]
我没太看明白，到底是怎么读取的呢？我尝试各种方法读取到了，但得到的是父类的指针，不知道怎么转成对应数据结构类型
