### ISSUE TITLE
lua_cjson 整合进来后，android打包失败

### ISSUE THREAD

**Issue by gzbin7878at2016** [Tencent/sluaunreal#221]
请教下大佬，我lua_cjson 整合到插件里面了，PC可以用
现在想android平台也能用，但是打包报错
UATHelper: Packaging (Android (Multi:ASTC,PVRTC,DXT,ATC,ETC2,ETC1a,ETC1)):     E:\UE_PJ\QuestKongfu\KongfuProject\Plugins\slua_unreal\Source\slua_unreal\Private/LuaCJsonWrap.cpp:0: error: undefined reference to 'slua::luaopen_cjson(slua::lua_State*)'
UATHelper: Packaging (Android (Multi:ASTC,PVRTC,DXT,ATC,ETC2,ETC1a,ETC1)):     E:\UE_PJ\QuestKongfu\KongfuProject\Plugins\slua_unreal\Source\slua_unreal\Private/LuaState.cpp:0: error: undefined reference to 'slua::luaopen_cjson(slua::lua_State*)'
UATHelper: Packaging (Android (Multi:ASTC,PVRTC,DXT,ATC,ETC2,ETC1a,ETC1)):     clang++.exe: error: linker command failed with exit code 1 (use -v to see invocation)
PackagingResults: Warning: skipping incompatible E:/UE_PJ/QuestKongfu/KongfuProject/Plugins/slua_unreal/Library/Android/armeabi-arm64/liblua.a while searching for lua
这个是什么原因呢

**Comment by gzbin7878at2016** [comment]
是不是liblua.a这个库没用重新生成？
请问下我要怎么生成这个库？

**Comment by pangweiwei** [comment]
undefined reference to 'slua::luaopen_cjson(slua::lua_State*)

这不是写的很清晰吗？你看看你有没有这个函数定义

**Comment by gzbin7878at2016** [comment]
sln工程 打开编译是正常的，
 CMakeLists.txt 我添加如下
#being lua cjson
set(LUA_CJSON_INC_PATH ${EXT_SRC_ROOT}/luacjson)
set(LUA_CJSON_SRC_PATH ${EXT_SRC_ROOT}/luacjson)
set (LUA_CJSON_SRC_FILES
	${LUA_CJSON_SRC_PATH}/fpconv.cpp
    ${LUA_CJSON_SRC_PATH}/fpconv.h
	${LUA_CJSON_SRC_PATH}/strbuf.cpp
    ${LUA_CJSON_SRC_PATH}/strbuf.h
	${LUA_CJSON_SRC_PATH}/lua_cjson.cpp
	${LUA_CJSON_SRC_PATH}/lua_cjson.h
)
#end lua cjson

set(THIRDPART_INC_PATH ${THIRDPART_INC_PATH} ${LUA_SOCKET_INC_PATH} ${LUA_CJSON_INC_PATH})
set(THIRDPART_SRC_FILES ${THIRDPART_SRC_FILES} ${LUA_SOCKET_SRC_FILES} ${LUA_CJSON_SRC_FILES})
问下，打包android版本，make_android.sh 这个要不要修改

**Comment by pangweiwei** [comment]
你还需要修改cjson代码，加入slua namespace，slua的lua代码是修改过的，加入了c++ 
namespace

**Comment by gzbin7878at2016** [comment]
命名空间我修改过了，PC跑都没问题了，测试过了，就是android打包报错
随便问下 android liblua.a这个库里面是什么代码？

**Comment by pangweiwei** [comment]
android 也是通过cmake那个工程编译的，使用make_android.sh编译的。

**Comment by dsz0** [comment]
请问make_android.sh是否能在Windows的MINGW64中运行，CMake和VS分别用的是什么版本？
还是说编译成功需要什么其他条件？

**Comment by pangweiwei** [comment]
首先你需要安装ndk，ndk支持的编译变换下，设置ANDROID_NDK环境变量为ndk安装目录，安装最新版cmake，然后就可以了，不需要vs。

ps：我们使用的macosx来编译android的，理论上ndk的编译环境安装cmake也是支持的。

**Comment by dsz0** [comment]
另外，现在ue4的安卓打包已经要求NDK版本使用r14b,
但slua还是建议r13么？？

**Comment by pangweiwei** [comment]
另外你可以 fork 一个cjson的分支，我看看具体什么原因。

**Comment by pangweiwei** [comment]
你可以测试一下，简易版本只是没有在其他版本上编译过，如果有问题可以修改

**Comment by dsz0** [comment]
在win10系统，使用NDK13，14，15配合数个Cmake版本，2.8，3.1，3.15，3.16都没有成功，我还装了好几个vs的版本……

**Comment by pangweiwei** [comment]
你fork一个分支，发给我看看吧
