### ISSUE TITLE
LuaReference要不要加入auto null功能？

### ISSUE THREAD

**Issue by kimixuchen** [Tencent/sluaunreal#223]
Hi，LuaReference模拟了UEGC的标记阶段，但是UE会在这个阶段把指向PendingKill UObject的指针设为null，但LuaReference并没有做这个操作。造成影响是LuaArray中引用的Actor如果被删除了，无效的指针依然留在LuaArray中。
虽然我在commit 4b96317570b8995cbdd3fba6ee23a02bccb70630中尝试修复，但后来发现问题依然在
`void* value = container?p->ContainerPtrToValuePtr<void>(base, n):base;
				UObject* obj = p->GetObjectPropertyValue(value);`

因为Object如果被释放了，base指针就已经坏了，ContainerPtrToValuePtr会报错。
感觉LuaReference实现了auto null的话，就可以杜绝LuaArray，LuaMap引用被删除UObject的问题了。

**Comment by pangweiwei** [comment]
嗯，在内部考虑了auto null的问题，反映到了对应的property，但没有反应回LuaArray和LuaMap。

**Comment by pangweiwei** [comment]
目前的修改是在auto null之后，删除容器内的元素。

**Comment by kimixuchen** [comment]
好的，赞
