### ISSUE TITLE
使用setToTable发生崩溃

### ISSUE THREAD

**Issue by yelei8363** [Tencent/sluaunreal#225]
NS_SLUA::LuaState *state = NS_SLUA::LuaState::get();
NS_SLUA::LuaVar _luavarMap(state->getLuaState(), -1, NS_SLUA::LuaVar::LV_TABLE);
_luavarMap.setToTable<FString, int32>(TEXT("roomID"), 123);
我这样调用，会再setToTable发生崩溃，请问setToTable是如何正确调用，我在例子中无法找到，谢谢

**Comment by pangweiwei** [comment]
提供崩溃调用栈，我估计是_luavarMap根本就不是一个table
