### ISSUE TITLE
关于Lua调用C++函数走ProcessEvent的开销

### ISSUE THREAD

**Issue by kimixuchen** [Tencent/sluaunreal#227]
你好，我发现现在lua通过反射调用C++函数，都会使用ProcessEvent接口，但ProcessEvent集成的功能太多了，还负责蓝图函数调用，RPC调用等功能，而且OutParm的获取需要每次重新遍历。如果仅调用本地C++函数，最简情况，不做check等检查，可以手动调用UFunction::Invoke进行函数。还有，C++函数的OutParam是确定的，因此可以预先缓存，感觉也能加快速度。
不过走ProcessEvent安全性比较有保证，本地测试ProcessEvent无关操作会消耗可观时间，不知这要怎么权衡

**Comment by pangweiwei** [comment]
你说的是 扩展的 extension 的c++方法？

**Comment by kimixuchen** [comment]
就是普通的C++类UFunction，非RPC，纯本地调用

**Comment by pangweiwei** [comment]
override现在需要processevent的重载

**Comment by pangweiwei** [comment]
而且，你增加是否是rpc，蓝图函数等判断，然后自己处理frame的，代码量也不必processevent少。

**Comment by kimixuchen** [comment]
是的，自己判断也需要处理这么多情况，去掉一些check检查也不安全。

**Comment by kimixuchen** [comment]
还有我觉得C++子类override的父类UFunction，如果在中lua调用，理论上可以不用ProcessEvent，直接用UFunction::Invoke，先调用到父类的execXXX方法，然后再调用到子类override的方法体。
