### ISSUE TITLE
lua整合第三方socket疑问？

### ISSUE THREAD

**Issue by gzbin7878at2016** [Tencent/sluaunreal#228]
想问下，这个socket的使用场景是什么？
Demo里面也没有相关演示
试了下，http请求，这个是阻塞式的，会卡游戏进程

**Comment by pangweiwei** [comment]
主要是用于调试服务，不用于网络相关开发，http可以直接用ue自带的http模块，Demo也有演示。

**Comment by gzbin7878at2016** [comment]
好的谢谢
