### ISSUE TITLE
LuaArray有访问无效FScriptArray风险？

### ISSUE THREAD

**Issue by kimixuchen** [Tencent/sluaunreal#229]
你好，关于LuaArray我还有一个问题。如果从lua获取C++对象成员TArray，那lua中得到的就是成员TArray的引用，LuaArray里的`FScriptArray* array`指向成员TArray数据。
如果C++对象被UE的GC删除了，但这个LuaArray在lua里还在被引用，未被lua gc，它也无法知道对应的C++对象已经没了，那之后再访问`array`属性就是在访问非法内存。继续在lua里访问它，或者调用`LuaArray::AddReferencedObjects`方法都是危险的。
感觉我之前在[https://github.com/Tencent/sluaunreal/issues/210](url)中遇到问题的根本原因可能是这个。

**Comment by pangweiwei** [comment]
是有这个风险，我fix一下
