### ISSUE TITLE
stateName 参数不理解

### ISSUE THREAD

**Issue by gzbin7878at2016** [Tencent/sluaunreal#230]
请问下大佬，LuaBase init stateName 这个参数做什么用的？
我现在Editor里面要调试多人的逻辑，lua里面的全局变量是多个client共用的，这个是什么原因？

**Comment by pangweiwei** [comment]
LuaBase 默认是和GameInstance相关的LuaState的，slua支持创建多个luastate，每个luastate有自己的逻辑和数据，你可以通过name来区分它们，luabase的Statename就是配置运行在那个luastate里。

默认不指定的话，就是当前gameinstance对应的luastate。

Editor里调试多人逻辑，就是多个gameinstance，就是多个luastate。

**Comment by gzbin7878at2016** [comment]
目前已经支持了吗？
我看代码 LuaState mainState 这个是静态变量
LuaBase init这个函数auto ls = LuaState::get(); 这个获得ls就是这个静态变量
好像没有多luastate使用，是我哪里误解了吗？

**Comment by gzbin7878at2016** [comment]
LuaBase init里面 我试着根据GPlayInEditorID 来获得ls
if (GPlayInEditorID > 0)
{
	ls = LuaState::get(GPlayInEditorID);
}
当结束调试，我设置StateIndex =0
StateIndex 这个不能清除吗？
