### ISSUE TITLE
UE423 slua profile打开不能更新

### ISSUE THREAD

**Issue by AngeliaQing** [Tencent/sluaunreal#231]
游戏启动后，slua profile显示空界面，没有任何更新
![image](https://user-images.githubusercontent.com/35912697/68585064-1e7b9600-04bc-11ea-8cee-ed7c4e49c281.png)

调试了下，貌似没有建立连接。这里没有回调到，不知道为啥
![image](https://user-images.githubusercontent.com/35912697/68586216-212bba80-04bf-11ea-9844-13fba9393bf5.png)

**Comment by AngeliaQing** [comment]
调试了下，貌似没有建立连接

**Comment by pangweiwei** [comment]
你看下demo里代码test profile lua
，需要正确配置ip，如果你在真机上测试。

**Comment by pangweiwei** [comment]
我们补充profile的使用文档

https://github.com/Tencent/sluaunreal/wiki/slua-Profiler-%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E
