### ISSUE TITLE
继承自LuaCharacterBase ，使用AIController的SimpleMoveLocation无效

### ISSUE THREAD

**Issue by kingkunkun** [Tencent/sluaunreal#236]
继承自LuaCharacterBase蓝图类，调用自己的AIController的SimpleMoveLocation不能移动。
有2情况：
 1：继承自LuaCharacterBase的蓝图类默认在场景中，能获取AIController但是调用SimpleMoveLocation 不能移动

**Comment by pangweiwei** [comment]
你这个问题不是slua问题，是unreal使用的问题。

**Comment by kingkunkun** [comment]
谢谢及时回复，NavaMesh路径设置没问题。如果是继承自Character ，在蓝图内调用 GetController（）.SimpleMoveToLocation（），能正确移动。 如果继承自LuaCharacter则原地不动

**Comment by kingkunkun** [comment]
目前我看只有这两个区别，请问如果继承自LuaCharacter ，想能正确使用AIController的SimpeMoveToLocation进行移动，需要设置哪些？还是我unreal使用需要设置哪些呢，谢谢。

**Comment by pangweiwei** [comment]
我自己测试没有任何问题。你拿不到controller可能是没有正确设置auto possess ai 属性。

**Comment by kingkunkun** [comment]
auto possess ai 属性设置为 pawned or place in World，目前能拿到 controller ，但是調用SimpleMoveToLocation方法不能移動，如果同样的设置改为继承Character就没问题

**Comment by kingkunkun** [comment]
我找了slua-unreal官方的例子没有这方面的，能否在下次更新时 添加一个这方面的内容呢。 谢谢

**Comment by morirain** [comment]
检查你的nav 这是unreal相关的问题 试着修改Can Affect Navigation Generation
