### ISSUE TITLE
增量打包问题

### ISSUE THREAD

**Issue by gzbin7878at2016** [Tencent/sluaunreal#238]
请教下大佬，我想打一个APK和一个DLC，用Project launcher的方式。
如果我lua逻辑修改了，再重新打DLC时候，lua代码逻辑没有更新的问题。
我lua文件是在Project Settings -> Packaging -> Additional Non-Asset Directories to Package
添加Lua文件夹到打包，
感觉问题是lua不是UE4的资源，关联引用都没有，所以即使有变动，UE4也认不出来导致的？
请问有什么好的方法，满足增量更新的需求吗？

**Comment by pangweiwei** [comment]
我们是自己打包lua为pak，自己去下载，然后把pak mount到文件系统。

**Comment by gzbin7878at2016** [comment]
好的，谢谢

**Comment by hxhb** [comment]
我开源了一个工具，可以进行差异分析和打包资源，实现增量更新 https://zhuanlan.zhihu.com/p/102998101
