### ISSUE TITLE
Profile每次触发hook都getinfo并做字符串拼接函数名的开销比较重

### ISSUE THREAD

**Issue by quabqi** [Tencent/sluaunreal#242]
可以考虑直接保存ci结构

**Comment by Glossimar** [comment]
> 可以考虑直接保存ci结构

lua_getinfo方法本质上是通过CallInfo和lua_State获取信息。如果通过将CallInfo从客户端发送至服务器端，然后从服务器端对函数信息进行收集的话，Server端接收信息时的lua_State已经不再是发送时的lua_State了，所以接收到的CallInfo就没有意义了。

**Comment by quabqi** [comment]
最小只需要S信息就可以了，不需要n和l，另外拷贝给FString拼接不是必须的

**Comment by Glossimar** [comment]
takeSample方法是对Profiler的CPU收集数据进行打包发送，函数名是需要收集的信息，属于lua_Debug中的name成员，这是l的信息，如果只有S是无法满足Profiler对CPU数据收集的需求。字符串拼接问题正在开销优化的解决方法

**Comment by Glossimar** [comment]
> 最小只需要S信息就可以了，不需要n和l，另外拷贝给FString拼接不是必须的

takeSample方法是对Profiler的CPU收集数据进行打包发送，函数名是需要收集的信息，属于lua_Debug中的name成员，这是l的信息，如果只有S是无法满足Profiler对CPU数据收集的需求。字符串拼接问题正在思考开销优化的解决方法～

**Comment by Glossimar** [comment]
takeSample方法是对收集到CPU信息进行打包发送，而收集到的CPU信息中函数名也是不可缺少的，函数名属于lua_Debug中的name成员，通过lua_State和CallInfo来获取。如果只收集S信息则不满足CPU的功能需求。字符串拼接问题正在思考优化方案～

**Comment by ShuraLiu** [comment]
这个issue为什么关闭了，现在profile卡的根本不能用。
