### ISSUE TITLE
ue4.22 DELEGATE相关

### ISSUE THREAD

**Issue by castle2048** [Tencent/sluaunreal#243]
请问类似于4.22版本中**UUserWidget::BindToAnimationFinished**函数，我该如何在Lua中使用这个绑定事件呢？
不同于4.21版本中有声明**OnAnimationFinished**变量
`/** Fires when the widget animation is finished. */`
	`UPROPERTY(BlueprintAssignable, Category="Animation")`
	`FOnWidgetAnimationPlaybackStatusChanged OnAnimationFinished;`
之前我的调用方式如下
`us_widget["anim"].OnAnimationFinished:Add(`
`        function()`
`            print("Animation Finished")`
`            end`
`  end`
4.22版本中**UUserWidget::BindToAnimationFinished**声明如下
`/**`
`	 * Bind an animation finished delegate.`
`	 * @param Animation the animation to listen for starting or finishing.`
`	 * @param Delegate the delegate to call when the animation's state changes`
`	 */`
`	UFUNCTION(BlueprintCallable, Category = Animation)`
`	void BindToAnimationFinished(UWidgetAnimation* Animation, FWidgetAnimationDynamicEvent Delegate);`
请问我该如何在Lua中处理这个Delegate对象呢？

**Comment by pangweiwei** [comment]
使用slua. createDelegate函数 传入lua函数 返回值给到 那个需要delegate的函数

**Comment by castle2048** [comment]
问题解决了 谢谢大佬
