### ISSUE TITLE
lua文件加密发布，slua有方案吗？

### ISSUE THREAD

**Issue by yelei8363** [Tencent/sluaunreal#244]
咨询一下，UE4的slua有对lua文件进行加密的方案吗？还是说需要我们自己制作。

**Comment by pangweiwei** [comment]
你们需要自己制作，如果提供了统一的方案，又是开源的，相当于没有加密。
主要的修改可以考虑：
重新乱序opcode，定制你的虚拟机opcode；
编译；
对字节码加密；
修改loadbuffer函数。

**Comment by yelei8363** [comment]
好的，谢谢
