### ISSUE TITLE
lua调用lua重载的rpc函数异常

### ISSUE THREAD

**Issue by zh5243a** [Tencent/sluaunreal#245]
重现步骤：
1，创建一个rpc函数
2，在Lua脚本重载rpc函数
3，从lua脚本调用该rpc函数

* 最终会变成直接调用lua本地函数，而失去了rpc功能
* 如果从蓝图调用则正常

**Comment by pangweiwei** [comment]
嗯，确实有这个问题，我fix一下

**Comment by pangweiwei** [comment]
你的第一步创建一个rpc函数，是c++创建一个ufunction的rpc把？

**Comment by zh5243a** [comment]
我是在蓝图里面创建的，  服务端执行

**Comment by pangweiwei** [comment]
如果是这样，你直接调用 self.Super:SomeRpcFunction(） 就行了呀

**Comment by zh5243a** [comment]
这样的话会有另外一个问题， 调用组播函数时（服务端调用muticast）， 服务端执行的父类的函数，客户端执行的是重载后的lua函数

**Comment by pangweiwei** [comment]
你客户端重载rpc函数，难道不应该执行重载后的rpc？
你在客户端的rpc，是被服务器调用的，不是被自己调用的呀。

你的问题根本是，客户端的rpc和服务器rpc写在了一起，还是同名，是这样吗？

**Comment by zh5243a** [comment]
是啊，当rpc的响应函数属性设置 muticast的时候，在服务端执行该函数，正常情况下，服务端和客户端都会触发（执行相同的函数），而使用 self.Super:SomeMuticastRpcFunction() 后， 客户端正常（执行了重载后的lua响应函数），而服务端执行的却是父类的响应函数（未执行重载后的lua函数） ,两端响应了不同的函数

**Comment by pangweiwei** [comment]
懂了，所以，大概需要这么一个设计 self.rpc:SomeFunction() 就ok了

**Comment by zh5243a** [comment]
是呀， rpc逻辑比较特殊

**Comment by zh5243a** [comment]
还有 rpc的数组传递这个你们有试过能用吗， 我试了下，或者会蹦，或者会直接卡死

**Comment by pangweiwei** [comment]
你把的rpc 测试蓝图连接发我测试一下
还有你会卡死，会崩的蓝图也发给我

**Comment by zh5243a** [comment]
好的， 这是我qq 273143979  加一下？

**Comment by pangweiwei** [comment]
fixed
