### ISSUE TITLE
C++调用Lua函数，如果传入FVector则会编译不通过

### ISSUE THREAD

**Issue by pilaoda** [Tencent/sluaunreal#250]
![image](https://user-images.githubusercontent.com/12658348/70512005-aeb80400-1b6a-11ea-8f2e-35a9c418b4ac.png)
如图，我在上层使用LuaVar的call然后传入FVector，在pushArg里没有找到匹配参数类型的push方法

**Comment by pangweiwei** [comment]
外部需要传入FVector* 指针。

**Comment by pilaoda** [comment]
> 外部需要传入FVector* 指针。

那请问FVector*指向的内存，有没有什么办法确保在lua中保存这个FVector的时候不被销毁掉呢？

**Comment by pangweiwei** [comment]
内部会复制这段内存

**Comment by pilaoda** [comment]
error LNK2019: unresolved external symbol "public: static char const * __cdecl slua::TypeName<struct FVector,0>::value(void)" (?value@?$TypeName@UFVector@@$0A@@slua@@SAPEBDXZ) referenced in function "private: int __cdecl slua::LuaVar::pushArg<struct FVector *>(struct FVector *)" (??$pushArg@PEAUFVector@@$$V@LuaVar@slua@@AEAAHPEAUFVector@@@Z)   
还是编译不过

**Comment by pangweiwei** [comment]
你是不是没有 增加那个 类似 xxx_api的宏

**Comment by pilaoda** [comment]
> 你是不是没有 增加那个 类似 xxx_api的宏

是指在哪里加呢？

**Comment by pangweiwei** [comment]
类的定义哪里，你现在link不过，一般都是这个问题

**Comment by pangweiwei** [comment]
你是使用cppbinding导出c++接口，对吧，如果的你的c++接口在另外一个dll里，需要使用这个宏

#define DefLuaClassExtern(MODULE_API,CLS, ...) \
        DefLuaClassBaseExtern(MODULE_API,CLS) \
        LuaObject::newTypeWithBase(L,#CLS,std::initializer_list<const char*>{#__VA_ARGS__}); \

这个宏本质上是增加了一个 类似这样SLUA_UNREAL_API 的dllexport的申明

struct SLUA_UNREAL_API LuaClass {
}

**Comment by pilaoda** [comment]
可以了，感谢

**Comment by pilaoda** [comment]
刚刚试了一下，lua看起来并不会复制一份内存，我在C++中把new出来的FVector* delete掉之后，lua中的全局变量指向的内存乱了
![image](https://user-images.githubusercontent.com/12658348/70533774-ba202500-1b94-11ea-8f39-8bb9e41e96b6.png)

在new之后以及delete之前:
![image](https://user-images.githubusercontent.com/12658348/70533756-affe2680-1b94-11ea-8c7f-0cc8bdf77bc6.png)

在delete之后:
![image](https://user-images.githubusercontent.com/12658348/70533814-cc9a5e80-1b94-11ea-83bd-03eb9e809958.png)

**Comment by pangweiwei** [comment]
我刚才看了代码，UE 的 struct是会复制的，FVector 不是 UE 的struct，是需要new的，不过我也想是否可以统一不需要new。

```c++
template<class T>
		static int push(lua_State* L, const char* fn, const T* v, uint32 flag = UD_NOFLAG) {
            if(getFromCache(L,void_cast(v),fn)) return 1;
            luaL_getmetatable(L,fn);
			// if v is the UnrealType
			UScriptStruct* uss = nullptr;
			if (lua_isnil(L, -1) && isUnrealStruct(fn, &uss)) {
				lua_pop(L, 1); // pop nil
				uint32 size = uss->GetStructureSize() ? uss->GetStructureSize() : 1;
				ensure(size == sizeof(T));
				uint8* buf = (uint8*)FMemory::Malloc(size); // 这里会复制
				uss->InitializeStruct(buf);
				uss->CopyScriptStruct(buf, v); 
				cacheObj(L, void_cast(v));
				return push(L, new LuaStruct(buf, size, uss));
			}
			NewUD(T, v, flag);
			lua_pushvalue(L, -2);
			lua_setmetatable(L, -2);
			lua_remove(L, -2); // remove metatable of fn
            cacheObj(L,void_cast(v));
            return 1;
		}

```

**Comment by pilaoda** [comment]
> 我刚才看了代码，UE 的 struct是会复制的，FVector 不是 UE 的struct，是需要new的，不过我也想是否可以统一不需要new。
> 
> ```c++
> template<class T>
> 		static int push(lua_State* L, const char* fn, const T* v, uint32 flag = UD_NOFLAG) {
>             if(getFromCache(L,void_cast(v),fn)) return 1;
>             luaL_getmetatable(L,fn);
> 			// if v is the UnrealType
> 			UScriptStruct* uss = nullptr;
> 			if (lua_isnil(L, -1) && isUnrealStruct(fn, &uss)) {
> 				lua_pop(L, 1); // pop nil
> 				uint32 size = uss->GetStructureSize() ? uss->GetStructureSize() : 1;
> 				ensure(size == sizeof(T));
> 				uint8* buf = (uint8*)FMemory::Malloc(size); // 这里会复制
> 				uss->InitializeStruct(buf);
> 				uss->CopyScriptStruct(buf, v); 
> 				cacheObj(L, void_cast(v));
> 				return push(L, new LuaStruct(buf, size, uss));
> 			}
> 			NewUD(T, v, flag);
> 			lua_pushvalue(L, -2);
> 			lua_setmetatable(L, -2);
> 			lua_remove(L, -2); // remove metatable of fn
>             cacheObj(L,void_cast(v));
>             return 1;
> 		}
> ```

我看UE4官方关于GC和FVector的说明是建议原生结构体不要用指针，当成int一样的数值来传参，不然在栈外就没有GC机制维护他了。要不也加一个直接push结构体的？

**Comment by pangweiwei** [comment]
可以，我稍后fix
