### ISSUE TITLE
Linux上的DS在调用对象的UFunction时有概率崩溃

### ISSUE THREAD

**Issue by pilaoda** [Tencent/sluaunreal#251]
对象是会动态创建和销毁的，有用isValid判空，但上线有万分之一的概率会崩溃，堆栈很迷看不懂。
![image](https://user-images.githubusercontent.com/12658348/70514282-4ec35c80-1b6e-11ea-808c-c2ee7f1475b2.png)
![image](https://user-images.githubusercontent.com/12658348/70514344-73b7cf80-1b6e-11ea-8bea-4159fff6e407.png)
![image](https://user-images.githubusercontent.com/12658348/70514468-ab267c00-1b6e-11ea-910a-64b04bb9b101.png)
![image](https://user-images.githubusercontent.com/12658348/70514511-c1343c80-1b6e-11ea-99a9-055d592be4a3.png)
用的是旧版的Slua，isValid逻辑如下：
![image](https://user-images.githubusercontent.com/12658348/70514584-e6c14600-1b6e-11ea-89bb-3d946e22f6db.png)

目前怀疑是对象被销毁后，Lua对他的引用可能是野指针指向了别的UObject，判空侥幸通过，然后调成员函数时对象是Unknown导致了崩溃？

**Comment by pangweiwei** [comment]
我大概知道了，你是不是在lua里保存了返回的function，例如：
local f = act.someFunc
然后，在后面某个地方调用

f(...)

这样可能会导致一个问题，就是f里其实保存了ufunction指针，，但ufunction被删除了。

**Comment by pangweiwei** [comment]
你是不是在lua层保存了 返回的function，例如：

local f = actor.someFunction

然后在后面调用

f(actor,...)

这样可能，会导致你提到的问题？

**Comment by pilaoda** [comment]
> 你是不是在lua层保存了 返回的function，例如：
> 
> local f = actor.someFunction
> 
> 然后在后面调用
> 
> f(actor,...)
> 
> 这样可能，会导致你提到的问题？

并没有，只在lua的table里保存了一个actor，actor被gc销毁后再从table里拿他，然后调用他的方法
![image](https://user-images.githubusercontent.com/12658348/70520805-11b09780-1b79-11ea-98a8-8eade2242c21.png)

**Comment by pangweiwei** [comment]
你确认是crash在这个函数了？

**Comment by pilaoda** [comment]
> 你确认是crash在这个函数了？

查了一圈只有这里比较可疑，堆栈也看不出来在lua的哪里

**Comment by pangweiwei** [comment]
从截图的调用栈开，就是UFunction的指针，或者UProperty指针为空导致的crash

你的TeamInfos是啥，一个lua table？

**Comment by pilaoda** [comment]
> 从截图的调用栈开，就是UFunction的指针，或者UProperty指针为空导致的crash
> 
> 你的TeamInfos是啥，一个lua table？

是的，纯lua table

**Comment by pilaoda** [comment]
是否改用新版的带弱引用的会好一些？因为lua中对userdata的引用被GC销毁后会不会没办法自动变成nil？然后这个引用地址如果又在C++中重新指向了别的对象就有问题了。

**Comment by pangweiwei** [comment]
你是用哪个版本？

**Comment by pilaoda** [comment]
用的是没有弱引用的版本
![image](https://user-images.githubusercontent.com/12658348/70596492-031dbb00-1c21-11ea-95ad-a9d148326e5e.png)

**Comment by pangweiwei** [comment]
你看一下你现在代码里， LuaObject.h 235-253  行代码有没有weakptr的cache代码

**Comment by pilaoda** [comment]
> 你看一下你现在代码里， LuaObject.h 235-253 行代码有没有weakptr的cache代码

没有

**Comment by pangweiwei** [comment]
那你可以升级到最新版本，应该解决你说的问题。

**Comment by pangweiwei** [comment]
上面说错了，是LuaState.h: 235 ,有没有这样的代码

```c++
		// cache ufunction/uproperty ptr if index by lua
		struct ClassCache {
			typedef TMap<FString, TWeakObjectPtr<UFunction>> CacheFuncItem;
			typedef TMap<TWeakObjectPtr<UClass>, CacheFuncItem> CacheFuncMap;

			typedef TMap<FString, TWeakObjectPtr<UProperty>> CachePropItem;
			typedef TMap<TWeakObjectPtr<UClass>, CachePropItem> CachePropMap;
			
			UFunction* findFunc(UClass* uclass, const char* fname);
			UProperty* findProp(UClass* uclass, const char* pname);
			void cacheFunc(UClass* uclass, const char* fname, UFunction* func);
			void cacheProp(UClass* uclass, const char* pname, UProperty* prop);
			void clear() {
				cacheFuncMap.Empty();
				cachePropMap.Empty();
			}

			CacheFuncMap cacheFuncMap;
			CachePropMap cachePropMap;
		} classMap;

```

**Comment by pangweiwei** [comment]
另外你第一个，截图的调用栈，发一个全，后面是什么，我再看看

**Comment by pilaoda** [comment]
![image](https://user-images.githubusercontent.com/12658348/70606077-b93fcf80-1c36-11ea-93d7-2767e767a200.png)
堆栈下面没什么，是自己写的一个timer
ClassCache是有的，一模一样

**Comment by pangweiwei** [comment]
你在这里添加一行

```
 UFunction* func = reinterpret_cast<UFunction*>(ud);
        // 这里添加

if (!func || !func->IsValidLowLevel())
			luaL_error(L, "function is isvalid");

		FStructOnScope params(func);
		LuaObject::fillParam(L, offset, func, params.GetStructMemory());
		{
			LuaObject::callUFunction(L, obj, func, params.GetStructMemory());
		}
		// return value to push lua stack
		return LuaObject::returnValue(L, func, params.GetStructMemory());
```

看会不会有错误报告。

**Comment by pilaoda** [comment]
编辑器上无法复现，目前猜测是ds上一个UClass没有对象的时候，会被GC销毁，同时他的UFunction也会被GC销毁，但是GC标记UObject为Unreachable的时候，这个UObject对象由于异步分帧GC的结果可能依然存在，而他的参数UField可能已被销毁，此时就会造成崩溃。建议所有用到UObject的地方都加上对象Unreachable的判断，而不只是判断空指针和ValidLowLevel，之前isValid也是会认为Unreachable的对象是有效的，我们自己已经补上这个判断了。

**Comment by pangweiwei** [comment]
你们加了这个判断之后，实际测试如何？

**Comment by pilaoda** [comment]
> 你们加了这个判断之后，实际测试如何？

正常UObject不加Unreachable判断，崩溃率几十分之一，加了判断之后崩溃率万分之一。UFunction的Unreachable判断还没测试。

**Comment by pangweiwei** [comment]
能方便提供你的测试用例吗？我感觉有问题，正常UObject 和 UFunction都会被引用住，为什么会IsUnreachable ？

**Comment by pilaoda** [comment]
> 能方便提供你的测试用例吗？我感觉有问题，正常UObject 和 UFunction都会被引用住，为什么会IsUnreachable ？

你手动Destory就可以了。我们做的就是对一个单位造成伤害，血量0就销毁。

**Comment by pangweiwei** [comment]
我自己测试，创建10个actor，每帧随机删除一个，并且调用他们的成员方法，不管用不用slua.isValid都不会崩溃，如果使用isValid判断，没有任何异常，如果不适用isValid，则报告脚本错误：
Slua: Error: /Users/siney/sluaunreal/Content/Lua/Map2Actor.lua:69: arg 1 had been freed(0x16ead6b00), can't be used
stack traceback:
    [C]: in metamethod '__index'

说明Actor已经被脚本释放，仍然在访问的异常，但无论如何不会崩溃。

不知道你们是不是修改了ue的gc策略？在没有gc之前，会把标记需要删除的内存重新使用？或者其他优化？

**Comment by pilaoda** [comment]
不知道你是不是编辑器上复现的，编辑器上的GC策略是写死全量GC的（4.18版本），也就是说一个UObject会在一帧内，由pendingKill变成Unreachable再变成UD_HADFREE，不存在Unreachable这个中间状态。但如果你是构建好后独立运行的ds或客户端，他的GC策略是步进GC，每帧有时间限制（默认0.02秒），如果你的UObject数量够多那就很可能有一些卡在Unreachable这个中间状态。
总结一下复现前提：
1. UObject数量足够多。
2. 非编辑器环境。
3. 手动Destory某个actor之后，再等UE4的新一轮GC开始后，在后面某一帧调用其成员方法。

**Comment by pangweiwei** [comment]
嗯，关于你的第一个问题我也测试出来并修复了，关于你的第二个UFunction的问题，还在测试，暂时按照你的方法没有测试出来，我修复第一部分。

**Comment by pangweiwei** [comment]
第二个问题我没有测试出来，但是我增加了代码，在checkUObject 的时候，检查reachable
