### ISSUE TITLE
请问怎么导入C++里的类等类型？

### ISSUE THREAD

**Issue by FTQZS** [Tencent/sluaunreal#253]
比如在lua里调一个枚举，例子里直接UEnums.EXXXX就拿到了，UEnums是什么时候加载的？如何加载？

**Comment by pangweiwei** [comment]
新版已经没有这个东西了

**Comment by FTQZS** [comment]
新版没有了？要手动自己导需要的类型吗？利用CppBinding吗？没怎么看懂怎么导，有相关教程吗？

**Comment by pangweiwei** [comment]
import “someEnum"

**Comment by pangweiwei** [comment]
新版的例子也对应修改了：
例如
EPropertyClass = import"EPropertyClass"

**Comment by FTQZS** [comment]
谢谢，能导入枚举了，还试了导入部分C++类，有的成功，有的不行，像经常用的全局指针GEngine该怎么拿呢？想用GEngine->AddOnScreenDebugMessage方法打印Log什么的

**Comment by pangweiwei** [comment]
你可以做一个函数返回GEngine，比如GetGEngine

**Comment by pangweiwei** [comment]
如果你想使用AddOnScreenDebugMessage函数，这个函数没有UFunction标记，所以你需要使用extension机制扩展它，参考这里：
https://github.com/Tencent/sluaunreal/wiki/CppBinding-%E7%AE%80%E5%8D%95%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E#%E6%89%A9%E5%B1%95blueprint%E7%9A%84cppbinding

**Comment by pangweiwei** [comment]
你还可以参考LuaExtensionMethod.cpp这个文件，slua本身也extend了一些常用了非UFunction方法供lua使用。
