### ISSUE TITLE
UE4.24 版本 lua OnComponentBeginOverlap 碰撞对象找不到

### ISSUE THREAD

**Issue by gzbin7878at2016** [Tencent/sluaunreal#254]
请教下大佬，UE4.21~22 都没问题，但是升级到4.24 这个对象就为nil
attempt to index a nil value (field 'OnComponentBeginOverlap')
stack traceback:

这个对象的导入到lua，逻辑是在哪里做的？

**Comment by pangweiwei** [comment]
那要看一下 4.24是不是改名字了

**Comment by gzbin7878at2016** [comment]
Slua: Error: unsupport type MulticastSparseDelegateProperty to push
报了这个错误

**Comment by gzbin7878at2016** [comment]
能考虑支持下 UE4.24版本吗，项目需要用到424版本的渲染优化

**Comment by gzbin7878at2016** [comment]
参考 pushUMulticastInlineDelegateProperty添加就可以，谢谢

**Comment by baldSun** [comment]
我用的UE4.23也遇到了这个问题
