### ISSUE TITLE
请问这个是给lua用的委托吧？怎么触发委托事件呢？这几个成员函数都调不到诶

### ISSUE THREAD

**Issue by FTQZS** [Tencent/sluaunreal#256]
![图片](https://user-images.githubusercontent.com/31785663/70808555-dd4c0e00-1dfa-11ea-858f-55a0868e9c0e.png)

**Comment by pangweiwei** [comment]
触发委托是在c++代码里，当unreal的delegate被触发，会会掉到lua函数里。
