### ISSUE TITLE
这是加载在slua里的一些接口吧，为什么setTickFunction没了？

### ISSUE THREAD

**Issue by FTQZS** [Tencent/sluaunreal#257]
![图片](https://user-images.githubusercontent.com/31785663/70809643-2ac97a80-1dfd-11ea-948f-17ded53ad3a6.png)

用法不是slua.setTickFunction(函数)吗？还有这个看了你们实现，只能一个LuaState对应一个帧函数吗？出于什么考虑不能注册多个帧函数呢？

**Comment by pangweiwei** [comment]
之前的setTickFunction是用于内部的一个功能，后来找到了更合适的实现方法，就把那个函数去掉了，你如果有需要，可以加回去

**Comment by FTQZS** [comment]
也不是需要，就是把slua大体看了一遍，好奇而已，去掉了吗？在哪取除了？不仅是setTickFunction，getMicroseconds和getMiliseconds都没了。

**Comment by pangweiwei** [comment]
我刚才看了代码，你说的函数都存在呀
