### ISSUE TITLE
slua 支持导出智能提示吗

### ISSUE THREAD

**Issue by zh5243a** [Tencent/sluaunreal#262]
类似于unlua的UnLuaIntelliSense模块

UnLuaIntelliSense. 'Program' module to generate IntelliSense (symbols) of all UCLASS, UPROPERTY, UFUNCTION, USTRUCT, UENUM for a private IDE (which will be PUBLIC soon). It's disabled by default.

**Comment by pangweiwei** [comment]
这个功能我们做在VS插件里，用luapanda可以支持代码提示。

**Comment by pangweiwei** [comment]
我们不需要的插件层面上额外生成任何信息，仅仅是调试插件动态分析语法
