### ISSUE TITLE
lua中怎么调用C++中返回值用引用传回的接口？比如UGameplayStatics::GetAllActorsOfClass

### ISSUE THREAD

**Issue by FTQZS** [Tencent/sluaunreal#263]
![图片](https://user-images.githubusercontent.com/31785663/71401290-5c93da00-2664-11ea-8c70-7ad8fb9026ab.png)
![图片](https://user-images.githubusercontent.com/31785663/71401409-b7c5cc80-2664-11ea-89d5-8bc17d8370a6.png)
我这样写并不能获取到场景里的Actor

**Comment by pangweiwei** [comment]
这个函数在例子中有调用，你可以参考：
local arr=GameplayStatics.GetAllActorsOfClass(uactor,bpClass,nil)
