### ISSUE TITLE
lua为何不用源码形式放入插件？

### ISSUE THREAD

**Issue by xpc-yx** [Tencent/sluaunreal#265]
源码编译应该更方便跨平台处理

**Comment by pangweiwei** [comment]
最开始是放在插件代码里的，这样也方便调试，后来是因为UE的 IWYU编译模式导致lua的代码在跨平台编译时有问题，现在最新版有没有解决这个问题我也没有测试了，如果解决了，可以在放回来

**Comment by xpc-yx** [comment]
期待直接继承源码的版本

**Comment by xpc-yx** [comment]
感谢，期待直接集成源码的版本
