### ISSUE TITLE
拓展luaActor出错

### ISSUE THREAD

**Issue by hongshaowu** [Tencent/sluaunreal#272]
怎么拓展新的luaActor，例如luaAIController,单纯修改LuaActor.h和LuaBase.cpp会link2001，有哪些地方需要修改，或者能不能出一个教程或者文档

**Comment by pangweiwei** [comment]
你是如何修改的，报告的错误详细信息是啥

**Comment by hongshaowu** [comment]
通过在LuaActor.h 继承AIControler类，和其他的luaActor类似，报错link error 2001 未解析的外部符号加函数名,AIControler的所有函数
``UCLASS()
class SLUA_UNREAL_API ALuaAIController : public AAIController, public slua_Luabase, public ILuaTableObjectInterface {
	GENERATED_BODY()
		LUABASE_BODY(LuaAIController)
public:
	ALuaAIController(const FObjectInitializer& ObjectInitializer = FObjectInitializer::Get())
		: AAIController(ObjectInitializer)
	{
		PrimaryActorTick.bCanEverTick = true;
	}
public:
	// below UPROPERTY and UFUNCTION can't be put to macro LUABASE_BODY
	// so copy & paste them
	UPROPERTY(BlueprintReadOnly, EditAnywhere, Category = "slua")
		FString LuaFilePath;
	UPROPERTY(BlueprintReadOnly, EditAnywhere, Category = "slua")
		FString LuaStateName;
	UFUNCTION(BlueprintCallable, Category = "slua")
		FLuaBPVar CallLuaMember(FString FunctionName, const TArray<FLuaBPVar>& Args) {
		return callMember(FunctionName, Args);
	}
};``

**Comment by pangweiwei** [comment]
你需要添加 AIModule 到 PrivateDependencyModuleNames

```cs
PrivateDependencyModuleNames.AddRange(
            new string[]
            {
                "CoreUObject",
                "Engine",
                "Slate",
                "SlateCore",
                "UMG",
                "AIModule",
				// ... add private dependencies that you statically link with here ...	
			}
            );
```
