### ISSUE TITLE
REG_EXTENSION_METHOD_WITHTYPE(UDataTable, "FindRow", &UDataTable::FindRow, FTableRowBase* (UDataTable::*)(FName, const FString&, bool) const);编译失败

### ISSUE THREAD

**Issue by FTQZS** [Tencent/sluaunreal#275]
1>Module.slua_unreal.cpp.obj : error LNK2019: 无法解析的外部符号 "public: static struct slua::SimpleString __cdecl slua::TypeName<struct FTableRowBase,0>::value(void)" (?value@?$TypeName@UFTableRowBase@@$0A@@slua@@SA?AUSimpleString@2@XZ)，该符号在函数 "public: static int __cdecl slua::FunctionBind<struct FTableRowBase * (__cdecl*)(struct slua::lua_State *,void *,class FName &&,class FString const &,bool &&),&public: static struct FTableRowBase * __cdecl slua::LuaCppBinding<struct FTableRowBase * (__cdecl UDataTable::*)(class FName,class FString const &,bool)const ,&public: struct FTableRowBase * __cdecl UDataTable::FindRow<struct FTableRowBase>(class FName,class FString const &,bool)const ,1>::invoke(struct slua::lua_State *,void *,class FName &&,class FString const &,bool &&),2>::invoke(struct slua::lua_State *,void *)" (?invoke@?$FunctionBind@P6APEAUFTableRowBase@@PEAUlua_State@slua@@PEAX$$QEAVFName@@AEBVFString@@$$QEA_N@Z$1?invoke@?$LuaCppBinding@P8UDataTable@@EBAPEAUFTableRowBase@@VFName@@AEBVFString@@_N@Z$1??$FindRow@UFTableRowBase@@@1@QEBAPEAU2@012@Z$00@3@SAPEAU1@01234@Z$01@slua@@SAHPEAUlua_State@2@PEAX@Z) 中被引用
1>D:\Download\sluaunreal-master\sluaunreal-master\Plugins\slua_unreal\Binaries\Win64\UE4Editor-slua_unreal-0001-Win64-DebugGame.dll : fatal error LNK1120: 1 个无法解析的外部命令

**Comment by pangweiwei** [comment]
你还需要则slua namespace下增加一个类型推导提示：

DefTypeName(FTableRowBase);

参考sluautil.h的

```c++
	DefTypeName(FFloatRange);
	DefTypeName(FInt32RangeBound);
	DefTypeName(FInt32Range);
	DefTypeName(FFloatInterval);
	DefTypeName(FInt32Interval);
	DefTypeName(FPrimaryAssetType);
	DefTypeName(FPrimaryAssetId);
	DefTypeName(FActorComponentTickFunction);
	DefTypeName(FDateTime);
```

申明
