### ISSUE TITLE
slua目前还不支持行为树类吗？

### ISSUE THREAD

**Issue by FTQZS** [Tencent/sluaunreal#282]
并没有AIController、UBlackboardData、UBTService、UBTDecorator、UBTTaskNode等类的lua类，那么我是要自己扩展支持的类吗？

**Comment by pangweiwei** [comment]
slua的设计目标不包括某个具体类是否导出，我们提供了一个底层基础设施帮助你快速搞定你想扩展的蓝图类成为lua

**Comment by FTQZS** [comment]
那我如果想像使用ALuaActor一样，让lua的table继承C++类，可以仿ALuaActor也定义一个Lua用的类？

**Comment by hongshaowu** [comment]
请问题主解决了么，自己拓展遇到了一些问题

**Comment by zjhongxian** [comment]
请关注新版本使用wiki哦，虽然还在完善中，但已经标记处使用方式了。只需要在对应蓝图添加LuaOverrideInterface类，或者在C++继承里面添加ILuaOverriderInterface并实现它们的GetLuaFilePath函数即可达成
