### ISSUE TITLE
蓝图拓展LuaActor无法调用lua

### ISSUE THREAD

**Issue by xiaoerjason** [Tencent/sluaunreal#283]
在4.21版本下按照官方的教程，扩展蓝图Actor，已经选择好了LuaActor的父类，同时也绑定了lua文件，但是运行起来就是没有调用，无正常print，这是还有其他配置没有配置好吗？[https://github.com/Tencent/sluaunreal/wiki/LuaActor%E7%9A%84%E4%BD%BF%E7%94%A8](url)

**Comment by pangweiwei** [comment]
你直接跑附带的demo，看看LuaActor是否可以跑起来，

**Comment by xiaoerjason** [comment]
附带的demo可以跑起来。。是我漏了什么细节吗

**Comment by forget-js** [comment]
我也遇到这个问题了，请问你解决了吗？

**Comment by pangweiwei** [comment]
有啥错误报告吗？

**Comment by forget-js** [comment]
> 有啥错误报告吗？

感谢回复，已通过修改demo的方式正常使用。自己新建项目还未解决，大概是我漏了些步骤，我再研究研究。

**Comment by pangweiwei** [comment]
可能是忘记处理lua文件加载代理，导致找不到你自己的lua文件。
