### ISSUE TITLE
请问我在打包时  build configuration 选 shipping  后lua就没起作用这有可能是什么原因呢？

### ISSUE THREAD

**Issue by ArchmageMelon** [Tencent/sluaunreal#285]
之前打包用development是正常的，后来选了shipping就不行了，再选成development也不行
但是，编辑器play new window正常，这有可能是哪的原因呢？

**Comment by morirain** [comment]
有可能lua脚本没打包进去

**Comment by pangweiwei** [comment]
是的，你要把lua文件目录，添加到需要打包的列表里

**Comment by ArchmageMelon** [comment]
不好意思，这个打包列表是在哪里配置的呢？

**Comment by ArchmageMelon** [comment]
之前有在 packaging/additional non-asset directories to package 里加了lua，打包列表是指这个么？

**Comment by ArchmageMelon** [comment]
就是packaging的additional配置问题，已解决
