### ISSUE TITLE
怎么在Lua里为UUserWidget添加普通的SWidget控件呢？

### ISSUE THREAD

**Issue by FTQZS** [Tencent/sluaunreal#286]
在C++里有SNew和SAssignNew宏。比如创建一个SHorizontalBox之类的SWidget小控件，不知道lua里该怎么写，不是UMG那种提前拼好的界面，要动态创建添加。

**Comment by pangweiwei** [comment]
做一些extension方法导出，或者导出一些自定义方法支持你这种情况
参考cppbinding
