### ISSUE TITLE
UWorld方法扩展问题

### ISSUE THREAD

**Issue by gzbin7878at2016** [Tencent/sluaunreal#287]
hi 大佬:
请教下方法,谢谢.
想扩展OverlapMultiByProfile这个方法到Lua调用,我参考SpawnActor,但是编译不过.

bool OverlapMultiByProfile(TArray<struct FOverlapResult>& OutOverlaps, const FVector& Pos, const FQuat& Rot, FName ProfileName, const FCollisionShape& CollisionShape, const FCollisionQueryParams& Params = FCollisionQueryParams::DefaultQueryParam) const;
我翻译过来是
REG_EXTENSION_METHOD_WITHTYPE(UWorld, "OverlapMultiByProfile", &UWorld::OverlapMultiByProfile, bool (UWorld::*)(TArray<struct FOverlapResult>&, const FVector&, const FQuat&, FName , const FCollisionShape&, const FCollisionQueryParams&) const);

报错:
error C4239: nonstandard extension used: 'argument': conversion from 'TArray<FOverlapResult,FDefaultAllocator>' to 'TArray<FOverlapResult,FDefaultAllocator> &'
 note: A non-const reference may only be bound to an lvalue
note: while compiling class template member function 'T slua::FunctionBind<RET (__cdecl *)(slua::lua_State *,void *,TArray<FOverlapResult,FDefaultAllocator> &,const FVector &,const FQuat &,FName &&,const FCollisionShape &,const FCollisionQueryParams &),RET slua::LuaCppBinding<bool (__cdecl UWorld::* )(TArray<FOverlapResult,FDefaultAllocator> &,const FVector &,const FQuat &,FName,const FCollisionShape &,const FCollisionQueryParams &) const,{&UWorld::OverlapMultiByProfile,0},1>::invoke(slua::lua_State *,void *,TArray<FOverlapResult,FDefaultAllocator> &,const FVector &,const FQuat &,FName &&,const FCollisionShape &,const FCollisionQueryParams &),2>::Functor<I>::invoke(slua::lua_State *,void *)'

**Comment by pangweiwei** [comment]
TArray<FOverlapResult,FDefaultAllocator> 这个类型并没有导出

另外对于extension方法，建议简化参数传递形式。

**Comment by gzbin7878at2016** [comment]
好的,谢谢
