### ISSUE TITLE
大佬能麻烦帮忙看看报错是什么原因吗？

### ISSUE THREAD

**Issue by FTQZS** [Tencent/sluaunreal#288]
![图片](https://user-images.githubusercontent.com/31785663/76179475-00b60780-61f6-11ea-9161-2a4a24c5254a.png)
![图片](https://user-images.githubusercontent.com/31785663/76179552-41ae1c00-61f6-11ea-97c0-4520e7214e52.png)

Script Stack (0 frames):

Ensure condition failed: ud->ud == Object [File:F:/WorkArea/Project/client/Plugins/slua_unreal/Source/slua_unreal/Private/LuaState.cpp] [Line: 513] 

[2020.03.09-02.57.54:932][530]LogOutputDevice: Error: Ensure condition failed: ud->ud == Object [File:F:/WorkArea/Project/client/Plugins/slua_unreal/Source/slua_unreal/Private/LuaState.cpp] [Line: 513] 

[2020.03.09-02.57.54:933][530]LogStats:             FDebug::EnsureFailed -  0.001 s
UE4Editor-Win64-DebugGame.exe 已触发了一个断点。

**Comment by FTQZS** [comment]
C++这边的堆栈只有两处，再往上就是Lua调过来的，看Log，好像是Lua层销毁了一个C++对象，然后通知C++销毁，C++没找到还是怎么滴了吗？

**Comment by pangweiwei** [comment]
这个unlinkUobject是发生在uObject会ue回收（比如切换world），但是lua还在引用，而lua里保存的uobject并不是需要回收的UObject，这个断言就是确保两者必须是一个东西。

**Comment by Piscis-QJ** [comment]
刚想报，发现已经有了。。

研究下了。
应该是这样触发:
`
function actor:createActor()
        local newactor = world:SpawnActor(actorClass,pos,nil,nil)
        --do something...
        newactor:K2_DestroyActor()
end
`

这样，等gc的时候回触发。
虽然actor在同一方法里创建了，有马上销毁了，这个很奇怪。但断言就是这样产生的。

**Comment by FTQZS** [comment]
> 
> 
> 刚想报，发现已经有了。。
> 
> 研究下了。
> 我这里情况是这样触发:
> 
> ```
> function actor:createActor()
>         local newactor = world:SpawnActor(actorClass,pos,nil,nil)
>         --do something...
>         newactor:K2_DestroyActor()
> end
> ```
> 
> 这样，等gc的时候回触发。
> 虽然actor在同一方法里创建了，又马上销毁了。

是不能同一帧里生成销毁吗？

**Comment by Piscis-QJ** [comment]
具体也不是很清楚。目前猜测：
SpawnActor后返回的newactor应该自带GC
然后DestroyActor
lua gc 的时候，LuaObject::gcObject==>unlinkUobject
UE gc会触发LuaState::NotifyUObjectDeleted==>unlinkUobject

理论上在第二次unlinkUobject时候，会当object not push to lua处理，直接返回。
然而概率会出现在objRefs对应object还存在，导致ud->ud与object不同了。
所以在lua gc和UE gc之间发生了什么？还得继续查原因。

**Comment by Piscis-QJ** [comment]
```
GenericUserData* ud = *udptr;

// remove should put here avoid ud is invalid
// remove ref, Object must be an UObject in slua
objRefs.Remove(const_cast<UObject*>(Object));
```
问题好像找到了。
ud指向的内容可能已经是野数据了，通过objRefs.Remove后。

**Comment by pangweiwei** [comment]
我fix一下

**Comment by pangweiwei** [comment]
fix 了

**Comment by leeweo** [comment]
之前的fix并未找出崩溃的本质，不能真正解决问题
1. 造成这个崩溃的原因是，push到lua中的UObject对象对应的userdata，在gc的时候，由于CheckUDGC宏检查，由于UObject可能是无效的，直接返回了，并未调用接下来的removeRef方法。
2. lua调用了__gc元方法后，userdata的内存（NS_SLua::UserData<UObject*>）已经被回收了，这块内存随时都有可能被分配给其他对象，这时候LuaState的objRefs中UObject*对应的NS_SLua::UserData<UObject*>已经是脏数据了，在unlinkUObject的时候是不应该再访问它的字段，这也是ud->ud != Object的原因。
3. 彻底解决这个问题，修改可能不少，要同时处理好lua和ue4的垃圾回收，两者的先后顺序并不是确定的，至少仅仅只有一个objRefs应该是不够的。
