### ISSUE TITLE
LuaObject中checkUD模板疑问

### ISSUE THREAD

**Issue by crazytuzi** [Tencent/sluaunreal#290]
LuaObject中checkUD模板下使用luaL_getmetafield从元表中获取值，成功之后tostring，然后再执行lua_pop,正常流程没问题。可是如果luaL_getmetafield失败后，再去执行lua_pop，而luaL_getmetafield失败时什么也不会压栈，不就破坏了栈吗?
![Snipaste_2020-03-17_16-12-17](https://user-images.githubusercontent.com/28628663/76835482-26808380-686a-11ea-9ea9-31607b965dee.png)

**Comment by pangweiwei** [comment]
luaL_getmetafield 失败也会push一个nil的

**Comment by crazytuzi** [comment]
最初是在云风翻译的中文文档下看到的luaL_getmetafield失败不压栈，刚才去看了下lua-5.3.5源码，luaL_getmetafield先调用的lua_getmetatable去获取元表，而lua_getmetatable失败时也不进行压栈操作，那luaL_getmetafield也应该失败时不压栈吧，还是我哪里理解有问题，如果有的话，大佬指点下，谢谢。另外，QQ群申请同意一下呢，想和大家一起学习
![Snipaste_2020-03-18_11-56-59](https://user-images.githubusercontent.com/28628663/76924276-c8f34200-6910-11ea-93ec-e8e445fb8a85.png)

**Comment by pangweiwei** [comment]
嗯，我看了下代码，确实不push nil，我fix一下，谢谢指出。
