### ISSUE TITLE
关于ULuaDelegate泄露问题

### ISSUE THREAD

**Issue by Piscis-QJ** [Tencent/sluaunreal#293]
我有一个LuaUserWidgetA，它里面有一个UUserwidgetB蓝图控件。

```
function LuaUserWidgetA:Construct()
        self.suggestClickHandler = self.userWidgetB.buttonB.OnClicked:Add(luaCallBack(self.btnClick, self))
        ....
end
```
由于userWidgetB是一个纯蓝图weidget。然后注册button的onclick事件在lua后，suggestClickHandler就泄露了，又没法直接释放。
建议ULuaDelegate添加一个函数来释放自己。

```
function LuaUserWidgetA:Destruct()
        self.suggestClickHandler:ReleaseLua() --类似添加这样的函数释放ULuaDelegate
        --self.userWidgetB.buttonB.OnClicked:Clear() --这样写有点累，况且有可能userWidgetB.buttonB在之前被去除了？
        ...
end
```
self.userWidgetB不是lua，所以自己纯蓝图调用button->clear()又释放不了ULuadelegate。。。

**Comment by pangweiwei** [comment]
目前，释放的能力是有的：
self.userWidgetB.buttonB.OnClicked:Clear
self.userWidgetB.buttonB.OnClicked:Remove
都可以。

问题的核心是你感觉不方便
我们这里的实践的方法是有一个地方统一处理：
例如
eventhandle.add(self.btn,'Clicked',function() end) -- 里面封装事件添加、保存，支持mulitcast
eventhandle.add(self.btn2,'Clicked',function() end)
eventhandle.add(self.btn3,'Clicked',function() end)

eventhandle.clearall() --全部解除绑定并回收。
