### ISSUE TITLE
lua绑定的几个UI控件GC报错，求帮忙看看

### ISSUE THREAD

**Issue by FTQZS** [Tencent/sluaunreal#294]
LogOutputDevice: Error: === Handled ensure: ===
LogOutputDevice: Error: Ensure condition failed: !IsGarbageCollecting() [File:D:/Build/++UE4/Sync/Engine/Source/Runtime/UMG/Private/Slate/SObjectWidget.cpp] [Line: 43]
LogOutputDevice: Error: SObjectWidget for 'CharShowTaleView_C /Engine/Transient.UnrealEdEngine_0:IdleGameInstance_1.CharShowView_C_0.WidgetTree_0.CharShowTaleView' destroyed while collecting garbage.  This can lead to multiple GCs being required to cleanup the object.  Possible causes might be,
LogOutputDevice: Error: 1) ReleaseSlateResources not being implemented for the owner of this pointer.
LogOutputDevice: Error: 2) You may just be holding onto some slate pointers on an actor that don't get reset until the actor is Garbage Collected.  You should avoid doing this, and instead reset those references when the actor is Destroyed.
LogOutputDevice: Error: Stack: 
LogOutputDevice: Error: [Callstack] 0x00007ffadb96309e UE4Editor-UMG.dll!UnknownFunction []
LogOutputDevice: Error: [Callstack] 0x00007ffadb7d0746 UE4Editor-UMG.dll!UnknownFunction []
LogOutputDevice: Error: [Callstack] 0x00007ffb0279a29a UE4Editor-SlateCore.dll!UnknownFunction []
LogOutputDevice: Error: [Callstack] 0x00007ffadd849cdc UE4Editor-Slate.dll!UnknownFunction []
LogOutputDevice: Error: [Callstack] 0x00007ffadd83ff77 UE4Editor-Slate.dll!UnknownFunction []
LogOutputDevice: Error: [Callstack] 0x00007ffb0279a29a UE4Editor-SlateCore.dll!UnknownFunction []
LogOutputDevice: Error: [Callstack] 0x00007ffadd8cc94e UE4Editor-Slate.dll!UnknownFunction []
LogOutputDevice: Error: [Callstack] 0x00007ffadd8bdb58 UE4Editor-Slate.dll!UnknownFunction []
LogOutputDevice: Error: [Callstack] 0x00007ffadd8c18a9 UE4Editor-Slate.dll!UnknownFunction []
LogOutputDevice: Error: [Callstack] 0x00007ffb0271dac4 UE4Editor-SlateCore.dll!UnknownFunction []
LogOutputDevice: Error: [Callstack] 0x00007ffadb80378c UE4Editor-UMG.dll!UnknownFunction []
LogOutputDevice: Error: [Callstack] 0x00007ffb0318b7c3 UE4Editor-CoreUObject.dll!UnknownFunction []
LogOutputDevice: Error: [Callstack] 0x00007ffb03166aec UE4Editor-CoreUObject.dll!UnknownFunction []
LogOutputDevice: Error: [Callstack] 0x00007ffb0310f8c2 UE4Editor-CoreUObject.dll!UnknownFunction []
LogOutputDevice: Error: [Callstack] 0x00007ffb0310ea0a UE4Editor-CoreUObject.dll!UnknownFunction []
LogOutputDevice: Error: [Callstack] 0x00007ffab7f1b7ff UE4Editor-UnrealEd.dll!UnknownFunction []
LogOutputDevice: Error: [Callstack] 0x00007ffab7a0ef43 UE4Editor-UnrealEd.dll!UnknownFunction []
LogOutputDevice: Error: [Callstack] 0x00007ffab8265296 UE4Editor-UnrealEd.dll!UnknownFunction []
LogOutputDevice: Error: [Callstack] 0x00007ff60bd47b0a UE4Editor-Win64-DebugGame.exe!UnknownFunction []
LogOutputDevice: Error: [Callstack] 0x00007ff60bd5a91c UE4Editor-Win64-DebugGame.exe!UnknownFunction []
LogOutputDevice: Error: [Callstack] 0x00007ff60bd5a9fa UE4Editor-Win64-DebugGame.exe!UnknownFunction []
LogOutputDevice: Error: [Callstack] 0x00007ff60bd6b93c UE4Editor-Win64-DebugGame.exe!UnknownFunction []
LogOutputDevice: Error: [Callstack] 0x00007ff60bd6e62e UE4Editor-Win64-DebugGame.exe!UnknownFunction []
LogOutputDevice: Error: [Callstack] 0x00007ffb0bd54034 KERNEL32.DLL!UnknownFunction []
LogOutputDevice: Error: [Callstack] 0x00007ffb0de03691 ntdll.dll!UnknownFunction []

**Comment by pangweiwei** [comment]
看不出和slua有任何关系，你可以提交详细重现步骤
