### ISSUE TITLE
您好，目前这边遇到一个在Lua重写方法里面定义self 变量卡顿问题，可以帮忙看一下是为什么吗？

### ISSUE THREAD

**Issue by 1538360240** [Tencent/sluaunreal#295]
我在UserWidget的lua文件的Construct方法里 比如初始化一个sefl.aa = 0, 多个变量出现卡顿现象，个人怀疑是不是因为会去到蓝图中查找的原因，我放到一个自己写的lua初始化方法里去初始化卡顿现象消失，但是这种使用方式其他地方也很多，甚至有些类似方式可能都会带来性能问题，烦请解答。

**Comment by pangweiwei** [comment]
self.xxx 是支持直接修改UProperty和蓝图属性的，所以
sefl.aa 的这个写法，是先去查找对应UProperty，蓝图属性等，如果不存在，才会当做一个普通aa数据放在self对应的luatable里，所以建议你这样来组织自己的数据
self.data = {}
self.data.aa =0
self.data.bb= 1

避免反复对 self绑定的c++，蓝图对象访问，或者使用rawset

rawset(self,"aa",0)
