### ISSUE TITLE
内存可能被写乱的问题

### ISSUE THREAD

**Issue by leeweo** [Tencent/sluaunreal#300]
详细问题可参考这里：
1. https://github.com/Tencent/sluaunreal/issues/288
2. https://github.com/Tencent/sluaunreal/issues/288#issuecomment-611936242

补充一个比较方便的测试方法：
1.  创建出一个界面，只有一个Button即可
2.  Button的OnClicked事件中，如果全局变量是nil，SpanwActor赋值给这个全局变量，否则DestroyActor销毁之前的Actor，重新再SpanwActor赋值给全局变量，原来的Actor会处于PendingKill状态
3. 根据SLua的实现，之前的Actor对应的userdata，会很快调用__gc元方法，但是CheckUDGC会由于PendingKill状态而返回，不会调用removeRef方法。
4. 此时LuaState中的objRefs保存的userdata内存就不应该再使用了，因为这块内存有可能会被系统重新分配给其他对象。

建议解决方式：
1. 现在有objRefs表，从UObject*映射到userdata，可以再增加一个userdata到UObject*的映射表。
2. lua的gc元方法里，同时移除两个表的映射关系
3. ue4的gc里，移除objRefs映射关系，同时修改新的映射表，设置HADFREE标记

**Comment by pangweiwei** [comment]
fix后的代码是

			else if (isUObjectValid(ptr->ud) || !checkfree)
				return ptr->ud;

即便PendingKill的object也会返回它对应的指针，因为checkfree为false在CheckUDGC，这样就会调用removeRef。

**Comment by pangweiwei** [comment]
按照提供的测试方法，在最新fix后的代码跑，是没有崩溃的。

**Comment by pangweiwei** [comment]
```lua
local gg = nil
local bpClass = slua.loadClass("/Game/LuaBpActor.LuaBpActor")
local handler = btn2.OnClicked:Add(function() 

	if not gg then
		local p = FVector(math.random(-100,100),math.random(-100,100),0)
		gg = gworld:SpawnActor(bpClass,p,nil,nil)
	else
		gg:K2_DestroyActor()
		local p = FVector(math.random(-100,100),math.random(-100,100),0)
		gg = gworld:SpawnActor(bpClass,p,nil,nil)
	end

end);
```

测试代码如上。

**Comment by leeweo** [comment]
我们使用的代码之前没有更新到最新的版本，崩溃几乎是必然的。
更新到最新之后，是不会崩溃了，但是单纯从代码分析，还是可能出现内存被写乱的问题。
在gcObject方法中，如果CheckUDGC返回了，这时候lua的gc有可能已经回收了UserData<UObject*>的内存，但是在LuaState的objRefs里面仍然保存了指向这块内存的指针，在ue4的gc调用unlinkUObject的时候，有可能会获取或设置ud的flag属性，这时候仍然可能会出问题吧。
如果不能保证gcObject的时候removeRef能被调用，内存读写混乱还是有可能出现的。

**Comment by pangweiwei** [comment]
现在的修改方案就是保证gcOBJECT不会返回呀，这里你有疑问吗？最后一个参数是false，不会因为ispendding 返回。发自我的华为手机-------- 原始邮件 --------发件人： chenyunlei <notifications@github.com>日期： 2020年4月11日周六 下午4:59收件人： Tencent/sluaunreal <sluaunreal@noreply.github.com>抄送： siney <sineysan@163.com>, Comment <comment@noreply.github.com>主    题： Re: [Tencent/sluaunreal] 内存可能被写乱的问题 (#300)
我们使用的代码之前没有更新到最新的版本，崩溃几乎是必然的。
更新到最新之后，是不会崩溃了，但是单纯从代码分析，还是可能出现内存被写乱的问题。
在gcObject方法中，如果CheckUDGC返回了，这时候lua的gc有可能已经回收了UserData<UObject*>的内存，但是在LuaState的objRefs里面仍然保存了指向这块内存的指针，在ue4的gc调用unlinkUObject的时候，有可能会获取或设置ud的flag属性，这时候仍然可能会出问题吧。
如果不能保证gcObject的时候removeRef能被调用，内存读写混乱还是有可能出现的。

**Comment by leeweo** [comment]
也就是现在可以保证CheckUDGC宏在gcObject函数里，一定不会直接return对吧，虽然从代码形式上看有一个return语句，如果有这个保证的话，那就没有什么疑问了。

**Comment by pangweiwei** [comment]
嗯，我可以加一个断言，之前会可能return，现在是不可能想我加一个断言吧。发自我的华为手机

**Comment by leeweo** [comment]
好的，感谢回复讨论！！！
