### ISSUE TITLE
Lua调用RPC失败,会在客户端执行

### ISSUE THREAD

**Issue by crazytuzi** [Tencent/sluaunreal#301]
引擎版本4.24.3
slua版本为当前最新版本
调试发现,调用RPC的时候,如果是一个RPC函数,会单独调用一个callRpc函数
![Snipaste_2020-04-20_16-06-00](https://user-images.githubusercontent.com/28628663/79728982-5ddac800-8321-11ea-980f-b0f6429aaca9.png)
结合版本提交记录分析了一下,大概是IOS平台下,TArray会crash,所以单独处理了一下。
可是,当我在windows上测试的时候发现,会直接在调用RPC时,会在UObject::ProcessEvent提前就中止，并沒有进入callRpc那部分代码
![Snipaste_2020-04-20_16-13-04](https://user-images.githubusercontent.com/28628663/79729281-d772b600-8321-11ea-8000-3fb72c6eb9ec.png)
并未在ios上测试过,目前我在windows上测试直接改成了调用ProcessEvent,能够成功调用

**Comment by pangweiwei** [comment]
如果问题解决，麻烦关闭一下
@crazytuzi

**Comment by jayfenny** [comment]
LuaObject.cpp,  函数 LuaObject::callRpc 的616~617行是不是有点问题？注释写的是拷贝参数到Local里，但Param取出来之后，调用的却是InitializeValue（我们碰到的bug是会被清空）？取出来的Param没用到？

614           } else {
615                // copy the result of the expression for this parameter into the appropriate part of the local variable space
616                uint8* Param = Property->ContainerPtrToValuePtr<uint8>(NewStack.Locals);
617                Property->InitializeValue_InContainer(NewStack.Locals);
618           }
