### ISSUE TITLE
android 项目 Lua_gc 异常

### ISSUE THREAD

**Issue by gzbin7878at2016** [Tencent/sluaunreal#302]
**Describe the bug**
hi 大佬: 
    我们在开发android游戏项目时,容易报gc异常,能帮我分析下吗,谢谢

**Version**
tag v1.1版本

**To Reproduce**
游戏运行一段时间,有很大概率触发这个异常

**Crash**
`Assertion failed: OffsetFromBase >= 0 [File:D:\Build\++UE4\Sync\Engine\Source\Runtime\Core\Private\HAL\MallocBinned.cpp] [Line: 1080] 
Error: === Critical error: ===
Error: 
Error: Assertion failed: OffsetFromBase >= 0 [File:D:\Build\++UE4\Sync\Engine\Source\Runtime\Core\Private\HAL\MallocBinned.cpp] [Line: 1080] 
Error: 
Error: [Callstack] 0x00000000BCF4BFF4 (0x0000000003A2FFF4) libUE4.so!FDebug::CheckVerifyFailedImpl(char const*, char const*, int, char16_t const*, ...)  []
Error: [Callstack] 0x00000000C0F62CAC (0x0000000007A46CAC) libUE4.so!void FDebug::CheckVerifyFailed<char16_t [1]>(char const*, char const*, int, char16_t const (&) [1])  []
Error: [Callstack] 0x00000000BCE1EF80 (0x0000000003902F80) libUE4.so!FMallocBinned::GetAllocationSize(void*, unsigned int&)  []
Error: [Callstack] 0x00000000BCE7776C (0x000000000395B76C) libUE4.so!FMallocPoisonProxy::Realloc(void*, unsigned int, unsigned int)  []
Error: [Callstack] 0x00000000BCE3ED9C (0x0000000003922D9C) libUE4.so!FMemory::Realloc(void*, unsigned int, unsigned int)  []
Error: [Callstack] 0x00000000BC7337B4 (0x00000000032177B4) libUE4.so!FScriptArray::ResizeTo(int, int)  []
Error: [Callstack] 0x00000000BC717E88 (0x00000000031FBE88) libUE4.so!slua::LuaArray::~LuaArray()  []
Error: [Callstack] 0x00000000BC717FF0 (0x00000000031FBFF0) libUE4.so!slua::LuaArray::~LuaArray()  []
Error: [Callstack] 0x00000000BC718C50 (0x00000000031FCC50) libUE4.so!slua::LuaArray::gc(slua::lua_State*)  []
Error: [Callstack] 0x00000000BC6E5B24 (0x00000000031C9B24) libUE4.so!slua::lua_gc(slua::lua_State*, int, int)  []
Error: [Callstack] 0x00000000BC747788 (0x000000000322B788) libUE4.so!slua::LuaState::Tick(float)  []
Error: [Callstack] 0x00000000BF39E144 (0x0000000005E82144) libUE4.so!FTickableGameObject::TickObjects(UWorld*, int, bool, float)  []
Error: [Callstack] 0x00000000BF20F970 (0x0000000005CF3970) libUE4.so!UGameEngine::Tick(float, bool)  []
Error: [Callstack] 0x00000000BC6B82D8 (0x000000000319C2D8) libUE4.so!FEngineLoop::Tick()  []
Error: [Callstack] 0x00000000BC6AF77C (0x000000000319377C) libUE4.so!AndroidMain(android_app*)  []
Error: [Callstack] 0x00000000BC6BE63C (0x00000000031A263C) libUE4.so!android_main()  []`

**Desktop (please complete the following information):**
 - OS: [Android]
 - hw glass vr

**Comment by pangweiwei** [comment]
我感觉你升级到最新版本，应该可以解决问题

**Comment by gzbin7878at2016** [comment]
能具体指出什么原因吗?替换版本,工程量有点大,谢谢

**Comment by gzbin7878at2016** [comment]
是 tag 1.3 
fix invalid access of LuaArray and LuaMap 这个吗?

**Comment by gzbin7878at2016** [comment]
好的,我试下新版本,谢谢

**Comment by pangweiwei** [comment]
应该是1.2 的 fix LuaArray & LuaMap crash on GC
