### ISSUE TITLE
什么时候支持4.25版本？

### ISSUE THREAD

**Issue by ttaw** [Tencent/sluaunreal#304]
4.25里把UProperty改为FProperty了，导致现在的代码不能用了。什么时候能升级完成呢？

**Comment by pangweiwei** [comment]
近期开一个分支 支持 4.25

**Comment by zorofee** [comment]
你好，。请问4.25分支合并到master了吗？还是要用for_4.25那个分支？

**Comment by pangweiwei** [comment]
now 4.25 is beta
