### ISSUE TITLE
读取Luac问题

### ISSUE THREAD

**Issue by keltonxian** [Tencent/sluaunreal#313]
pc上用lua5.3.4编译lua成luac文件，用lua.exe能正常读取，但ue4.24引擎读取不出来。
提示
Slua: Error: t.lua:1: attempt to index a nil value
stack traceback:
	t.lua:1: in main chunk
请问如何正确读取luac文件呢？

**Comment by keltonxian** [comment]
再测试了下，是能读取，例如lua文件中在第三行写一句print，然后报错会定位到第三行，错误内容如之前描述。是引擎中对lua的方法做了什么处理吗？

**Comment by keltonxian** [comment]
是引擎中用的版本跟源码版本的opcode顺序不一致，用引擎中的来编译出编译器从而生成luac就行。

**Comment by zxws007** [comment]
请教一下 怎么编出slua的 dll

**Comment by zxws007** [comment]
@keltonxian
