### ISSUE TITLE
Run the demo in 4.25 & Crash

### ISSUE THREAD

**Issue by franklzt** [Tencent/sluaunreal#314]
Run the demo in 4.25 and then crash. Here is the Log:

LoginId:c6c43fe640bef403385215be307a7d35
EpicAccountId:ba507d99805b47c4b02f780b459658b1

Fatal error: [File:D:/Build/++UE4+Licensee/Sync/Engine/Source/Runtime/CoreUObject/Private/UObject/GarbageCollection.cpp] [Line: 929] Invalid object in GC: 0x000001f22c52fec0, ReferencingObject: NULL, ReferencingProperty: NULL

UE4Editor_CoreUObject!FGCCollector<1,0>::HandleObjectReference() [D:\Build\++UE4+Licensee\Sync\Engine\Source\Runtime\CoreUObject\Private\UObject\GarbageCollection.cpp:938]
UE4Editor_slua_unreal!slua::LuaArray::AddReferencedObjects() [E:\TestProject\sluaunreal-for_4.25\Plugins\slua_unreal\Source\slua_unreal\Private\LuaArray.cpp:95]
UE4Editor_CoreUObject!UGCObjectReferencer::AddReferencedObjects() [D:\Build\++UE4+Licensee\Sync\Engine\Source\Runtime\CoreUObject\Private\Misc\GCObjectReferencer.cpp:27]
UE4Editor_CoreUObject!TFastReferenceCollector<1,FGCReferenceProcessor<1,0>,FGCCollector<1,0>,FGCArrayPool,0,1>::ProcessObjectArray() [D:\Build\++UE4+Licensee\Sync\Engine\Source\Runtime\CoreUObject\Public\UObject\FastReferenceCollector.h:635]
UE4Editor_CoreUObject!TFastReferenceCollector<1,FGCReferenceProcessor<1,0>,FGCCollector<1,0>,FGCArrayPool,0,1>::FCollectorTaskQueue::DoTask() [D:\Build\++UE4+Licensee\Sync\Engine\Source\Runtime\CoreUObject\Public\UObject\FastReferenceCollector.h:383]
UE4Editor_CoreUObject!TGraphTask<TFastReferenceCollector<1,FGCReferenceProcessor<1,0>,FGCCollector<1,0>,FGCArrayPool,0,1>::FCollectorTaskProcessorTask>::ExecuteTask() [D:\Build\++UE4+Licensee\Sync\Engine\Source\Runtime\Core\Public\Async\TaskGraphInterfaces.h:849]
UE4Editor_Core!FTaskThreadAnyThread::ProcessTasks() [D:\Build\++UE4+Licensee\Sync\Engine\Source\Runtime\Core\Private\Async\TaskGraph.cpp:1039]
UE4Editor_Core!FTaskThreadAnyThread::ProcessTasksUntilQuit() [D:\Build\++UE4+Licensee\Sync\Engine\Source\Runtime\Core\Private\Async\TaskGraph.cpp:863]
UE4Editor_Core!FTaskThreadAnyThread::Run() [D:\Build\++UE4+Licensee\Sync\Engine\Source\Runtime\Core\Private\Async\TaskGraph.cpp:940]
UE4Editor_Core!FRunnableThreadWin::Run() [D:\Build\++UE4+Licensee\Sync\Engine\Source\Runtime\Core\Private\Windows\WindowsRunnableThread.cpp:86]

**Comment by pangweiwei** [comment]
sluaunreal doesn't support UE4.25 currently.
I will support it ASAP, branch for 4.25 is currently under development.

**Comment by pangweiwei** [comment]
now 4.25 is beta
