### ISSUE TITLE
4.25分支可以启动编辑器，运行崩溃。master 分支ue4.24无法编译运行进入编辑器

### ISSUE THREAD

**Issue by TerstGitHub** [Tencent/sluaunreal#316]
**Describe the bug**

**Version**
What version of slua you used?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Crash**
If crashed, attach traceback information.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows macOS iOS Android]
 - Other information about your environment.

**Additional context**

**Comment by pangweiwei** [comment]
ue4.24无法编译运行进入编辑器

报告什么错误？

**Comment by pangweiwei** [comment]
另外你可以尝试直接使用release的发布版，不要直接从master分支拉取。

**Comment by pangweiwei** [comment]
4.25 开发中。
