### ISSUE TITLE
返回指针类型到Lua时，会导致指针被gc掉，但未从objRefs中移除，导致ensure失败，甚至会导致Tick中Lua的gc失败

### ISSUE THREAD

**Issue by crazytuzi** [Tencent/sluaunreal#318]
![Snipaste_2020-06-04_21-45-33](https://user-images.githubusercontent.com/28628663/83764872-0e701180-a6ad-11ea-9252-21f3115c1e42.png)
问题的原因应该是这个地方，应该是UObject才对，如果是UClass，会导致testudata模板中，由于匹配的模板是Class，转换userdata失败
![QQ图片20200604215008](https://user-images.githubusercontent.com/28628663/83765243-850d0f00-a6ad-11ea-987c-287515e49411.jpg)
![QQ图片20200604215121](https://user-images.githubusercontent.com/28628663/83765266-8c341d00-a6ad-11ea-9794-1d0254f29e26.png)

**Comment by pangweiwei** [comment]
感谢反馈，已经fix。
