### ISSUE TITLE
请问4.24应该使用哪个分支？

### ISSUE THREAD

**Issue by forget-js** [Tencent/sluaunreal#323]
我在生成解决方案的时候，报错：
无法打开包括文件: “ModuleManager.h”: No such file or directory	
无法打开包括文件: “Margin.h”: No such file or directory

**Comment by pangweiwei** [comment]
请问那个文件报告这样的错误？

**Comment by forget-js** [comment]
> 请问那个文件报告这样的错误？

首先，我使用4.24新建了一个空的C++项目，接着把官方demo中的Plugins目录和Tools目录复制到新项目，安装文档中的描述，修改了build.cs文件，生成解决方案时报错。详细报错信息如下：
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	C1083	无法打开包括文件: “ModuleManager.h”: No such file or directory	ChickBallLua	E:\Unreal Project\ChickBallLuaDemo\ChickBallLua\Plugins\slua_unreal\Source\slua_profile\Public\slua_profile.h	19	
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	C1083	无法打开包括文件: “ModuleManager.h”: No such file or directory	ChickBallLua	E:\Unreal Project\ChickBallLuaDemo\ChickBallLua\Plugins\lua_wrapper\Source\lua_wrapper\Public\lua_wrapper.h	6

**Comment by pangweiwei** [comment]
我下载一个4.24的版本测试一下

**Comment by forget-js** [comment]
感谢，期待你的结果！

**Comment by forget-js** [comment]
另外想请教一个问题，4.21找不到编译器，让我安装vs2017，然而我已经安装了。我尝试全部卸载Epic和引擎再重新安装，以及重装vs2017，都没能解决，请问您是否知道如何解决此问题呢？感谢~

**Comment by clime57** [comment]
VS2017安装到C盘试试，或者再装个VS2015

**Comment by forget-js** [comment]
> VS2017安装到C盘试试，或者再装个VS2015

vs2017是在C盘的，我试试看安装VS2015

**Comment by pangweiwei** [comment]
使用master分支。

**Comment by forget-js** [comment]
我用的就是从Epic Games Launcher上面下载的4.24.3，刚刚再次使用vs2019和master分支试了一下，还是会有报错：
LuaTest/Plugins/slua_unreal/Source/slua_unreal/Private/LuaBase.cpp(16): fatal error C1083: 无法打开包括文件: “Script.h”: No such file or directory
LuaTest\Plugins\slua_unreal\Source\slua_profile\Public\slua_profile.h(18): fatal error C1083: 无法打开包括文件: “ModuleManager.h”: No such file or directory
LuaTest\Plugins\lua_wrapper\Source\lua_wrapper\Public\lua_wrapper.h(6): fatal error C1083: 无法打开包括文件: “ModuleManager.h”: No such file or directory
我使用4.23的话，都可以正常使用。不知道是什么地方有问题。

**Comment by forget-js** [comment]
> 我用的就是从Epic Games Launcher上面下载的4.24.3，刚刚再次使用vs2019和master分支试了一下，还是会有报错：
> LuaTest/Plugins/slua_unreal/Source/slua_unreal/Private/LuaBase.cpp(16): fatal error C1083: 无法打开包括文件: “Script.h”: No such file or directory
> LuaTest\Plugins\slua_unreal\Source\slua_profile\Public\slua_profile.h(18): fatal error C1083: 无法打开包括文件: “ModuleManager.h”: No such file or directory
> LuaTest\Plugins\lua_wrapper\Source\lua_wrapper\Public\lua_wrapper.h(6): fatal error C1083: 无法打开包括文件: “ModuleManager.h”: No such file or directory
> 我使用4.23的话，都可以正常使用。不知道是什么地方有问题。

刚刚又再次尝试了一下，使用vs2017也是同样报错。
完全一样的步骤，4.23就可以，4.24就不行。
会是什么原因呢

**Comment by Weilin1992** [comment]
相同的问题，有结论了吗

**Comment by forget-js** [comment]
> 相同的问题，有结论了吗

还没有呢~

**Comment by pangweiwei** [comment]
你们是用2019吗？我亲自测试了2019没有问题

**Comment by Weilin1992** [comment]
> 你们是用2019吗？我亲自测试了2019没有问题

我用的是2017 ue4.25.1 epic安装的版本

**Comment by Weilin1992** [comment]
> 你们是用2019吗？我亲自测试了2019没有问题

安装了一个2019 也有这个问题

**Comment by Weilin1992** [comment]
切换到for_4.25 分支,在vs2017和2019下，自带的democpp.uproject   均可正常编过，将 plugin下面两个目录复制到 epic安装版 4.25.1 新建的项目 ，并且按照说明更改 build.cs 就会报错

**Comment by Weilin1992** [comment]
https://github.com/googleforgames/agones/issues/1318  应该是这个问题

**Comment by Paccelerator** [comment]
> 切换到for_4.25 分支,在vs2017和2019下，自带的democpp.uproject 均可正常编过，将 plugin下面两个目录复制到 epic安装版 4.25.1 新建的项目 ，并且按照说明更改 build.cs 就会报错

你看看2个.Target.cs 文件是不是和官方demo一样。

**Comment by frank28** [comment]
> [googleforgames/agones#1318](https://github.com/googleforgames/agones/issues/1318) 应该是这个问题

是的，就是合格`BuildSettingsVersion.V2`的问题。从4.25创建的新工程，默认是有这一句，注释掉即可解决。
在设置为`BuildSettingsVersion.V2`时，从.uproject生成的vs工程中，只会添加比如`Core`一级的include路径，而不会像之前添加比如`Core\Public\Modules`这样的额外路径，导致编译报错。

参考其它项目以及UE自己的代码，正确的应该是修改头文件，比如
`#include "ModuleManager.h"`
应修改为
`#include "Modules/ModuleManager.h"`

这样能保证在`BuildSettingsVersion.V2`时代码正确编译。
