### ISSUE TITLE
求问尝试把lua以lib的形式调用转换为源代码导入的形式，luasocket link失败的原因是啥

### ISSUE THREAD

**Issue by quarantinefile** [Tencent/sluaunreal#327]
这个问题搞了好久了，lua的link没有问题，luasocket总是提醒找不到符号

Error	LNK2019	unresolved external symbol "int __cdecl slua::luaopen_socket_core(struct slua::lua_State *)" (?luaopen_socket_core@slua@@YAHPEAUlua_State@1@@Z) referenced in function "void __cdecl slua::LuaSocket::init(struct slua::lua_State *)" (?init@LuaSocket@slua@@YAXPEAUlua_State@2@@Z)

**Comment by pangweiwei** [comment]
你的luasocket的代码来源于哪里？
