### ISSUE TITLE
把lua文件编译成luac加载报错

### ISSUE THREAD

**Issue by zengdelang** [Tencent/sluaunreal#329]
把lua文件编译成luac加载报错，提示Entry.luac: size_t size mismatch in precompiled chunk，Luac程序是从lua源码中luac.c改造编译的用的插件Lua库编译，使用了Win32和Win64编译出来的luac都无法加载，要怎样解决这个问题？

**Comment by keltonxian** [comment]
你用引擎中的lua文件来生成一个luac吧，因为引擎中的改过size和opcode顺序的

**Comment by pangweiwei** [comment]
是的。

**Comment by GAnnie** [comment]
Android版本的库文件怎么打？在Window下使用gitbash运行make_android.sh报错，如下
https://github.com/Tencent/sluaunreal/issues/471
