### ISSUE TITLE
1.想问一下在lua里怎么用类似蓝图的cast的功能，或许只要一个isType接口？ 2.在lua里能用蓝图类似Delay接口吗？

### ISSUE THREAD

**Issue by ZuoEr** [Tencent/sluaunreal#34]

**Comment by pangweiwei** [comment]
不明白你问什么

**Comment by ZuoEr** [comment]
1.就是在蓝图里是可以用cast判断对象的类型的，在lua里应该调用哪个方法判断类型？
2.lua里能用蓝图的Delay接口吗？

**Comment by ZuoEr** [comment]
2.lua里实现蓝图的Delay接口应该怎么做？

**Comment by ZuoEr** [comment]
大佬求解答呀，感觉应该建一个qq群套路会更高效。

**Comment by pangweiwei** [comment]
有qq群15647305

**Comment by pangweiwei** [comment]
你需要用lua的思考方式来使用，而不是把blueprint用lua写。

**Comment by ZuoEr** [comment]
嗯，但是类型判断的接口还是要有的吧？lua里用什么方法判断ue的对象类型呢？

**Comment by pangweiwei** [comment]
太多方法了，比如getclass()->getname

**Comment by ZuoEr** [comment]
多谢解答，我知道了，在C++导出这样一个方法给lua就可以了哈，可以把这个issue关闭了哈，谢谢
