### ISSUE TITLE
双击democpp.uproject，报错“打开地图文件失败”

### ISSUE THREAD

**Issue by roundsheep** [Tencent/sluaunreal#340]
直接双击democpp.uproject，报错：

打开地图文件失败。 这可能是因为该地图时使用较新版本的引擎保存的。点确定后场景是黑的。

sluaunreal版本1.3.2和master都有这个问题，unreal版本4.21.2

**Comment by pangweiwei** [comment]
地图文件的数据是新版unreal的，老版本不支持了，建议你升级unreal版本到24

**Comment by pangweiwei** [comment]
或者你可以打开4.18的地图数据
