### ISSUE TITLE
push到lua的UObject在UE端被gc，但userdata的flag没有标记UD_HADFREE，再次访问野指针崩溃。

### ISSUE THREAD

**Issue by ShuraLiu** [Tencent/sluaunreal#352]
大概从1个半月前，就一直被这个bug困扰，一直没有找到稳定复现的方式。崩溃堆栈的截图如下

> std::__1::enable_if<(std::is_base_of<UObject, UClass>::value) && (!(std::is_same<UObject, UClass>::value)), UClass*>::type slua::LuaObject::testudata<UClass>(slua::lua_State*, int, bool) + 1152
1 std::__1::enable_if<(std::is_base_of<UObject, UClass>::value) && (!(std::is_same<UObject, UClass>::value)), UClass*>::type slua::LuaObject::testudata<UClass>(slua::lua_State*, int, bool) + 4136157135018918980
2 UClass* slua::LuaObject::checkUD<UClass>(slua::lua_State*, int, bool) + 60
3 slua::checkUClassProperty(slua::lua_State*, UProperty*, unsigned char*, int) + 52
4 slua::fillParamFromState(slua::lua_State*, UProperty*, unsigned char*, int) + 104
5 slua::LuaObject::fillParam(slua::lua_State*, int, UFunction*, unsigned char*) + 252
6 slua::ufuncClosure(slua::lua_State*) + 256

症状就是抛到lua端的UObject在UE端已经被释放了，但UD_HADFREE没有被正确标记，导致testudata时直接调用isUObjectValid(ptr->ud)野指针，但为什么会没有正确标记UD_HADFREE我们这完全没有头绪，反复检查都没找出原因。求各路大佬看一看有没有什么思路。

**Comment by ShuraLiu** [comment]
这个和#346不是一个问题，在我们升级slua之前就有了，升级前的版本大约是今年3月份左右的版本

**Comment by pangweiwei** [comment]
你看看 这个修复
https://github.com/Tencent/sluaunreal/issues/351

**Comment by ShuraLiu** [comment]
351和346是同一个问题，和这个issue的问题不太一样。这个issue我们这在6月份的时候出现的

**Comment by pangweiwei** [comment]
我今天碰巧遇到了pubg的同事问了这个问题，他们fix了这个问题，但是没有pr，我拜托他们明天pr。

**Comment by ShuraLiu** [comment]
哇，太棒了~感谢 @pangweiwei
