### ISSUE TITLE
isValid 判断UE4对象是否释放错误

### ISSUE THREAD

**Issue by gzbin7878at2016** [Tencent/sluaunreal#353]
**Describe the bug**
slua.isValid(actor.__cppinst) 提示错误
 bad argument #1 to 'isValid' (userdata expected, got light userdata)

**Version**
1.3.2

**To Reproduce**
我之前使用 1.1.0 版本,这个接口没问题,升级到1.3.2会报这个错误

**Crash**
bad argument #1 to 'isValid' (userdata expected, got light userdata)

**Desktop (please complete the following information):**
 - OS: Windows10

**Comment by gzbin7878at2016** [comment]
LuaBpActor.lua
`-- override event from blueprint
function actor:ReceiveBeginPlay()
    self.bCanEverTick = true
    -- set bCanBeDamaged property in parent
    self.bCanBeDamaged = false
    print("Error: bpactor:ReceiveBeginPlay actor=", actor)
    print("Error: bpactor:ReceiveBeginPlay __cppinst=", actor.__cppinst)
    local tt = slua.isValid(actor.__cppinst)
    print("Error: bpactor:ReceiveBeginPlay tt=", tt)
end
`

**Comment by gzbin7878at2016** [comment]
LuaBpActor.lua
`
-- override event from blueprint
function actor:ReceiveBeginPlay()
    self.bCanEverTick = true
    -- set bCanBeDamaged property in parent
    self.bCanBeDamaged = false
    print("Error: bpactor:ReceiveBeginPlay actor=", actor)
    print("Error: bpactor:ReceiveBeginPlay __cppinst=", actor.__cppinst)
    local tt = slua.isValid(actor.__cppinst)
    print("Error: bpactor:ReceiveBeginPlay tt=", tt)
end

`

**Comment by ShuraLiu** [comment]
升到最新的slua的话，_cppinst是个lightuserdata，应该直接用slua.isValid(actor)判断，slua内部会根据传入参数找到对应的ue对象

**Comment by gzbin7878at2016** [comment]
我直接 isValid(actor) 
报错误
bad argument #1 to 'isValid' (userdata expected, got LuaActor)
代码
local tt = slua.isValid(actor)

**Comment by gzbin7878at2016** [comment]
看了CPP, 好像没有转UE对象的过程
	int SluaUtil::isValid(lua_State * L)
	{
		// 这句话报错
		luaL_checktype(L, 1, LUA_TUSERDATA);
...

**Comment by pangweiwei** [comment]
目前的设计，是无法判断一个lightuserdata的是否valid的，因为__cppinst本来不是可以被直接使用的，你也不用关心他是否valid。

**Comment by gzbin7878at2016** [comment]
好的,谢谢
