### ISSUE TITLE
Lua 绑定 OnComponentBeginOverlap:Add 异常

### ISSUE THREAD

**Issue by gzbin7878at2016** [Tencent/sluaunreal#355]
**Describe the bug**
我在蓝图创建一个Box 碰撞体, 想把Overlap逻辑写在lua,但是在绑定的时候报异常
之前我用1.0.8版本的时候没有问题,
最近想升级插件,升级后有这个问题

**Version**
1.3.2

**To Reproduce**
1. 蓝图加入Box碰撞体
2. Lua LuaBpActor.lua ReceiveBeginPlay 事件写绑定逻辑
3. 运行直接异常
4. 代码如下
`
function actor:ReceiveBeginPlay()
    self.bCanEverTick = true
    self.bCanBeDamaged = false
    self["bp_Box"].OnComponentBeginOverlap:Add(function (...)
        self:OnComponentBeginOverlap(...)
    end)
end

function actor:OnComponentBeginOverlap(overlappedComponent, otherActor, otherComp, otherBodyIndex, bFromSweep, sweepResult)
    print("Error: OnComponentBeginOverlap")
end

`

**Crash**
`
Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x00000000

UE4Editor_slua_unreal!slua::luaD_precall()
UE4Editor_slua_unreal!slua::luaV_execute()
UE4Editor_slua_unreal!slua::luaD_callnoyield()
UE4Editor_slua_unreal!slua::luaD_rawrunprotected()
UE4Editor_slua_unreal!slua::luaD_pcall()
UE4Editor_slua_unreal!lua_pcallk()
UE4Editor_slua_unreal!slua::LuaVar::docall() [h:\lua424\sluaunreal-1.3.2\plugins\slua_unreal\source\slua_unreal\private\luavar.cpp:576]
UE4Editor_slua_unreal!slua::LuaVar::callByUFunction() [h:\lua424\sluaunreal-1.3.2\plugins\slua_unreal\source\slua_unreal\private\luavar.cpp:609]
UE4Editor_slua_unreal!slua::LuaBase::luaImplemented() [h:\lua424\sluaunreal-1.3.2\plugins\slua_unreal\source\slua_unreal\private\luabase.cpp:47]
UE4Editor_slua_unreal!ALuaActor::ProcessEvent() [h:\lua424\sluaunreal-1.3.2\plugins\slua_unreal\source\slua_unreal\public\luaactor.h:55]
`

**Desktop (please complete the following information):**
 - Windows 10

**Comment by gzbin7878at2016** [comment]
这个问题有办法解决吗?

**Comment by gzbin7878at2016** [comment]
大佬放假了吗?

**Comment by zjhongxian** [comment]
可以关注下后续的更新看看，后续Lua复写蓝图机制有大改进

**Comment by gzbin7878at2016** [comment]
这个版本改不了?
