### ISSUE TITLE
CreateDefaultSubobject，这种组件创建在lua里怎么做呢？

### ISSUE THREAD

**Issue by ZuoEr** [Tencent/sluaunreal#36]

**Comment by pangweiwei** [comment]
不支持泛型方法，作为变通，你可以自己到处一个函数接受const char* type作为输入，然后
if(type=="USceneComponent")
return CreateDefaultSubobject<USceneComponent>( TEXT( "SceneComponent" ) );
else if(type==...)
类似这样的写法。

**Comment by ZuoEr** [comment]
那就是目前如果要在lua里面创建Component的话必须要在C++里面先写一个方法，然后lua去调用吗？
