### ISSUE TITLE
请问slua-unreal目前是否支持直接在lua脚本中声明RPC函数

### ISSUE THREAD

**Issue by cici01** [Tencent/sluaunreal#361]
![image](https://user-images.githubusercontent.com/38182501/90974321-a9fe7900-e55c-11ea-8f9d-9bf81d8d3fe9.png)

![image](https://user-images.githubusercontent.com/38182501/90974646-a8828000-e55f-11ea-8b74-0c914e5ff078.png)

请问目前能否支持在lua脚本中直接声明RPC函数和Replicated 成员变量？

**Comment by pangweiwei** [comment]
你可以看看rpc那个测试例子，你需要在蓝图定义接口，然后在lua里实现，就可以实现rpc调用进入lua。

**Comment by cici01** [comment]
好的，了解了，谢谢
