### ISSUE TITLE
在lua脚本中使用SpawnEmitterAtLocation 报错

### ISSUE THREAD

**Issue by cici01** [Tencent/sluaunreal#365]
在lua脚本中使用SpawnEmitterAtLocation播放特效报错
![image](https://user-images.githubusercontent.com/38182501/91281664-f2b36d80-e7ba-11ea-84f7-5b27f22c9cba.png)

![image](https://user-images.githubusercontent.com/38182501/91281800-170f4a00-e7bb-11ea-853d-de12126ebff5.png)

**Comment by zjhongxian** [comment]
![image](https://user-images.githubusercontent.com/5793922/91297243-8f343a80-e7d0-11ea-885f-bf334c530a80.png)

**Comment by cici01** [comment]
@zjhongxian  用点的话报新的错误

![image](https://user-images.githubusercontent.com/38182501/91378682-9c463d80-e853-11ea-9e01-6a97e9d5c449.png)

![image](https://user-images.githubusercontent.com/38182501/91378702-acf6b380-e853-11ea-8001-d98be16de971.png)

**Comment by cici01** [comment]
知道问题的原因了，要把默认参数补齐

![image](https://user-images.githubusercontent.com/38182501/91381145-30ff6a00-e859-11ea-9408-562581f3d47c.png)
