### ISSUE TITLE
请问如何在lua脚本里面使用SetTimer

### ISSUE THREAD

**Issue by cici01** [Tencent/sluaunreal#368]
在脚本里面使用SetTimer，绑定函数的时候发现

![image](https://user-images.githubusercontent.com/38182501/91441376-ae030180-e8a2-11ea-9e23-79f600f28165.png)

BindUFunction失败，有办法直接在Lua脚本中直接定义timer要执行的函数吗？

![2](https://user-images.githubusercontent.com/38182501/91441392-b52a0f80-e8a2-11ea-8d80-180b78cc7b80.jpg)

使用 slua.createDelegate( function() end ) 来包装一个lua function 变成一个 delegate，又报新的错误
![3](https://user-images.githubusercontent.com/38182501/91441394-b65b3c80-e8a2-11ea-85c3-3f6234569d9c.jpg)
![4](https://user-images.githubusercontent.com/38182501/91441395-b6f3d300-e8a2-11ea-9579-3f82603f168c.jpg)

**Comment by pangweiwei** [comment]
我看了下，这个delegate的实现需要一个UObject，可能对你最简单的就是自己简单通过cppbinding分装一个支持lua function timer

**Comment by cici01** [comment]
嗯，考虑了一下，可能只能这么做U最简单了

**Comment by cici01** [comment]
> 我看了下，这个delegate的实现需要一个UObject，可能对你最简单的就是自己简单通过cppbinding分装一个支持lua function timer

嗯，考虑了一下，可能只能这么做U最简单了
