### ISSUE TITLE
想请教下如何在slua中编写绑定事件分发器的。And想加个群

### ISSUE THREAD

**Issue by ly-ue4-backend** [Tencent/sluaunreal#369]
已阅读过了相关的基础教程了。目前我所需要的功能没有相关资料。
还有个问题，像是在slua中调用ReceiveBeginPlay是重写了lua子类的ReceiveBeginPlay是吧，我没理解错吧？调用slua actor->ReceiveBeginPlay 的实现可以等同于ue4 actor ->Beginplay 是这种等价实现关系是吧。

**Comment by pangweiwei** [comment]
是的

**Comment by ly-ue4-backend** [comment]
有个新问题，我看bp可以调lua，lua能调bp中的委托么？我看例子是有lua->bp func ;bp->lua func;lua add delegate ，call lua delegate,但是我没有看到例子or代码有直接实现 lua call bp delegate.....另外一个问题我看slua部分的代码没有类似于server ，client的标识，那么rpc这块是个谜？？ue rpc不是需要指定类型的么？还是我看漏了，还是slua实现的部分全是默认的。
