### ISSUE TITLE
CppBinding函数的参数必须为const char* 吗，为什么使用char*会报错

### ISSUE THREAD

**Issue by lxhhuangjin** [Tencent/sluaunreal#370]
`  TestLua.cpp.obj : error LNK2019: 无法解析的外部符号 "public: static struct slua::SimpleString __cdecl slua::TypeName<char,0>::value(void)" (?value@?$TypeName@D$0A@@slua@@SA?AUSimpleString@2@XZ)，该符号在函数 "public: static char * __cdecl slua::LuaObject::checkReturn<char *>(struct slua::lua_State *,int)" (??$checkReturn@PEAD@LuaObject@slua@@SAPEADPEAUlua_State@1@H@Z) 中被引用`

**Comment by pangweiwei** [comment]
对的，目前不支持char*

你可以自己在LuaObject.h 里添加 char* 的checkValue，不过实际情况下const char* 更符合语义。
