### ISSUE TITLE
1.为什么不在ExtensionMethod::init()中传入state，这样可以在这个函数里使用DefGlobalMethod；2.REG_EXTENSION_METHOD暂时不支持导出返回值是指针常量的函数吗？；3.REG_EXTENSION_METHOD暂时不支持导出FORCEINLINE的函数吗？；

### ISSUE THREAD

**Issue by lyuavery** [Tencent/sluaunreal#38]

**Comment by pangweiwei** [comment]
1） ExtensionMethod 的语意很明确，添加uobject的扩展方法，如果你需要添加DefGlobalMethod，可以在任何你希望的地方做自己的init函数增加global函数；

**Comment by lyuavery** [comment]
->1）在任意地方进行注册的话不能保证一定是在任意（main state里的）lua代码执行前注册的吧，可能出现调用时由于未被注册而调用失败？

**Comment by pangweiwei** [comment]
2）可能会因为push的匹配到了bool分支，所以我增加一个const uobject*的push支持，应该可以解决这个问题；

**Comment by pangweiwei** [comment]
1）你可以在extesion init的地方添加你自己的一个init函数

**Comment by lyuavery** [comment]
->2)（我想我应该提供更多信息的......）是的，class USkeletalMeshSocket const* GetSocketByName( FName InSocketName ) const;在导出的这个方法在正确返回时，返回值是true

**Comment by lyuavery** [comment]
->3)（补充）导出FORCEINLINE函数时，宏展开会有语法报错，expect a ‘)'

**Comment by lyuavery** [comment]
->3)测试了一下，应该不是不支持FORCEINLINE，只是我导出的刚好是返回FRotator的函数，所以没有push版本匹配到，谢谢大佬解答！
