### ISSUE TITLE
cppbind问题

### ISSUE THREAD

**Issue by jy00223715** [Tencent/sluaunreal#384]
很基础的问题，democpp 同样编译不通过，自己写的例子也不通过，求教到底应该如何做绑定
绑定后在lua里如何调用，谢谢
`class fuck {
	LuaClassBody()
public:
	void FuckU()
	{
		//Log::Log("baseFunc1 call");
	}
};

DefLuaClass(fuck)
	DefLuaMethod(FuckU, &fuck::FuckU)
EndDef(fuck, &NoConstructor)`

**Comment by pangweiwei** [comment]
你在EndDef这里使用了 NoConstructor，说明这个东西不可以在lua侧被构造

你需要写一个类似create的函数，去构造并返回class，才能在lua侧使用类似如下的代码构造：

local f = fuck(....)

**Comment by jamessg** [comment]
关于cppbinding这个也想请教比较基础的问题，也辛苦帮忙解答一下@pangweiwei 
DefLuaClass(Test)
DefLuaMethod(hello, &fuck::hello)
EndDef(fuck, &Test:create)`

使用宏定义后，是否还需要其他注册等操作呢，还是只要定义了，就会自动绑定，直接lua中调用就行呢？
另外在enddef时，什么情况需要构造，什么情况不需要构造或传入nullptr呢，如果没有构造，在lua中如何调用呢？
静态方法和非静态方法导出是一样的配置吗？

是否有cppbinding相关的demo可以参考呢
