### ISSUE TITLE
请问lua调用蓝图函数时，如何传递数组过去

### ISSUE THREAD

**Issue by gzxb525** [Tencent/sluaunreal#389]
我 a:func({actor}) 这样传递一个数组过去，在蓝图那边的参数定义为Array Of Actor，里面显示Length为0.
是不是应该创建一个TArray传递过去，我看资料里面说有个LuaArray，但是不知道在lua中应该如何创建,
谢谢

**Comment by lzsong** [comment]
slua.Array可以创建，但是调用蓝图方法可以直接用lua的table 会自动转换

**Comment by gzxb525** [comment]
谢谢
