### ISSUE TITLE
for_4.25分支 mac 下编译失败

### ISSUE THREAD

**Issue by Manhelp** [Tencent/sluaunreal#403]
**mac build for_4.25**
mac 下编译失败 引擎版本4.25.4
macOS BIg Sur 11.0.1
xcode 12.2
<img width="276" alt="截屏2020-12-06 下午1 15 13" src="https://user-images.githubusercontent.com/9910074/101272232-3445b280-37c5-11eb-9a63-0715b029d6bb.png">

**Comment by pangweiwei** [comment]
是不是 报告 select.o 连接一个符号失败？如果是请重新用cmake编译mac下lua lib。

**Comment by Manhelp** [comment]
没有日志， 只有上图的error， 点OK就关掉了， 重新编译了lua lib也不行

**Comment by Manhelp** [comment]
噗，是我这边的问题，新项目和老项目都编译不了了， 升级系统和引擎后没打开过新项目和老项目！！！
