### ISSUE TITLE
luawrapper生成工具相关

### ISSUE THREAD

**Issue by inarutom2014** [Tencent/sluaunreal#42]
请问生成工具有相关文档说明吗，目前项目用到一些F类在LuaWrapper中并没有导出，只能手写，同时也希望生成工具能开源，可以根据项目定制一些特异化的生成需求，十分感谢

**Comment by pangweiwei** [comment]
这个工具，目前正在走开源流程，会开源的
目前你可以直接修改tools目录下的配置文件

**Comment by inarutom2014** [comment]
配置文件可以增加文档说明吗，如果需要把某个F类加入luawrapper，是把include_path下的路径包含进去吗？
另外再请教一个问题，luawrapper生成代码里，如果是F类静态方法，绑定的方法里会忽略函数第一个参数，比如在lua端调用FVector的Distance静态方法，不能写成FVector.Distance(FVector(),FVector(1,1,1))，因为参数个数只有2个，而luawrapper那里的绑定方法参数是三个，只能写成FVector:Distance(FVector(),FVector(1,1,1))，没有想明白设计的用意，希望帮忙解答一下，不胜感谢

**Comment by pangweiwei** [comment]
嗯，这是个bug，我们会fix

**Comment by pangweiwei** [comment]
fixed
