### ISSUE TITLE
CheckUD would crash when UD is nullptr

### ISSUE THREAD

**Issue by eigeneko** [Tencent/sluaunreal#422]
Mistakenly using . rather than :  in LuaArray  will lead to crash.
 
```lua
local x = slua.Array(UEnums.EpropertyClass.Int)
x.Num()
```
```c++
int LuaArray::Num(lua_State* L) {
    CheckUD(LuaArray,L,1);
    return LuaObject::push(L,UD->num());
}
```
`CheckUD` return a nullptr when the item corresponding to the index is nil
```c++
template<typename T>
static T* checkUD(lua_State* L,int p,bool checkfree=true) {
    if (lua_isnoneornil(L, p)) {
        return nullptr;
	}
```

Which one would be better for fixing this problem ？
1. Check whether `UD` is valid after `CheckUD`.
2. Instead of returning a nullptr, call `luaL_error`.
Are there some situations that `CheckUD` **must** return nullptr ? If there are then maybe 2 is infeasible.

In most situations, `UD` is used directly after `CheckUD`. Then raise an error inside `CheckUD` maybe OK.
But I'm not sure whether some outer codes rely on returned `UD` being nullptr in some cases.
```c++
template<>
inline UScriptStruct* LuaObject::checkValue(lua_State* L, int p) {
    CheckUD(UScriptStruct, L, p);
    return UD;
}
```

**Comment by zjhongxian** [comment]
Fixed in slua unreal 2.0 version.
