### ISSUE TITLE
关于uproperty属性get/set错误问题

### ISSUE THREAD

**Issue by xiaoaq** [Tencent/sluaunreal#426]
**Describe the bug**
lua中获取的bp属性值是bp中的默认值，bp中对属性值做了修改之后，lua再次获取，得到的仍然是默认值。
lua中修改bp属性值，bp中并未被更改。
就是lua或bp中做修改后，只在本端有效。

**Version**
1.3.3

**Comment by zjhongxian** [comment]
1、我猜你拿出的属性是ustrcut类型，然后对ustruct的某个嵌套字段赋值了。
2、slua对于ustruct的属性赋值设计，类似于csharp中的struct，都是值复制的形式。
你代码是不是类似下面？
local bp = slua.loadUI("xxxx.xxxx")
print(bp.Anchors.min.x, bp.Anchors.min.y) -- 结果为0， 0
bp.Anchors.min = FVector2D(1, 1)
print(bp.Anchors.min.x, bp.Anchors.min.y) -- 结果为0， 0

**Comment by xiaoaq** [comment]
> 1、我猜你拿出的属性是ustrcut类型，然后对ustruct的某个嵌套字段赋值了。
> 2、slua对于ustruct的属性赋值设计，类似于csharp中的struct，都是值复制的形式。
> 你代码是不是类似下面？
> local bp = slua.loadUI("xxxx.xxxx")
> print(bp.Anchors.min.x, bp.Anchors.min.y) -- 假设结果为0， 0
> bp.Anchors.min = FVector2D(1, 1)
> print(bp.Anchors.min.x, bp.Anchors.min.y) -- 结果为0， 0

不是的，基础类型的属性也是如此，eg.int、float.
