### ISSUE TITLE
大佬你好，TArray在lua里目前是不是只支持int和string，Object还不支持吗？

### ISSUE THREAD

**Issue by ZuoEr** [Tencent/sluaunreal#43]
我用这个slua.Array(UEnums.EPropertyClass.Object)
传入GameplayStatics.GetAllActorsOfClass，发现并不行。

**Comment by pangweiwei** [comment]
ufunction 的out参数，直接当做额外的lua返回值返回

**Comment by ZuoEr** [comment]
Array类型也会作为额外的返回值返回吗？应该只有基础类型需额外的lua返回值返回吧？

**Comment by pangweiwei** [comment]
也会
