### ISSUE TITLE
无法导出UStruct类型的方法

### ISSUE THREAD

**Issue by lc1995** [Tencent/sluaunreal#432]
看了一下，UStruct类型导出到lua里是一个LuaStruct的结构。这个结构只支持访问对应的UProperty，以及支持参数传递，但好像并不支持通过cppbinding导出方法。

导出的方法在checkUD阶段先抛出类型不匹配的异常。我在这个阶段加了一个对LuaStruct类型的检查，机制上是可行的，就是不确定会不会有什么其他问题，还是说设计上就不希望用户导出UStruct的方法。

如果不会有其他问题，我可以提交一个MR。

**Comment by ShuraLiu** [comment]
仿照LuaWrapper.cpp自己实现一个对应的binding应该是可行的。

**Comment by lc1995** [comment]
> 仿照LuaWrapper.cpp自己实现一个对应的binding应该是可行的。

所有的UStruct都需要参照LuaWrapper的方式手写binding吗，这样量还挺多的。
而且对于有反射信息的UStruct，是不是应该也可以使用动态Binding的形式。

而且我看有个Commit还提到，不应该在LuaWrapper里导出UStruct类型。

**Comment by ShuraLiu** [comment]
就我这边项目的情况来看，UStruct都是用来做数据存储，不会有方法。如果有方法的话一般都用UObject
