### ISSUE TITLE
请问如何返回UTexture2D给Lua？

### ISSUE THREAD

**Issue by zty0** [Tencent/sluaunreal#449]
C++里定义了一个函数，加载一个新的UTexture2D并返回，希望能在Lua里使用这个函数，请问应该怎么做呢？仿照SluaUtil:::loadObject方法写了一个，似乎不行，在lua里print是个int，而不是期待的UTexture2D类型

**Comment by zty0** [comment]
`int MyAssetManager::loadAsset()
{
	UMyGameInstance *pGI = Cast<UMyGameInstance>(GEditor->PlayWorld->GetGameInstance());
	FStreamableManager& streamableManager = UAssetManager::Get().GetStreamableManager();
	FString file = TEXT("Texture2D'/Game/tex.tex");
	UTexture2D* loadedObject = streamableManager.LoadSynchronous<UTexture2D>(FSoftObjectPath(file));

	return NS_SLUA::LuaObject::push(pGI->state.getLuaState(), loadedObject);
}`

代码是这么写的，但是lua里得到的却是1

**Comment by pangweiwei** [comment]
一般c++函数使用cppbinding自动导出，直接返回UTexture2d*
如果你手写lua函数导出，就需要完全lua导出函数的签名
int (*luafunction)(lua_state* L)

这样形式，否则不理解你的写法，会返回1，本身在lua函数里，返回是说stack上有一个返回值。
