### ISSUE TITLE
由于编译报错导致Android打包失败

### ISSUE THREAD

**Issue by inarutom2014** [Tencent/sluaunreal#46]
lua插件的Log.h里对于宽字符输出的函数声明用的是const TCHAR*，在Log.cpp里实现用的是const wchar_t*,在windows平台该变量是一致的，但是在android平台是const char16_t *，导致函数找不到定义，编译失败

**Comment by pangweiwei** [comment]
你的ndk版本？

**Comment by inarutom2014** [comment]
r12b

**Comment by inarutom2014** [comment]
如果使用类似于slua::Log::Log(TEXT("this a log"));会产生编译报错 如果使用slua::Log::Log("this a log")是不会报错的，因为在Android平台类型一致，demo工程中用到的Log传参都是const char* 没有用到过const TCHAR*，所以demo编译不会报错

**Comment by inarutom2014** [comment]
报错的日志
error: undefined reference to 'slua::Log::Error(char16_t const*, ...)'

**Comment by pangweiwei** [comment]
请使用至少r13b之后的版本

**Comment by inarutom2014** [comment]
好的，我试一下
