### ISSUE TITLE
4.27.2版本Ureal引擎，编译iOS版本，LuaObject.cpp报错

### ISSUE THREAD

**Issue by dsz0** [Tencent/sluaunreal#493]
**Describe the bug**
在4.27.2版本Ureal引擎，编译iOS版本，LuaObject.cpp报错

**Version**
1.3.3
**To Reproduce**
1. 在4.27.2版本进行ipa版本编译
2. 发现111行FBlueprintExceptionTracker为undeclared identifier
3. virtual ~FNewFrame() 中的118行也暴露了同样相关FBlueprintExceptionTracker的错误

**Expected behavior**
针对新版本，处理此问题，使用其他方法及进行蓝图错误的记录处理。

**Screenshots**
![55a07d436c23c956d9c188fc13c4c45](https://user-images.githubusercontent.com/33507061/154900213-052d332f-30ed-48cf-9649-db195f128a1f.jpg)

**Desktop (please complete the following information):**
 - OS: macOS12.1 上打包 iOS（ipa文件）
XCode版本13.2.1

**Additional context**

**Comment by zjhongxian** [comment]
建议升级2.0版本

**Comment by pangweiwei** [comment]
这个最近修复了一个可能的因素，你 up 一下
