### ISSUE TITLE
4.27.2打开项目报错

### ISSUE THREAD

**Issue by flyxujie** [Tencent/sluaunreal#496]
4.27.2打开项目报错，打不开项目
现在的分支是否支持4.27

**Comment by stonexing** [comment]
同样报错，找不到解决办法
切换到4.24.3后可以打开demo
我macOS 12.2.1但无法在新项目中使用sluaunreal。
目前能发现lua-wrapper.exe。这种文件显然是windows下的东西。
希望官方赶紧支持4.27和macOS

**Comment by ShuraLiu** [comment]
用for_4.25分支

**Comment by stonexing** [comment]
此项目貌似不维护了
请移步腾讯的另外一个lua项目
https://github.com/Tencent/UnLua

**Comment by zjhongxian** [comment]
最新已经修复不同版本打开的问题。用4.26以后的版本应该都能打开。
