### ISSUE TITLE
Slua打包一直出现空包错误问题

### ISSUE THREAD

**Issue by fistpan** [Tencent/sluaunreal#499]
**Describe the bug**

**Version**
What version of slua you used?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Crash**
If crashed, attach traceback information.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows macOS iOS Android]
 - Other information about your environment.

**Additional context**

**Comment by fistpan** [comment]
使用 的是UE5.01版本
插件下载编译进入，直接发行打包，没有做任务动作。
提示打包成功，但是一直是空包没有任何文件
UATHelper: 打包 (Windows): D:\_UE5Projects\self2\Plugins\UnLua\Source\UnLua\Private\Containers\LuaArray.h(130): warning C4996: 'TScriptArray<FHeapAllocator>::Add': TScriptArray::Add without an alignment parameter is deprecated. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
UATHelper: 打包 (Windows): D:\_UE5Projects\self2\Plugins\UnLua\Source\UnLua\Private\Containers\LuaArray.h(143): warning C4996: 'TScriptArray<FHeapAllocator>::Add': TScriptArray::Add without an alignment parameter is deprecated. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
UATHelper: 打包 (Windows): D:\_UE5Projects\self2\Plugins\UnLua\Source\UnLua\Private\Containers\LuaArray.h(177): warning C4996: 'TScriptArray<FHeapAllocator>::Insert': TScriptArray::Insert without an alignment parameter is deprecated. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
UATHelper: 打包 (Windows): D:\_UE5Projects\self2\Plugins\UnLua\Source\UnLua\Private\Containers\LuaArray.h(194): warning C4996: 'TScriptArray<FHeapAllocator>::Remove': TScriptArray::Remove without an alignment parameter is deprecated. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
UATHelper: 打包 (Windows): D:\_UE5Projects\self2\Plugins\UnLua\Source\UnLua\Private\Containers\LuaArray.h(225): warning C4996: 'TScriptArray<FHeapAllocator>::Empty': TScriptArray::Empty without an alignment parameter is deprecated. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
UATHelper: 打包 (Windows): D:\_UE5Projects\self2\Plugins\UnLua\Source\UnLua\Private\Containers\LuaArray.h(241): warning C4996: 'TScriptArray<FHeapAllocator>::Empty': TScriptArray::Empty without an alignment parameter is deprecated. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
UATHelper: 打包 (Windows): D:\_UE5Projects\self2\Plugins\UnLua\Source\UnLua\Private\Containers\LuaArray.h(262): warning C4996: 'TScriptArray<FHeapAllocator>::Remove': TScriptArray::Remove without an alignment parameter is deprecated. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
UATHelper: 打包 (Windows): D:\_UE5Projects\self2\Plugins\UnLua\Source\UnLua\Private\LuaContext.cpp(468): warning C4996: 'UObjectBaseUtility::IsPendingKill': IsPendingKill() should no longer be used. Use IsValid(Object), IsValidChecked(Object) or GetValid(Object) instead. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
UATHelper: 打包 (Windows): D:\_UE5Projects\self2\Plugins\UnLua\Source\UnLua\Private\UnLuaBase.cpp(457): warning C4996: 'TScriptArray<FHeapAllocator>::Empty': TScriptArray::Empty without an alignment parameter is deprecated. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
UATHelper: 打包 (Windows): D:\_UE5Projects\self2\Plugins\UnLua\Source\UnLua\Private\UnLuaBase.cpp(458): warning C4996: 'TScriptArray<FHeapAllocator>::Add': TScriptArray::Add without an alignment parameter is deprecated. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
UATHelper: 打包 (Windows): [73/75] Compile Module.slua_unreal.cpp
UATHelper: 打包 (Windows): D:\_UE5Projects\self2\Plugins\slua_unreal\Source\slua_unreal\Private\LuaArray.cpp(88): warning C4996: 'TScriptArray<FHeapAllocator>::Empty': TScriptArray::Empty without an alignment parameter is deprecated. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
UATHelper: 打包 (Windows): D:\_UE5Projects\self2\Plugins\slua_unreal\Source\slua_unreal\Private\LuaArray.cpp(122): warning C4996: 'TScriptArray<FHeapAllocator>::Add': TScriptArray::Add without an alignment parameter is deprecated. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
UATHelper: 打包 (Windows): D:\_UE5Projects\self2\Plugins\slua_unreal\Source\slua_unreal\Private\LuaArray.cpp(128): warning C4996: 'TScriptArray<FHeapAllocator>::Insert': TScriptArray::Insert without an alignment parameter is deprecated. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
UATHelper: 打包 (Windows): D:\_UE5Projects\self2\Plugins\slua_unreal\Source\slua_unreal\Private\LuaArray.cpp(135): warning C4996: 'TScriptArray<FHeapAllocator>::Remove': TScriptArray::Remove without an alignment parameter is deprecated. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
UATHelper: 打包 (Windows): C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winnt.h(603): warning C4005: ��TEXT��: ���ض���
UATHelper: 打包 (Windows): C:\Program Files\Epic Games\UE_5.0\Engine\Source\Runtime\Core\Public\HAL\Platform.h(1151): note: �μ���TEXT����ǰһ������
UATHelper: 打包 (Windows): D:\_UE5Projects\self2\Plugins\slua_unreal\Source\slua_unreal\Private\LuaWrapper.cpp(2659): warning C4996: 'FLinearColor::Quantize': Most callers of Quantize should have been calling QuantizeRound; to match old behavior use QuantizeFloor Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
UATHelper: 打包 (Windows): [74/75] Link self2-Win64-Shipping.exe
UATHelper: 打包 (Windows): lua.lib(lapi.obj) : error LNK2005: lua_absindex �Ѿ��� lapi.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(lapi.obj) : error LNK2005: lua_arith �Ѿ��� lapi.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(lapi.obj) : error LNK2005: lua_atpanic �Ѿ��� lapi.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(lapi.obj) : error LNK2005: lua_callk �Ѿ��� lapi.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(lapi.obj) : error LNK2005: lua_checkstack �Ѿ��� lapi.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(lapi.obj) : error LNK2005: lua_compare �Ѿ��� lapi.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(lapi.obj) : error LNK2005: lua_concat �Ѿ��� lapi.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(lapi.obj) : error LNK2005: lua_copy �Ѿ��� lapi.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(lapi.obj) : error LNK2005: lua_createtable �Ѿ��� lapi.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(lapi.obj) : error LNK2005: lua_error �Ѿ��� lapi.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(lapi.obj) : error LNK2005: lua_gc �Ѿ��� lapi.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(lapi.obj) : error LNK2005: lua_getallocf �Ѿ��� lapi.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(lapi.obj) : error LNK2005: lua_getfield �Ѿ��� lapi.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(lapi.obj) : error LNK2005: lua_getglobal �Ѿ��� lapi.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(lapi.obj) : error LNK2005: lua_geti �Ѿ��� lapi.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(lapi.obj) : error LNK2005: lua_getmetatable �Ѿ��� lapi.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(lapi.obj) : error LNK2005: lua_gettable �Ѿ��� lapi.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(lapi.obj) : error LNK2005: lua_gettop �Ѿ��� lapi.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(lapi.obj) : error LNK2005: lua_getupvalue �Ѿ��� lapi.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(lapi.obj) : error LNK2005: lua_iscfunction �Ѿ��� lapi.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(lapi.obj) : error LNK2005: lua_isinteger �Ѿ��� lapi.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(lapi.obj) : error LNK2005: lua_isnumber �Ѿ��� lapi.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(lapi.obj) : error LNK2005: lua_isstring �Ѿ��� lapi.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(lapi.obj) : error LNK2005: lua_isuserdata �Ѿ��� lapi.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(lapi.obj) : error LNK2005: lua_len �Ѿ��� lapi.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(lapi.obj) : error LNK2005: lua_load �Ѿ��� lapi.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(lapi.obj) : error LNK2005: lua_next �Ѿ��� lapi.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(lapi.obj) : error LNK2005: lua_pcallk �Ѿ��� lapi.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(lapi.obj) : error LNK2005: lua_pushboolean �Ѿ��� lapi.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(lapi.obj) : error LNK2005: lua_pushcclosure �Ѿ��� lapi.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(lapi.obj) : error LNK2005: lua_pushfstring �Ѿ��� lapi.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(lapi.obj) : error LNK2005: lua_pushinteger �Ѿ��� lapi.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(lapi.obj) : error LNK2005: lua_pushlightuserdata �Ѿ��� lapi.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(lapi.obj) : error LNK2005: lua_pushlstring �Ѿ��� lapi.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(lapi.obj) : error LNK2005: lua_pushnil �Ѿ��� lapi.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(lapi.obj) : error LNK2005: lua_pushnumber �Ѿ��� lapi.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(lapi.obj) : error LNK2005: lua_pushstring �Ѿ��� lapi.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(lapi.obj) : error LNK2005: lua_pushthread �Ѿ��� lapi.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(lapi.obj) : error LNK2005: lua_pushvalue �Ѿ��� lapi.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(lapi.obj) : error LNK2005: lua_pushvfstring �Ѿ��� lapi.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(lapi.obj) : error LNK2005: lua_rawequal �Ѿ��� lapi.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(lapi.obj) : error LNK2005: lua_rawget �Ѿ��� lapi.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(lapi.obj) : error LNK2005: lua_rawgeti �Ѿ��� lapi.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(lapi.obj) : error LNK2005: lua_rawgetp �Ѿ��� lapi.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(lapi.obj) : error LNK2005: lua_rawlen �Ѿ��� lapi.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(lapi.obj) : error LNK2005: lua_rawset �Ѿ��� lapi.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(lapi.obj) : error LNK2005: lua_rawseti �Ѿ��� lapi.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(lapi.obj) : error LNK2005: lua_rawsetp �Ѿ��� lapi.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(lapi.obj) : error LNK2005: lua_rotate �Ѿ��� lapi.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(lapi.obj) : error LNK2005: lua_setallocf �Ѿ��� lapi.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(lapi.obj) : error LNK2005: lua_setfield �Ѿ��� lapi.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(lapi.obj) : error LNK2005: lua_setglobal �Ѿ��� lapi.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(lapi.obj) : error LNK2005: lua_seti �Ѿ��� lapi.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(lapi.obj) : error LNK2005: lua_setmetatable �Ѿ��� lapi.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(lapi.obj) : error LNK2005: lua_settable �Ѿ��� lapi.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(lapi.obj) : error LNK2005: lua_settop �Ѿ��� lapi.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(lapi.obj) : error LNK2005: lua_setupvalue �Ѿ��� lapi.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(lapi.obj) : error LNK2005: lua_status �Ѿ��� lapi.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(lapi.obj) : error LNK2005: lua_stringtonumber �Ѿ��� lapi.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(lapi.obj) : error LNK2005: lua_toboolean �Ѿ��� lapi.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(lapi.obj) : error LNK2005: lua_tocfunction �Ѿ��� lapi.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(lapi.obj) : error LNK2005: lua_tointegerx �Ѿ��� lapi.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(lapi.obj) : error LNK2005: lua_tolstring �Ѿ��� lapi.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(lapi.obj) : error LNK2005: lua_tonumberx �Ѿ��� lapi.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(lapi.obj) : error LNK2005: lua_topointer �Ѿ��� lapi.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(lapi.obj) : error LNK2005: lua_tothread �Ѿ��� lapi.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(lapi.obj) : error LNK2005: lua_touserdata �Ѿ��� lapi.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(lapi.obj) : error LNK2005: lua_type �Ѿ��� lapi.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(lapi.obj) : error LNK2005: lua_typename �Ѿ��� lapi.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(lapi.obj) : error LNK2005: lua_upvalueid �Ѿ��� lapi.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(lapi.obj) : error LNK2005: lua_upvaluejoin �Ѿ��� lapi.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(lapi.obj) : error LNK2005: lua_version �Ѿ��� lapi.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(lapi.obj) : error LNK2005: lua_xmove �Ѿ��� lapi.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(lstate.obj) : error LNK2005: lua_close �Ѿ��� lstate.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(lstate.obj) : error LNK2005: lua_newstate �Ѿ��� lstate.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(lstate.obj) : error LNK2005: lua_newthread �Ѿ��� lstate.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(ldebug.obj) : error LNK2005: lua_gethook �Ѿ��� ldebug.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(ldebug.obj) : error LNK2005: lua_gethookcount �Ѿ��� ldebug.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(ldebug.obj) : error LNK2005: lua_gethookmask �Ѿ��� ldebug.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(ldebug.obj) : error LNK2005: lua_getinfo �Ѿ��� ldebug.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(ldebug.obj) : error LNK2005: lua_getlocal �Ѿ��� ldebug.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(ldebug.obj) : error LNK2005: lua_getstack �Ѿ��� ldebug.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(ldebug.obj) : error LNK2005: lua_sethook �Ѿ��� ldebug.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(ldebug.obj) : error LNK2005: lua_setlocal �Ѿ��� ldebug.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(ldo.obj) : error LNK2005: lua_isyieldable �Ѿ��� ldo.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(ldo.obj) : error LNK2005: lua_resume �Ѿ��� ldo.c.obj �ж���
UATHelper: 打包 (Windows): lua.lib(ldo.obj) : error LNK2005: lua_yieldk �Ѿ��� ldo.c.obj �ж���
UATHelper: 打包 (Windows):   ���ڴ����� D:\_UE5Projects\self2\Binaries\Win64\self2-Win64-Shipping.lib �Ͷ��� D:\_UE5Projects\self2\Binaries\Win64\self2-Win64-Shipping.exp
UATHelper: 打包 (Windows): D:\_UE5Projects\self2\Binaries\Win64\self2-Win64-Shipping.exe : fatal error LNK1169: �ҵ�һ���������ض���ķ���
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
是否是找不到link，该如何解决这个问题

**Comment by zjhongxian** [comment]
可以使用新版试试？新版我自测可以出包并运行了
