### ISSUE TITLE
attempt to call a nil value (component method, eg. 'IsVisible')

### ISSUE THREAD

**Issue by xiaoaq** [Tencent/sluaunreal#508]
**Describe the bug**
经常出现actor beginplay中调用某个组件的组件函数，函数为空的情况。

**Version**
UE4.26 & slua

**Screenshots**
![image](https://user-images.githubusercontent.com/33898493/183243365-73ee776e-35d8-4c31-a0f5-4f712551c6f9.png)

**Desktop (please complete the following information):**
 - OS: Android
 - Device: PicoNeo3

**Additional context**
eg.  attempt to call a nil value (method 'IsVisible'), object is a static mesh component.

**Comment by zjhongxian** [comment]
可以升级最新slua看看，已解决这个问题
