### ISSUE TITLE
vs2022 编译错误

### ISSUE THREAD

**Issue by scriptkitz** [Tencent/sluaunreal#509]
1> error C2752: 'slua::LuaCppBinding<void (__cdecl slua::LuaMovementFilter::* )(slua::LuaVar,slua::LuaVar,slua::LuaVar,slua::LuaVar),void slua::LuaMovementFilter::slua_SetFunction(slua::LuaVar,slua::LuaVar,slua::LuaVar,slua::LuaVar),1>': more than one partial specialization matches the template argument list
1>  LuaCppBinding.h(283): note: could be 'slua::LuaCppBinding<RET(__cdecl T::* )(ARG...),func,1>'
1>  LuaCppBinding.h(301): note: or       'slua::LuaCppBinding<void(__cdecl T::* )(ARG...),func,1>'

vs2019编译正常，升级了vs2022就编译错误。。。。
看起来vs2022区分不了特例化的返回值不同的函数指针的模板参数，哇擦。。。什么玩意。

**Comment by zjhongxian** [comment]
请关注2.0版本，这个问题已经修复
