### ISSUE TITLE
4.21 開起專案卡住

### ISSUE THREAD

**Issue by KONA-DEV** [Tencent/sluaunreal#52]
我電腦Win7使用UE4.21及VS2017 
照著【安装使用】直接打开 democpp.uproject文件
會卡在編譯的地方

`2>  [11/14] UE4Editor-lua_wrapper.dll
2>     Creating library D:\Work\Git\UE4RPG\Client\LuaTest\LuaTest\Plugins\lua_wrapper\Intermediate\Build\Win64\UE4Editor\Development\lua_wrapper\UE4Editor-lua_wrapper.suppressed.lib and object D:\Work\Git\UE4RPG\Client\LuaTest\LuaTest\Plugins\lua_wrapper\Intermediate\Build\Win64\UE4Editor\Development\lua_wrapper\UE4Editor-lua_wrapper.suppressed.exp
`
產出.sln編譯也同樣
都會卡在lua_wrapper.suppressed.lib
超過一小時不會下一步

請問是否需要其他設置
需要自己安裝CMAKE嗎

**Comment by pangweiwei** [comment]
不需要，之前发生过，感觉起来是vs2017的bug，cl在编译时对某些代码编译的很慢，但并不知道原因是什么，mac系统就没有这样问题；
你可以尝试更新vs2017试试。

**Comment by pangweiwei** [comment]
https://github.com/Tencent/sluaunreal/blob/05fac7c0bc301bac7ccc97864ff2f87911338942/Plugins/slua_unreal/Source/slua_unreal/Private/LuaState.cpp#L288

之前发生过问题的代码，你可以参考下

**Comment by KONA-DEV** [comment]
了解   謝謝你的幫助！

**Comment by KONA-DEV** [comment]
我用4.20跑1.0beta2 可以運行了
非常感謝

**Comment by pangweiwei** [comment]
fixed, 和之前的问题是一样的，只要dobuffer里直接调用strlen函数就会卡死cl，vs的bug
