### ISSUE TITLE
ULuaOverrider::luaOverrideFunc函数内存泄漏

### ISSUE THREAD

**Issue by gunsungithub** [Tencent/sluaunreal#523]
https://github.com/Tencent/sluaunreal/blob/71dcb582728c8efe9c33d0e768eeb5b88441585b/Plugins/slua_unreal/Source/slua_unreal/Private/LuaOverrider.cpp#L86-L87
看起来可能会内存泄漏

**Comment by zjhongxian** [comment]
不会的，它是栈上申请内存的，会自动回收

**Comment by gunsungithub** [comment]
请教一下，看上去是一个普通的malloc，为什么是在栈上呢？

**Comment by gunsungithub** [comment]
https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/alloca?view=msvc-170
懂了
