### ISSUE TITLE
2.0.2绑定lua脚本时报错not a lua table!

### ISSUE THREAD

**Issue by korben1029** [Tencent/sluaunreal#527]
UE5.2
lua_getmetatable 一直返回0
![无标题](https://github.com/Tencent/sluaunreal/assets/34670850/3ab1bbc2-0433-4bfc-b55e-3c6ca80f14de)

**Comment by zjhongxian** [comment]
请问能否提供下lua脚本的内容？或者先看看是否有脚本报错了

**Comment by korben1029** [comment]
> 

你好，下面是lua内容和绑定脚本的截图，ue5.1与5.2我都试了，都在这里报同样的错误
![1](https://github.com/Tencent/sluaunreal/assets/34670850/31402933-4ad3-4826-995e-04a9c2c28d87)
![2](https://github.com/Tencent/sluaunreal/assets/34670850/511e7e58-8351-4056-8640-3a79665ef406)

**Comment by zjhongxian** [comment]
如果你用的是最新slua，可能写法得改一下了。。你最后一句这样写：
return Class(nil, nil, mainui)

可以详细查看readme后半的slua 2.0更新部分内容。

**Comment by korben1029** [comment]
> 如果你用的是最新slua，可能写法得改一下了。。你最后一句这样写： return Class(nil, nil, mainui)
> 
> 可以详细查看readme后半的slua 2.0更新部分内容。

可以运行了，感谢 :P
