### ISSUE TITLE
instanceIndex时栈中第一个元素是一个table

### ISSUE THREAD

**Issue by edianzyg** [Tencent/sluaunreal#529]
![image](https://github.com/Tencent/sluaunreal/assets/122305054/2fbdf05c-30b8-49c0-83ab-0c0bd96a38a7)

问题1：
lua调用
![image](https://github.com/Tencent/sluaunreal/assets/122305054/f1b30e7b-4379-4dc3-83ea-f9a822c0d1d9)

返回错误
![image](https://github.com/Tencent/sluaunreal/assets/122305054/70a9416b-f0b8-4d21-a047-d97672380d76)

是不是调用__index时第一个参数变成了右边代码中创建的new metatable

问题2：
现在还有社群可以交流吗

**Comment by zjhongxian** [comment]
能提供下版本信息和对应测试代码么？

**Comment by Chydison** [comment]
Lua5.3
UE4.27
slua-master

**Comment by Chydison** [comment]
测试代码。任意UObject实例化后调用index都可以复现。

**Comment by zjhongxian** [comment]
是不是自己编译的lua库，尝试下用slua官方给的lua 库？
另QQ群：15647305

**Comment by Chydison** [comment]
QQ群提示满员进不了了，可以拉一下么503964115，谢谢。
是自己编译的Lua库，用External目录下的源码编译的，我再对比一下差异，和尝试使用slua的提供的lib。

**Comment by Chydison** [comment]
有关lua源码的改动可以开源吗，我们也有一些改动，不能直接使用slua提供的lib

**Comment by zjhongxian** [comment]
> 

我不是群管理员，拉不了，可能得siney大神才能拉

**Comment by Chydison** [comment]
合并lua源码改动之后测试可以了，感谢。
