### ISSUE TITLE
Debug Editor模式下编译错误

### ISSUE THREAD

**Issue by edianzyg** [Tencent/sluaunreal#530]
1.LuaDelegate.cpp中 WITH_EDITOR弘控制的位置，改为 UE_BUILD_DEVELOPMENT
2.
![image](https://github.com/Tencent/sluaunreal/assets/122305054/2ae56f91-c55a-4226-a5f7-233eac40baea)
3.
![image](https://github.com/Tencent/sluaunreal/assets/122305054/f58d934b-b2f9-4455-97f4-bfd9a1661155)

**Comment by zjhongxian** [comment]
感谢指正，在我的分支已经提交修复，稍后合入主干
