### ISSUE TITLE
'Guid': is not a member of 'FRepSerializedPropertyInfo'

### ISSUE THREAD

**Issue by scriptkitz** [Tencent/sluaunreal#537]
Version: 2.1.0
UE 5.3

slua_unreal\Private\LuaNetSerialization.cpp(790): error C2039: 'Guid': is not a member of 'FRepSerializedPropertyInfo'

UE5.3里，FRepSerializedPropertyInfo已经没有Guid属性了。

**Comment by zjhongxian** [comment]
5.3还没release，等它出来打算把这个类抽出来自己实现一下，就不需要每次去兼容它了。现在暂时可能需要自己先去把它抠出来。

**Comment by zjhongxian** [comment]
最新代码已修复支持
