### ISSUE TITLE
Lua_gc crash 不能稳定重现

### ISSUE THREAD

**Issue by JacobZHK** [Tencent/sluaunreal#539]
UE：4.26.2版本
SLua： 2020年6月12日版本

![image](https://github.com/Tencent/sluaunreal/assets/54653451/7cf8b84a-0da8-4593-bdcb-7f24a8f3d2c7)

bug描述：
发行版本刚运行就gc崩溃，不能稳定重现。请问一下有什么线索么

**Comment by zjhongxian** [comment]
版本太老了。。可以考虑更新一下？
