### ISSUE TITLE
不能调用蓝图创建的蓝图函数库的函数

### ISSUE THREAD

**Issue by ozbao** [Tencent/sluaunreal#546]
**Describe the bug**
我新建了个蓝图函数库BFL_Common，lua不能调用蓝图函数库的函数，C++的蓝图函数库却能在lua调用
local BFL_Common = import("BFL_Common")
print(BFL_Common.GetUIManager())

报错
Slua: Error: ...Project/Main/RunbaPet/Content/Lua/RunbaMainCharacter.lua:10: Can't find class named BFL_Common
    ...Project/Main/RunbaPet/Content/Lua/RunbaMainCharacter.lua:10: in main chunk
Slua: Error: (null)
Slua: Error: LuaOverrider::BindOverrideFuncs Object[BP_RunbaMainCharacter_C_1]'s luaSelfTable[RunbaMainCharacter] not a lua table!

**Comment by zjhongxian** [comment]
要填蓝图的路径，且加 “_C” 后缀

**Comment by zjhongxian** [comment]
请问这样解决了么？

> 要填蓝图的路径，且加 “_C” 后缀

**Comment by ozbao** [comment]
> 请问这样解决了么？
> 
> > 要填蓝图的路径，且加 “_C” 后缀

可以用了
