### ISSUE TITLE
AllowWindowsPlatformTypes的类的位置不对导致编译不通过

### ISSUE THREAD

**Issue by ozbao** [Tencent/sluaunreal#550]
**Describe the bug**

**Version**
UE5.2，slua

**To Reproduce**
![image](https://github.com/Tencent/sluaunreal/assets/40519179/4aa8f493-353a-4239-a4ff-492241cdf584)
![image](https://github.com/Tencent/sluaunreal/assets/40519179/fd6820df-a162-4664-8987-4369b22a5039)

我这里要改着这样才能编译通过，Windows/AllowWindowsPlatformTypes.h
查了下everything，这些头文件都在../windows这个文件夹里面
![image](https://github.com/Tencent/sluaunreal/assets/40519179/e6a69b2e-f94b-4f8f-8a39-db3adeb10319)

**Additional context**

**Comment by zjhongxian** [comment]
应该是加个Window在前面更规范。比较奇怪的是我本地可以编译通过，我这就改
