### ISSUE TITLE
自定的枚举怎么导出呢？

### ISSUE THREAD

**Issue by jack0596cn** [Tencent/sluaunreal#56]
如题

**Comment by pangweiwei** [comment]
已经增加支持，参考这里 https://github.com/Tencent/sluaunreal/wiki/CppBinding-%E7%AE%80%E5%8D%95%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E#%E5%AF%BC%E5%87%BAenum%E5%92%8Cenum-class

**Comment by jack0596cn** [comment]
感谢，什么时候出1.0的release版本呢
