### ISSUE TITLE
请问如何实现全局（跨场景）的LuaState？

### ISSUE THREAD

**Issue by GotGimhong** [Tencent/sluaunreal#57]
slua的开发团队你们好，在我学习过部分源码以及示例代码后，发现无论是之前依赖一个USceneComponent还是现在基于一个Actor的版本，LuaState都会绑定到场景中的某个UObject上，如此一来，LuaState的生命周期就会与这个UObject的生命周期相同，LuaState似乎就不具备全局（跨场景）的能力了，因为切换场景后，在当前场景的LuaState就会执行析构，然后新场景的LuaState就会开始它的生命周期。

我尝试过把LuaState放到一个全局的对象中进行管理，例如UGameplayStatics或者UGameInstance，但是退出游戏时会在 `LuaState::removeRef` 处出现异常，原因是切换场景时引擎会回收一部分UObject对象，而LuaState仍然持有这些对象的引用。

由于在项目开发中，Lua层不可避免地需要缓存一些全局的数据，所以想请教一下全局（跨场景）LuaState的实现方法，谢谢。

**Comment by pangweiwei** [comment]
直接构建LuaState，luastate不依赖任何USceneComponent或者Actor，他的生命周期本来就是全局的，除非你自己绑定到了USceneComponent或者actor上。

**Comment by pangweiwei** [comment]
目前附带的demo

**Comment by pangweiwei** [comment]
对于某些lua引用的绑定到了uworld的对象，在切换场景的时候被回收了, 你需要考虑在一个合适的时机从lua里移除引用，比如切换场景的时候，另外你可以尝试：

修改一下
void removeRef(UObject* obj) {
	if (!obj->IsValidLowLevelFast()) return;
        ...

这样会跳过已经被free的对象，如果你测试ok请告知我，我也可以加入codebase。

**Comment by pangweiwei** [comment]
我fix了，不知道是不是你的异常，你可以pull一下最新代码测试一下，现在会在engine end play的时候自动调用luastate的close，回收掉所有lua引用的对象，避免最后的错误检查发生崩溃。

**Comment by GotGimhong** [comment]
收到。经过测试目前发现两个问题：

1. 除了属于游戏逻辑添加的引用外，LuaState似乎还会额外持有一些引用。即使是切换到空场景，而且不执行任何Lua代码，LuaState也会自动持有一个 `AGameModeBase` 和一个 `APlayerController` 类型的引用。

1. 尝试在 `LuaState::removeRef` 中添加您建议的代码，但是只能跳过部分被释放的对象，还有一部分能够通过 `IsValidLowLevelFast` 的检测，却在 `classInstanceNums` 没有引用记录的对象仍然会导致异常的出现。目前还不清楚原因是这部分对象没有添加引用记录还是野指针。

**Comment by pangweiwei** [comment]
1. 除了属于游戏逻辑添加的引用外，LuaState似乎还会额外持有一些引用。即使是切换到空场景，而且不执行任何Lua代码，LuaState也会自动持有一个 `AGameModeBase` 和一个 `APlayerController` 类型的引用。

luastate不会持有 `AGameModeBase` 和  `APlayerController`

2. 你pull最新代码试试；

**Comment by GotGimhong** [comment]
不好意思，更新了slua之后，我这边编译会花比较长时间，上一条回复还是在用您fix前的代码进行测试。我先pull一下您更新后的代码进行测试，如果还有问题明天再给您回复。

**Comment by pangweiwei** [comment]
新版也应该修改编译会花很多时间的问题，绕过了一个vs 2017的bug。

**Comment by GotGimhong** [comment]
早上好，重新pull过代码进行测试后，仍然有可能会在 `LuaState::removeRef` 处触发异常，但重现的概率比较低，目前也在尝试必现的方法。

以下是其中一次重现的错误信息记录，其中 `obj` 名为 "K2Node_VariableGet"，并且存在对应的 `UClass` 。
![obj](https://user-images.githubusercontent.com/16437644/52681477-e3712400-2f76-11e9-91e3-2c5309ccaebf.png)
![class](https://user-images.githubusercontent.com/16437644/52681488-e9ff9b80-2f76-11e9-86c9-5c3a2142b5eb.png)

调用栈信息如下图：
![stack](https://user-images.githubusercontent.com/16437644/52681492-ee2bb900-2f76-11e9-9005-9979357c28cf.png)

**Comment by zjhongxian** [comment]
@GotGimhong 请问下你是怎么重现的？我这边的工程编辑器上没有重现过，只有手机低概率重现

**Comment by inarutom2014** [comment]
> 你可以尝试：
> 
> 修改一下
> void removeRef(UObject* obj) {
> if (!obj->IsValidLowLevelFast()) return;
> ...
> 
> 这样会跳过已经被free的对象。
> 
> 但理论上UE4不应该回收被引用的对象，方便贴一下你的错误调用栈吗？

U类中的Actor比较特殊，经常有destroy一个Actor的需求，lua端的的actor主动调用K2_DestroyActor，然后再置成nil，等到lua端gc的时候，就会因为该U类已经被回收导致问题，如果加lowlevel的判断直接返回，ULuaObject里的Cache是否还残留着该指针呢？感觉应该提供一个专门用于销毁Actor的方法

**Comment by GotGimhong** [comment]
> @GotGimhong 请问下你是怎么重现的？我这边的工程编辑器上没有重现过，只有手机低概率重现

我这边重现的概率也比较低，只要进入游戏，切换过两次次场景就会有一定概率重现。具体是每进入一个新场景 `AGameModeBase` 和 `APlayerController` 会添加一次引用，再切换时上一个场景的引用对象貌似会被回收，导致引用失效了。引用失效可能会使得指针指向空内存，这个在2.12的更新中加了处理，会被 `IsValidLowLevelFast` 检测出来；也可能会指向其他的内存（或者是内存空间重新分配给其他对象了），这种情况 `IsValidLowLevelFast` 是检测不出来的，就会触发异常。
后来检查过引用了 `AGameModeBase` 和 `APlayerController` 应该是自己代码的问题，对于这些自己添加的，有可能会在 `LuaState::close` 之前被回收引用对象的引用，作者上面也提到需要自己考虑在一个合适的时机将引用移除掉，正常情况下应该是不会触发异常的。

**Comment by pangweiwei** [comment]
fix

**Comment by pangweiwei** [comment]
see this post https://github.com/Tencent/sluaunreal/commit/cd828df44b3244956020ebfd15b76b680452a5f5
