### ISSUE TITLE
当在同一进程开启多个游戏时（即设置Number of Player >=2），为什么lua代码只执行一次？

### ISSUE THREAD

**Issue by yfcyt** [Tencent/sluaunreal#586]
情景：
多人联网游戏，在开发过程中，需要在同一进程中开启多ViewPort来调试，即设置Num of Players >= 2
![aaaa](https://github.com/Tencent/sluaunreal/assets/7273396/d3681cef-08cc-4ef2-a677-fa0b8b958fef)

但是发现UI上（用的ULuaUserwidget）挂的lua脚本只会执行一次

如何让lua执行在每个ViewPort都执行？

**Comment by zjhongxian** [comment]
具体是什么版本？有具体的代码和运行log么？

**Comment by yfcyt** [comment]
> 具体是什么版本？有具体的代码和运行log么？

sluaunreal-2.1.2

具体的代码已经删了，现在通过开启多个进程来测试了
