### ISSUE TITLE
LuaArray中inner变量被销毁后，AddReferencedObjects访问inner野指针崩溃的问题

### ISSUE THREAD

**Issue by yish0000** [Tencent/sluaunreal#587]
**Describe the bug**
![image](https://github.com/Tencent/sluaunreal/assets/3023727/e162544d-876f-4584-a78c-a83fa43e32f7)
![image](https://github.com/Tencent/sluaunreal/assets/3023727/a2c0e175-137a-42a4-a614-6d76bf7efcfc)
上述native类派生的蓝图类实例化后，发生上述函数的调用时，产生的LuaArray构造时传入的FProperty是UFunction（OnEnterView）下所属的一个FProperty
假如发生GC的时候，蓝图类被GC，UFunction及其所属FProperty被销毁，此时LuaArray内的inner有可能变为野指针

**Version**
2.1.3

崩溃堆栈
![image](https://github.com/Tencent/sluaunreal/assets/3023727/4b08dbc6-76d0-4c90-b03e-22f3ac642634)
![image](https://github.com/Tencent/sluaunreal/assets/3023727/af2d13de-db7c-4b0c-a326-5205d2c02201)

**Comment by zjhongxian** [comment]
它对应的类按道理应该是会被引用住的。请问下你们是否有强制GC了对应的UClass？

**Comment by zjhongxian** [comment]
> 它对应的类按道理应该是会被引用住的。请问下你们是否有强制GC了对应的UClass？

![image](https://github.com/Tencent/sluaunreal/assets/5793922/d8883fd0-9de5-4572-ad61-c100a918decd)

它所对应的类，正常使用下，不应该是被销毁了

**Comment by yish0000** [comment]
我们没有强制GC对应的UClass
我看是蓝图类对应的UClass以及其所属的UPackage都被销毁了，这种情况下UClass是怎么被引用的呢

**Comment by yish0000** [comment]
![image](https://github.com/Tencent/sluaunreal/assets/3023727/4a54dfa6-d3b6-4963-8a82-9fbd804bffde)
![image](https://github.com/Tencent/sluaunreal/assets/3023727/a327c0d0-a840-4043-be37-eb7ec993ebee)
我通过这种修改，暂时不崩溃了

**Comment by yish0000** [comment]
![image](https://github.com/Tencent/sluaunreal/assets/3023727/7032d048-1c22-441a-b9bc-3e219fcd39bf)
有没有可能这里面Owner有可能不是UObject，可能Owner的Owner才是UObject

**Comment by zjhongxian** [comment]
> ![image](https://private-user-images.githubusercontent.com/3023727/317146670-7032d048-1c22-441a-b9bc-3e219fcd39bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MTkzMzksIm5iZiI6MTcxMTUxOTAzOSwicGF0aCI6Ii8zMDIzNzI3LzMxNzE0NjY3MC03MDMyZDA0OC0xYzIyLTQ0MWEtYjliYy0zZTIxOWZjZDM5YmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjdUMDU1NzE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTJhNjJmYjg4MTgwZmFiNmI0ZGYxMDlhMmZlNzVjZTg1MTJkYTFmZmMxNTZkN2M4OWM0Y2UwYWIzMmI2YmY0NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.I9KQxW1TACDW0cAb9xdhYRVkB8yeaK3aWqtS80QnIuk) 有没有可能这里面Owner有可能不是UObject，可能Owner的Owner才是UObject

大概率是这个原因了，感谢反馈！我明天抽空修复下

**Comment by yfcyt** [comment]
> **Describe the bug** ![image](https://private-user-images.githubusercontent.com/3023727/316233922-e162544d-876f-4584-a78c-a83fa43e32f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1OTE5NTQsIm5iZiI6MTcxMTU5MTY1NCwicGF0aCI6Ii8zMDIzNzI3LzMxNjIzMzkyMi1lMTYyNTQ0ZC04NzZmLTQ1ODQtYTc4Yy1hODNmYTQzZTMyZjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjhUMDIwNzM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzA2NmFkZGNjZDZlMTIxMzBhZGE3ZjZjOTlhMDEyYjlmY2ZiOWM4NjdhNzNjZTJlNGFlNWQzYTZlODNjM2E4ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.GY8EdSsw19bdcQxCc1HqgU06xtod8QwMd5cT5aqpOtI) ![image](https://private-user-images.githubusercontent.com/3023727/316233842-a2c0e175-137a-42a4-a614-6d76bf7efcfc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1OTE5NTQsIm5iZiI6MTcxMTU5MTY1NCwicGF0aCI6Ii8zMDIzNzI3LzMxNjIzMzg0Mi1hMmMwZTE3NS0xMzdhLTQyYTQtYTYxNC02ZDc2YmY3ZWZjZmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjhUMDIwNzM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjkxOGNkNTgxNjllNjQzMzk1ODQ2MDVkNDEzYTVhMDQ4NDZmYmM1N2U4NDBjNTQzMGE5ZWQyMzhhMDk4NGEwNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.RlDRgz6kbzYicrZAiR1iaETnfVfpHnYq5Bm7iAag24c) 上述native类派生的蓝图类实例化后，发生上述函数的调用时，产生的LuaArray构造时传入的FProperty是UFunction（OnEnterView）下所属的一个FProperty 假如发生GC的时候，蓝图类被GC，UFunction及其所属FProperty被销毁，此时LuaArray内的inner有可能变为野指针
> 
> **Version** 2.1.3
> 
> 崩溃堆栈 ![image](https://private-user-images.githubusercontent.com/3023727/316233662-4b08dbc6-76d0-4c90-b03e-22f3ac642634.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1OTE5NTQsIm5iZiI6MTcxMTU5MTY1NCwicGF0aCI6Ii8zMDIzNzI3LzMxNjIzMzY2Mi00YjA4ZGJjNi03NmQwLTRjOTAtYjAzZS0yMmYzYWM2NDI2MzQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjhUMDIwNzM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWQyNTA1YmFiNGJjNmUwNjBiZWM4Y2VlMmY3NDU2ZWI4MGM5MWU1MGI2YTA3NDIzYjM1OGUwNGY4ODAyNjI2NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.oJWj0fbVDe-Ija89RUCsLaYpicI-cAON0Xfu9USzAhE) ![image](https://private-user-images.githubusercontent.com/3023727/316233696-af2d13de-db7c-4b0c-a326-5205d2c02201.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1OTE5NTQsIm5iZiI6MTcxMTU5MTY1NCwicGF0aCI6Ii8zMDIzNzI3LzMxNjIzMzY5Ni1hZjJkMTNkZS1kYjdjLTRiMGMtYTMyNi01MjA1ZDJjMDIyMDEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjhUMDIwNzM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTdiZjZmZDNhZGE4Y2MzY2Y2MDQ5NzQwZmZjODA1ZTIwN2M2MzdlMmE5MThhZjBlMjJhNDk5NmE0NjM1MDFhMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.SfDQfe6kQsmZHsLHb1Xb8EbLR9Gqr0bzgsKK5GvMmEo)

哈喽，想请教一下，你的那个FSmartVisionInfo是怎么定义的？如何才传到Lua中的？我有同样的一个需求，发现无法通过const TArray<xxxx>& 传递到lua层中

**Comment by yish0000** [comment]
就是定义的USTRUCT，没什么特别的

**Comment by yfcyt** [comment]
> 就是定义的USTRUCT，没什么特别的

大佬有空帮我看看下面的问题吗？
#589
