### ISSUE TITLE
c++定义USTRUCT给lua使用，在C++中通过RPC调用lua代码时报错

### ISSUE THREAD

**Issue by yfcyt** [Tencent/sluaunreal#589]
报错日志：
LogProperty: Error: Struct type unknown for property 'StructProperty /Engine/Transient.Struct_0:TransientLuaProperty'; perhaps the USTRUCT() was renamed or deleted?

我写的代码：
![image](https://github.com/Tencent/sluaunreal/assets/7273396/d2b118fb-6c76-42b5-812c-0719eaf5dd56)

![image](https://github.com/Tencent/sluaunreal/assets/7273396/dc794a73-8bca-4899-aecc-8cfa6df726ee)

![image](https://github.com/Tencent/sluaunreal/assets/7273396/a522b7a2-f6b2-4d1c-8130-ba236f27007e)

![image](https://github.com/Tencent/sluaunreal/assets/7273396/9ef9592d-8cae-4223-9140-e54f2fbe03fd)

这里通过const TArray<FPlayerData>& 传递PlayerDatas到lua，会提示上面的报错

请问下，这个正确的用法是怎么样的？

**Comment by zjhongxian** [comment]
![image](https://github.com/Tencent/sluaunreal/assets/5793922/0067d478-1ce2-4554-aaa3-4e7e1c711be5)
是这里报错的？可有堆栈和相关变量信息？

**Comment by yfcyt** [comment]
> ![image](https://private-user-images.githubusercontent.com/5793922/317098548-0067d478-1ce2-4554-aaa3-4e7e1c711be5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MDc5ODgsIm5iZiI6MTcxMTUwNzY4OCwicGF0aCI6Ii81NzkzOTIyLzMxNzA5ODU0OC0wMDY3ZDQ3OC0xY2UyLTQ1NTQtYWFhMy00ZTdlMWM3MTFiZTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjdUMDI0ODA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODk4MDg2ZWU2N2FmNWY4YjAzNDljY2U0NzM2NDAxYjQxMjllNzI0MjkzYjI2NGQ1NTEwMjUxYjRiMTgzY2M3MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.PNF9XmT-jP63yQq-Iex0HY5JoVMGWhRThnheyRGGn3U) 是这里报错的？可有堆栈和相关变量信息？

谢谢大佬的回复！
是大佬截图的地方报的错，堆栈信息涉及一些商业隐私，不太方便截上来，我完整的描述一下我的情景：

我想要定义一个UStruct结构体FPlayerData，从C++传递(const TArray<FPlayerData>&)到Lua中，想在lua中访问从C++传递过来的FPlayerData数组

1.定义FPlayerData
USTRUCT(BlueprintType)
struct FPlayerData
{
	GENERATED_BODY()
public:
	/**
	 * @brief 玩家名字
	 */
	UPROPERTY()
	FString PlayerName;
	/**
	 * @brief 玩家Id
	 */
	UPROPERTY()
	FString PlayerId;
};

/**
* @brief 定义该类型可以被lua访问
*/
namespace NS_SLUA
{
	DefTypeName(FPlayerData);
	DefDeduceType(FPlayerData, Struct);
}

2.定义一个PlayerController，提供一个服务端调用客户端执行的RPC函数
UCLASS()
class UNREALPROJ_API AXXXPlayerController : public APlayerController
{
        //调用Lua代码
        template<class ...ARGS>
        void CallLuaFunc(const char* FuncName, ARGS&& ...args);

        /**
         * @brief 将信息同步到客户端 Run On Client
         */
        UFUNCTION(Client, Reliable, Category = "XXXX")
        void ClientUpdatePlayer(const TArray<FPlayerData>& PlayerDatas);
}

void AXXXPlayerController::ClientUpdatePlayer_Implementation(const TArray<FPlayerData>& PlayerDatas)
{
	CallLuaFunc("UpdatePlayer", PlayerDatas);
}

template<class ...ARGS>
void AXXXPlayerController::CallLuaFunc(const char* FuncName, ARGS && ...args)
{
	auto LuaWidget = Cast<ULuaUserWidget>(HUDWidget);
	if (LuaWidget)
	{
		auto Self = LuaWidget->GetSelfTable();
		if (Self.isValid()) Self.callField(FuncName, Self, std::forward<ARGS>(args)...);
	}
}

代码调用过程：

在Server端通过ClientUpdatePlayer将const TArray<FPlayerData>& PlayerDatas传递到ClientClientUpdatePlayer_Implementation

最终将PlayerDatas通过callField方法传递到了Lua的UpdatePlayer方法中

然后出现了上面的报错

**Comment by zjhongxian** [comment]
OK，我明天抽空构造一下现场看看

**Comment by yfcyt** [comment]
> OK，我明天抽空构造一下现场看看

好的，谢谢大佬
