### ISSUE TITLE
打包slua,老报SafeDelete错误

### ISSUE THREAD

**Issue by modest008** [Tencent/sluaunreal#590]
UE版本是5.2.1
windows使用visual studio 2022
打包时，经常报SafeDelete错误，找不到报错的位置
我使用mac打包了一下，也报错，并且显示出报错位置：
NiagaraShared.h(302,48): Error  : expected unqualified-id
        ~FNiagaraDataInterfaceParamRef() { Parameters.SafeDelete(); }
                                                      ^
SluaUtil.h(27,25): Reference  : expanded from macro 'SafeDelete'
#define SafeDelete(ptr) { if(ptr) { delete ptr;ptr=nullptr; } }
                        ^
1 error generated.

**Comment by zjhongxian** [comment]
应该是宏导致的，可以考虑把它去掉，slua代码里面的都手动改下

**Comment by modest008** [comment]
好的，谢谢，可以了
