### ISSUE TITLE
slua插件对mod加载以及Gamefeature的支持

### ISSUE THREAD

**Issue by JimSuo** [Tencent/sluaunreal#597]
请问slua插件现在是否支持Gamefeature功能呢？

**Comment by zjhongxian** [comment]
并没有对它做专门的开发，但我的理解它们两是不同维度的。slua按道理也支持GameFeature里面类、函数等的访问调用

**Comment by JimSuo** [comment]
感谢回复，您说的完全正确。我在继续研究了插件的源码之后发现只需要将插件对应的路径添加正确后，在设置loadFileDelegate的监听函数内再做一一下对应fn的处理就可以在使用Gamefeature的情况下正常使用了。这是我的实现，您看这么实现是否合理？
![1717393512827](https://github.com/Tencent/sluaunreal/assets/68036321/f62b0c3b-eb63-46d2-92af-14ae7d3f51da)

**Comment by zjhongxian** [comment]
思路是正确的，赞！

**Comment by JimSuo** [comment]
另外，我想加入群但是群已经满了，还有额外的群可以进入吗，我们公司正好在使用slua开发游戏业务。谢谢

**Comment by zjhongxian** [comment]
> 另外，我想加入群但是群已经满了，还有额外的群可以进入吗，我们公司正好在使用slua开发游戏业务。谢谢

QQ群是siney哥在管，我没权限。。只能先在github上交流先了

**Comment by JimSuo** [comment]
好的，有问题的话我会再次提交issue的
