### ISSUE TITLE
请教几个使用上的问题

### ISSUE THREAD

**Issue by kevinofsias** [Tencent/sluaunreal#6]
开发组你好，请教几个问题，该插件是基于USluaComponent生成LuaState，如果用于整个游戏的界面系统，应该是多个USluaComponent还是一个USluaComponent？
1.如果是1个USluaComponent维护所有界面，每个界面用一个脚本去控制，还需要一些共有数据脚本去存储数据，比如策划表，也有可能数据脚本保存一些共有变量，但是创建出来的新界面脚本需要如何去调用自己的init或tick函数，还有如何销毁某个界面。
2.如果是多个USluaComponent去分别创建自己LuaState，每个LuaState控制一个界面相关逻辑，那数据脚本可以相互访问吗，全局变量如何做到修改完，其他LuaState也被修改？
3.Lua中有一个lua_newthread的作用可以共用主线程LuaState数据，但是不知道怎么改，望开发组考虑一下数据共享问题。
望开发组解惑一下，非常感谢。

**Comment by kevinofsias** [comment]
这篇博客的评论中有人这样说过。https://blog.codingnow.com/2012/04/lua_multi_states_database.html

“大侠，看了以后我有个疑惑，求解惑。既然要多个lua_State共享一份数据，为什么不把这些静态数据像加载到一个lua_State* L中，以后创建的lua_State都以L子线程的发生创建，这样不就可以读共享数据了吗？
L1 = lua_newthread(L)我在Lua程序设计那本书上看到的，也写过小例子测试过，不知道这样会不会有什么缺点，望大侠不吝赐教”

**Comment by pangweiwei** [comment]
> 1.如果是1个USluaComponent维护所有界面，每个界面用一个脚本去控制，还需要一些共有数据脚本去存储数据，比如策划表，也有可能数据脚本保存一些共有变量，但是创建出来的新界面脚本需要如何去调用自己的init或tick函数，还有如何销毁某个界面。

USluaComponent的唯一作用是拿到uworld指针和tick，除此之外没有任何其他作用，uworld指针也仅仅用于load widget ui（这部分代码一般都需要根据项目重写，所以很可能实际代码中不需要USluaComponent，仅需要luastate），这样的情况下，slua目前的设计是一个luastate加载所有界面，每个界面对应一个lua文件。

同时目前slua的设计，支持多state，但确实尚未考虑数据共享问题，未来会考虑添加。

**Comment by ZuoEr** [comment]
初步使用看下来用单个state没什么问题，数据也很方便。
