### ISSUE TITLE
请问lua中如何创建C++对应的TArray<TSubclassOf<XXX>>的类型数组？

### ISSUE THREAD

**Issue by nozomanai** [Tencent/sluaunreal#611]
使用Class类型直接空指针
```lua
local SlotItemClassArray = slua.Array(EPropertyClass.Class,import("WeaponBase"))
```

![image](https://github.com/user-attachments/assets/64a7579b-5a8f-45ef-befa-e578050e6ddd)

不支持这种操作方式吗？

**Comment by zjhongxian** [comment]
local SlotItemClassArray = slua.Array(EPropertyClass.Object,import("WeaponBase"))
你试试这样行不行

**Comment by nozomanai** [comment]
> local SlotItemClassArray = slua.Array(EPropertyClass.Object,import("WeaponBase")) 你试试这样行不行

这样也不行，目前没发现好的方案，得麻烦点手动包装一层结构体

**Comment by zjhongxian** [comment]
你先封装一个API，返回这个类型看看。比如：
UFUNCTION()
TArray<TSubclassOf<XXX>> GenerateArrayOfXXX();

暂时我还没时间精力给你支持到位。
