### ISSUE TITLE
协程函数不输出异常日志到控制台

### ISSUE THREAD

**Issue by nozomanai** [Tencent/sluaunreal#612]
**Describe the bug**
在协程函数如果出现了异常，ue控制台不会有任何输出，如果程序没异常，使用print是可以看到输出。

**Version**
2.1.4 Release ，unreal5.4.3

```lua
function DefPlayer:ReceiveBeginPlay()
    print("开始游戏")

    local co = coroutine.create(function()
        local a = nil
        a:xda()
        print('测试输出')
    end)
    coroutine.resume(co)
end

```
![image](https://github.com/user-attachments/assets/53dcec3d-1b49-4238-bb46-aabf93666d25)
发现是没有输出异常的，并且测试输出这句话打印也没打印到。
如果协程函数没异常，可以看到打印：
```lua
function DefPlayer:ReceiveBeginPlay()
    print("开始游戏")

    local co = coroutine.create(function()
        -- local a = nil
        -- a:xda()
        print('测试输出')
    end)
    coroutine.resume(co)
end
```
![image](https://github.com/user-attachments/assets/e16a4181-3208-4e8f-a3fa-79b25dfe355b)
```lua
function DefPlayer:ReceiveBeginPlay()
    print("开始游戏")
    local a = nil
    a:xda()
    print("测试输出")
end
```
当然，不使用协程，异常是可以正常输出到控制台的
![image](https://github.com/user-attachments/assets/9a4aef36-5885-4acc-a193-78e6edb6d3a5)

**Comment by zjhongxian** [comment]
协程的异常需要自己处理，这个lua设计本如此

**Comment by nozomanai** [comment]
> 协程的异常需要自己处理，这个lua设计本如此

自己处理是没毛病，但是出异常控制台不输出，协程函数内的异常不会输出。
后面我发现wrap创建的协程，异常有可以输出，coroutine.create创建的协程不会输出异常日志

**Comment by zjhongxian** [comment]
你要这么写：
function DefPlayer:ReceiveBeginPlay()
    print("开始游戏")

    local co = coroutine.create(function()
        local a = nil
        a:xda()
        print('测试输出')
    end)
    local res, msg = coroutine.resume(co)
    if not res then
        print(debug.tracekback(co, msg)
    end
end
