### ISSUE TITLE
关于TMap和TArray的bug和支持

### ISSUE THREAD

**Issue by OneBigShrimp** [Tencent/sluaunreal#63]
1.TMap和TArray中有UObject类型时,作为方法的返回值或者作为对象字段,传给lua, 在GC调用AddReferencedObjects时会闪退,因为LuaReference的addRefByProperty方法中的ContainerPtrToValuePtr对于此种情况是多余的,因为此时传过来的base本身就是正确的地址,不需要偏移,我们这边增加了一个参数用来表示是否需要调用ContainerPtrToValuePtr对base进行偏移. 

2.lua端创建TArray或者TMap时, 没有对BaseStruct(FVector之类的)或者UStruct做支持,你们是否有做支持的打算?这边我们把createProperty方法最后一个参数换成了UObject*类型,可以传UClass*或者UScriptStruct*,方法内部增加了EPropertyClass::Struct分支处理做了支持

3.C++端调用lua方法时,参数不支持TArray和TMap,这个你们是否有做支持的打算?这边我们改动的多了一点,加了2个push的模板函数匹配TArray和TMap,加了一个类用来根据T来创建UProperty

我不太会用git,如果你们没有打算加上面的东西,我可以在这边测试基本没啥问题之后,尝试着提交一个pull request

**Comment by pangweiwei** [comment]
欢迎提交pr

**Comment by OneBigShrimp** [comment]
我们刚把你们这套东西接到项目里,然后刚刚改完,测试几天改的没啥问题就提交pr

**Comment by pangweiwei** [comment]
你们测试完了吗？如果测试完了，能不能提交一下pr ：）

**Comment by pangweiwei** [comment]
你提交的第一个问题，我测试并没有发现，
ContainerPtrToValuePtr 第二个参数在那种情况下为0，offset也为0，不会导致计算错误。
