### ISSUE TITLE
蓝图对象传到Lua后的GC问题

### ISSUE THREAD

**Issue by ShuraLiu** [Tencent/sluaunreal#64]
Level上的Actor传到Lua中做逻辑，Level被移除后Actor触发UE4的GC早于Lua的GC，导致ULuaObject的Remove方法在Actor被GC时还未调用。

**Comment by pangweiwei** [comment]
你什么版本？最新版本应该解决了这个问题，最新版本已经没有 ULuaObject

**Comment by ShuraLiu** [comment]
感谢回复，我们用的是一个比较老的版本，一会我们尝试下更新到新版本看看
