### ISSUE TITLE
导出Http模块的问题

### ISSUE THREAD

**Issue by zengdelang** [Tencent/sluaunreal#71]
使用下面的宏导出http模块的接口，GetAllHeaders, GetContent两个函数导出无法编译通过，提示24个重载中没有一个可以转换所有参数类型，有什么办法能够导出UE的http到lua中使用吗？
DefLuaClass(IHttpBase)
	DefLuaMethod(GetURL, &IHttpBase::GetURL)
	DefLuaMethod(GetURLParameter, &IHttpBase::GetURLParameter)
	DefLuaMethod(GetHeader, &IHttpBase::GetHeader)
	//DefLuaMethod(GetAllHeaders, &IHttpBase::GetAllHeaders)
	DefLuaMethod(GetContentType, &IHttpBase::GetContentType)
	DefLuaMethod(GetContentLength, &IHttpBase::GetContentLength)
	//DefLuaMethod(GetContent, &IHttpBase::GetContent)
EndDef(IHttpBase, &NoConstructor)

**Comment by pangweiwei** [comment]
https://github.com/Tencent/sluaunreal/wiki/CppBinding-%E7%AE%80%E5%8D%95%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E

请使用支持重载的宏

**Comment by zengdelang** [comment]
不是重载的问题，而是函数的返回值是TArray<uint8>, TArray<FString>导致无法push，在Base中添加下面方法并导出也无法编译通过

**Comment by zengdelang** [comment]
class Base {
        LuaClassBody()
    public:
        virtual ~Base() {
            Log::Log("Base object %p had been freed",this);
        }

        void baseFunc1() {
            Log::Log("baseFunc1 call");
        }

		TArray<uint8> GetContent()
        {
	        
        }

		TArray<FString> GetAllHeaders()
        {
	        
        }
    };

    DefLuaClass(Base)
        DefLuaMethod(baseFunc1,&Base::baseFunc1)
		DefLuaMethod(GetContent, &Base::GetContent)
		DefLuaMethod(GetAllHeaders, &Base::GetAllHeaders)
    EndDef(Base,&NoConstructor)
