### ISSUE TITLE
CppBinding的问题，无法绑定返回值是TArray的函数

### ISSUE THREAD

**Issue by zengdelang** [Tencent/sluaunreal#72]
和Http模块导出相同的问题，在Base类中，添加四个函数，testFunc1, testFunc2, testFunc3, testFunc4,由于testFunc1,testFunc2的返回值是TArray<uint8>,TArray<FString>导致无法导出，无法编译通过
 
测试代码：
 class Base {
        LuaClassBody()
    public:
        virtual ~Base() {
            Log::Log("Base object %p had been freed",this);
        }

        void baseFunc1() {
            Log::Log("baseFunc1 call");
        }

		TArray<uint8> testFunc1()
        {
	        
        }

		TArray<FString> testFunc2()
        {
	        
        }

		void testFunc3(TArray<uint8> arr)
        {
	        
        }

		void testFunc4(TArray<FString> arr)
		{

		}
    };

    DefLuaClass(Base)
        DefLuaMethod(baseFunc1,&Base::baseFunc1)
		//DefLuaMethod(testFunc1, &Base::testFunc1)
		//DefLuaMethod(testFunc2, &Base::testFunc2)
		DefLuaMethod(testFunc3, &Base::testFunc3)
		DefLuaMethod(testFunc4, &Base::testFunc4)
    EndDef(Base,&NoConstructor)

**Comment by pangweiwei** [comment]
嗯，这个问题在之前的这个 issue 也提了，https://github.com/Tencent/sluaunreal/issues/63

我再等他们pr，当然自己添加也不麻烦。

**Comment by pangweiwei** [comment]
fix
