### ISSUE TITLE
CppBinding问题，delegate的导入导出问题

### ISSUE THREAD

**Issue by zengdelang** [Tencent/sluaunreal#74]
定义两个代理
DECLARE_DYNAMIC_DELEGATE_OneParam(FOnTestDynamicDelegate, int, P);
DECLARE_DELEGATE_TwoParams(FOnTestDelegate, int32, bool);

class FooChild : public Foo 
{
		void testFunc1(FOnTestDynamicDelegate d) {
			d.ExecuteIfBound(1111);
		}

		void testFunc2(FOnTestDelegate d) {
			d.ExecuteIfBound(2222, TEXT("=============="));
		}

		FOnTestDynamicDelegate testFunc3() {
		}

		FOnTestDelegate testFunc4() {
		}
    };

    DefLuaClass(FooChild,Foo)
		DefLuaMethod(testFunc1, &FooChild::testFunc1)
		DefLuaMethod(testFunc2, &FooChild::testFunc2)
		//DefLuaMethod(testFunc1, &FooChild::testFunc3)
		//DefLuaMethod(testFunc2, &FooChild::testFunc4)
    EndDef(FooChild,&FooChild::create)

问题1： 如果使用代理作为返回值，导出无法编译通过
问题2：
由于testFunc1,testFunc2不是由UFUNCTION，UPROPERTY等宏修饰的，导致在lua中绑定无法回调
t:testFunc1(slua.createDelegate(function(p, p1)
    print("==================", p, p1) 
end))

由于上面的问题，引擎内置不使用UObject的部分代码以及部分自定义代码使用上面的方式无法导出或者导出不生效，目前发现下面的项目中
https://github.com/asqbtcupid/unreal.lua.git
提供了一个宏，用来导出代理
LUA_GLUE_DELEGATE
请问目前如何在slua中解决这个问题？

**Comment by pangweiwei** [comment]
直接使用tfunction

**Comment by pangweiwei** [comment]
参考 https://github.com/Tencent/sluaunreal/blob/d7078bff9dd22a18f2e22bb9b5cf1b0665939abb/Source/democpp/SluaTestCase.cpp#L100
