### ISSUE TITLE
请问unreal slua 怎么接 protobuf3.6.1?

### ISSUE THREAD

**Issue by kongbu0621** [Tencent/sluaunreal#76]
请问unreal lua 怎么接 protobuf3.6.1?   急~

**Comment by pangweiwei** [comment]
自己添加protobuf的代码进入cmake 文件，仿照luasocket，然后在对应平台上编译出lua库。

**Comment by kongbu0621** [comment]
> 自己添加protobuf的代码进入cmake 文件，仿照luasocket，然后在对应平台上编译出lua库。

好，我試試

**Comment by hanchen1234599** [comment]
怎么样你弄得。 我这边也遇到这个问题。 slua-unreal-pb接入4.25报错编译不过去
