### ISSUE TITLE
请问UE4 C++ Actor里定义的UPROPERTY(Replicated)int32 NetPawnUniqueIdx 如何在LuaActor里定义？

### ISSUE THREAD

**Issue by kongbu0621** [Tencent/sluaunreal#77]
UPROPERTY(VisibleAnywhere, BlueprintReadWrite, Replicated)
TArray<FCWPawnInstructs> ArrayInstructs;     //FCWPawnInstructs是一個Struct

UPROPERTY(Replicated)
TArray<FCWBattlePropertyAffectorData> ArrayPropertyAffectorData;  //FCWBattlePropertyAffectorData是一個Struct

UPROPERTY(EditAnywhere, BlueprintReadWrite, Replicated)
int32 NetPawnUniqueIdx;

请问C++里Actor里如上三个定义？ 如何在LuaActor里定义？

**Comment by pangweiwei** [comment]
这种网络同步的属性，你需要继承自LuaActor，然后添加你的属性申明

**Comment by kongbu0621** [comment]
在lua里怎么添加相应的属性申明？  语法是怎样的？  wiki里没提到， 我不会写

**Comment by pangweiwei** [comment]
不是，是从c++继承ALuaActor，然后吧你上面的写上去

**Comment by kongbu0621** [comment]
我需要在lua里写所有逻辑， 不能写在C++里

**Comment by pangweiwei** [comment]
目前你定义rpc的数据需要在c++里，定义完了之后可以用lua写代码。

**Comment by kongbu0621** [comment]
策划需求改变，我必须在lua里做处理。如此只需要更新lua代码即可。    如果在C++里定义新的rpc数据， 还是需要重新打包，然后整包更新，没有意义

**Comment by pangweiwei** [comment]
我思考一下如何在lua里增加支持

**Comment by zengdelang** [comment]
Lua配合蓝图可以实现，在蓝图里面声明对应的同步变量，RPC函数以及OnRep_XXX等函数，通过LuaActor的luaImplemented可以拦截对蓝图的反射调用，转到lua中调用即可对应同名函数即可
