### ISSUE TITLE
请问UE4 C++ Actor里UFUNCTION(NetMulticast, Reliable)，UFUNCTION(Server, Reliable, WithValidation)， UFUNCTION(Client, Reliable), 在LuaActor里如何实现？

### ISSUE THREAD

**Issue by kongbu0621** [Tencent/sluaunreal#78]
UFUNCTION(NetMulticast, Reliable)
void NetMulticastRPCAddBuff(int32 ParamBuffUniqueId, int32 ParamBuffId);

UFUNCTION(Client, Reliable)
void ClientRPCStartAction();

UFUNCTION(Server, Reliable, WithValidation)
void ServerRPCActionEnd();

请问UE4 C++ Actor里UFUNCTION(NetMulticast, Reliable)，UFUNCTION(Server, Reliable, WithValidation)， UFUNCTION(Client, Reliable), 在LuaActor里如何实现？

**Comment by pangweiwei** [comment]
我没有测试过这种情况，但感觉上你可以修改：
	bool LuaBase::luaImplemented(UFunction * func, void * params)
	{
		if (!func->HasAnyFunctionFlags(EFunctionFlags::FUNC_BlueprintEvent))
			return false;

这里添加 支持 FUNC_NetReliable 标记，他也可以发到脚本里调用对用lua函数

**Comment by kongbu0621** [comment]
不会写，大侠，能否在wiki里说明？

**Comment by pangweiwei** [comment]
我添加这个支持吧

**Comment by kongbu0621** [comment]
多谢大侠！

**Comment by dsz0** [comment]
另外，现在ue4的安卓打包已经要求NDK版本使用r14b,
但slua还是建议r13么？？
