### ISSUE TITLE
救命：unreal-slua 添加pb, local pb = require("pb") , 出现如下错误

### ISSUE THREAD

**Issue by kongbu0621** [Tencent/sluaunreal#79]
Slua:     hello luasocket
Slua:     LuaSocket 3.0-rc1
Slua: Error: Can't load file pb
Slua: Error: multiple Lua VMs detected
stack traceback:
    [C]: in ?
    [C]: in function 'require'
    ...../dst/git/ChessClient/Content//LuaClient/mainClient.lua:38: in field 'Init'
    ...../dst/git/ChessClient/Content//LuaClient/mainClient.lua:10: in function <...../dst/git/ChessClient/Content//LuaClient/mainClient.lua:9>

**Comment by zengdelang** [comment]
这是我集成的lua-protobuf,可以试下
https://github.com/zengdelang/slua-unreal-pb

**Comment by pangweiwei** [comment]
你是不是链接了2个不同的lua库，这样就会报告 multiple Lua VMs detected

**Comment by kongbu0621** [comment]
我试试，2楼 zengdelang兄弟的 slua-unreal-pb

**Comment by kongbu0621** [comment]
谢谢2楼 zengdelang兄弟提供的 https://github.com/zengdelang/slua-unreal-pb， 搞定了
