### ISSUE TITLE
Demo中 TArray 添加 actor的时候 crash

### ISSUE THREAD

**Issue by km-jiaxiu** [Tencent/sluaunreal#81]
demo 中 Map2Actor.lua  21行  self.ballarr:Add(actor) 
做checkUProperty<UObjectProperty> 会引发p->PropertyClass 空指针异常

**Comment by pangweiwei** [comment]
master版本已经修复了，你现在的是1.0版吧？

**Comment by pangweiwei** [comment]
fixed
