### ISSUE TITLE
请问我怎么判断哪些UE4的C++类，lua里能直接用？ 比如FPaths::ProjectContentDir()这样的类和函数，lua里可以用吗？

### ISSUE THREAD

**Issue by kongbu0621** [Tencent/sluaunreal#82]
请问我怎么判断哪些UE4的C++类，已经导出给lua, 在lua里能直接用？ 比如FPaths::ProjectContentDir()这样的类和函数，lua里可以用吗？ 怎么判断？

**Comment by pangweiwei** [comment]
你可以使用cppbinding手动导出，参考https://github.com/Tencent/sluaunreal/wiki/CppBinding-%E7%AE%80%E5%8D%95%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E
