### ISSUE TITLE
当classConstruct传入参数为lua table时候, lua的栈的参数个数会出现错误.

### ISSUE THREAD

**Issue by fdcumt** [Tencent/sluaunreal#87]
调用方式:
![image](https://user-images.githubusercontent.com/10294860/54899172-ef52ed00-4f09-11e9-82ae-57d4f3ae1534.png)

报错内容: 

调用堆栈:
![image](https://user-images.githubusercontent.com/10294860/54899214-114c6f80-4f0a-11e9-835e-23a4c645d631.png)

猜测代码错误的地方:
在这里面, 调用了函数lua_getfield, 参数栈size增加1,  而checkUD 里面testudata成功之后直接返回了,并没有把新压进去的参数pop出去.
![image](https://user-images.githubusercontent.com/10294860/54899285-3b059680-4f0a-11e9-8383-0f6178d92bbf.png)
![image](https://user-images.githubusercontent.com/10294860/54899493-f0d0e500-4f0a-11e9-8f53-74812fc383b3.png)

我目前解决方法(保证maybeAnUDTable函数执行完毕后, lua栈的大小不变):
![image](https://user-images.githubusercontent.com/10294860/54899869-43f76780-4f0c-11e9-90bb-e02159c5f0ac.png)

**Comment by fdcumt** [comment]
![image](https://user-images.githubusercontent.com/10294860/54900250-7c4b7580-4f0d-11e9-8c3c-fc887dfe312b.png)
当调用第一个checkValueOpt之后,lua参数栈大小会加1,如果就传入一个参数, 当执行第二个checkValueOpt时候, 就会报错.

**Comment by pangweiwei** [comment]
ok, got it
