### ISSUE TITLE
luawrapper 问题

### ISSUE THREAD

**Issue by xinbay** [Tencent/sluaunreal#89]
直接从git上下载的项目，luawrapper无法使用，修改了 solution_dir和ue4_dir
是否还要修改，include_path 
不添加自定义类，也无法导出。4.18和4.21版本都试过。
solution_dir": "E:/UEWorkspaces/UEClient.git",
        "ue4_dir": "d:/Program Files/Epic Games/UE_4.21",

**Comment by xinbay** [comment]
或者lua-wrapper.exe是否有log 输出可以查看哪里配置错误了

**Comment by easily** [comment]
@xinbay 
你的 solution_dir 配置错了，需要配置文件夹路径，而不是 git 路径
我测试了一下，如果 solution_dir 配置错误，正常应该会打印： “Cannot find the path of slua-unreal, please check the "config.json" file.”

**Comment by xinbay** [comment]
> @xinbay
> 你的 solution_dir 配置错了，需要配置文件夹路径，而不是 git 路径
> 我测试了一下，如果 solution_dir 配置错误，正常应该会打印： “Cannot find the path of slua-unreal, please check the "config.json" file.”

![image](https://user-images.githubusercontent.com/8396263/54977963-d4e84480-4fd9-11e9-8b9d-66af449c12d9.png)
你好，路径配置是正确的，.git是文件夹的名字，改了下， 还是没有任何效果，有一个命令行窗口一闪而过， 并且Output.Log窗口没有任何Log输出。

**Comment by xinbay** [comment]
@easily 
你好， 配置是正确的 ，还是没有效果。
"solution_dir": "E:/Workspace/sluaunreal",
"ue4_dir": "d:/Program Files/Epic Games/UE_4.18",

执行luaWrapper的时候，有个命令行窗口一闪而过， 并且在output.log窗口没有任何log输出。

**Comment by easily** [comment]
@xinbay 
用命令行窗口下面执行，不要直接双击
直接双击如果运行有异常会直接退出

**Comment by xinbay** [comment]
@easily 感谢帮助 问题解决了
