### ISSUE TITLE
config.json里，添加了几行，但是生成的LuaWrapper.cpp没有把相关struct导出？

### ISSUE THREAD

**Issue by kongbu0621** [Tencent/sluaunreal#90]
"export_files": {
        "TBaseStructure": "{ue4_dir}/Engine/Source/Runtime/CoreUObject/Public/UObject/Class.h",
        "Customs": {
            "FSlateFontInfo": "{ue4_dir}/Engine/Source/Runtime/SlateCore/Public/Fonts/SlateFontInfo.h",
            "FSlateBrush": "{ue4_dir}/Engine/Source/Runtime/SlateCore/Public/Styling/SlateBrush.h",
            "FMargin": "{ue4_dir}/Engine/Source/Runtime/SlateCore/Public/Layout/Margin.h",
            "FGeometry": "{ue4_dir}/Engine/Source/Runtime/SlateCore/Public/Layout/Geometry.h",
            "FSlateColor": "{ue4_dir}/Engine/Source/Runtime/SlateCore/Public/Styling/SlateColor.h",
			"FCWNetHead": "{output_dir}/Source/ChessWar/Public/Network/CWThread.h",
			"FCWNetRoute": "{output_dir}/Source/ChessWar/Public/Network/CWNetRoute.h",
			"FCWClientNetHead": "{output_dir}/Source/ChessWar/Public/Network/CWClientNetHead.h",
			"FCWServerNetHead": "{output_dir}/Source/ChessWar/Public/Network/CWServerNetHead.h",
        }
    },

**Comment by kongbu0621** [comment]
USTRUCT()
struct FCWNetHead
{
public:
	GENERATED_USTRUCT_BODY()
public:

	/**< 消息数据长度 */
	uint32 DataLength;

	/**< 消息类型 */
	uint16 MsgId;

	/**< 子消息个数(包括自己) */
	uint16 Child;
};

**Comment by kongbu0621** [comment]
USTRUCT()
struct FCWClientNetHead : public FCWNetHead
{
public:
	GENERATED_USTRUCT_BODY()
public:

};

**Comment by kongbu0621** [comment]
USTRUCT()
struct FCWNetRoute
{
public:
	GENERATED_USTRUCT_BODY()
public:

	FCWNetRoute();
	FCWNetRoute(uint64 ParamServerId, uint64 ParamSendId, uint64 ParamRecvId);

public:

	/**< 发送服务器Id */
	uint64 ServerId;

	/**< 发送者Id */
	uint64 SendId;

	/**< 接受者Id */
	uint64 RecvId;
};

**Comment by kongbu0621** [comment]
USTRUCT()
struct FCWServerNetHead : public FCWNetHead
{
public:
	GENERATED_USTRUCT_BODY()
public:

	/**< 路由信息 */
	UPROPERTY(Transient)
	FCWNetRoute Route;
};

**Comment by pangweiwei** [comment]
具有ustruct标签的，可以直接import使用

**Comment by kongbu0621** [comment]
好，了解了
