### ISSUE TITLE
android 打包加载文件失败

### ISSUE THREAD

**Issue by llyao** [Tencent/sluaunreal#91]
用demo打出来的包里面没有Lua,导致加载lua失败

**Comment by pangweiwei** [comment]
自带的例子，就是直接从磁盘读取文件，android打包后，你需要自己考虑包的读取，每个游戏都自己的打包方法；

修改 state 的load delegate
具体参考 MyGameInstance.cpp的 setLoadFileDelegate 的实例

作为简单测试，你可以把lua文件夹放入content打包中，放入non-asset package。
