### ISSUE TITLE
lua-wrapper.exe运行错误

### ISSUE THREAD

**Issue by huiger8723** [Tencent/sluaunreal#92]
![11](https://user-images.githubusercontent.com/35018842/55220593-93a69d80-5242-11e9-9cd5-5f877fe5939a.png)

**Comment by huiger8723** [comment]
依赖里面需要的是Newtonsoft.Json 11.0.02，并没看到这个版本号，只找到了11.0.0，是这个版本的库不行吗

**Comment by easily** [comment]
@huiger8723 
https://www.nuget.org/packages/newtonsoft.json/11.0.2
