### ISSUE TITLE
请问slua中怎么使用结构体.

### ISSUE THREAD

**Issue by githubcomus** [Tencent/sluaunreal#96]
/** Performs a collision query under the mouse cursor, looking on a trace channel */
	UFUNCTION(BlueprintCallable, Category="Game|Player", meta=(bTraceComplex=true))
	bool GetHitResultUnderCursorByChannel(ETraceTypeQuery TraceChannel, bool bTraceComplex, FHitResult& HitResult) const;

请问这个函数的第三个参数再slua中应该怎么声明呢,可否给下使用范例.

**Comment by pangweiwei** [comment]
在测试代码里有，你可以看看Map2Actor.lua

**Comment by githubcomus** [comment]
看到了,之前阅读不仔细,感谢!
