### ISSUE TITLE
luawrapper 导出问题

### ISSUE THREAD

**Issue by xinbay** [Tencent/sluaunreal#98]
@pangweiwei 
你好， 用luawrapper发现自定义类无法导出，已经添加custom 和 inclue_path ，

导出引擎中的类之后，编译错误
例如 
"FStreamableManager": "{ue4_dir}/Engine/Source/Runtime/Engine/Classes/Engine/StreamableManager.h",

 error C2143: syntax error: missing ';' before '*'
 error C7525: inline variables require at least '/std:c++17'
 error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
 error C2059: syntax error: '{'
 error C2143: syntax error: missing ';' before '{'
error C2447: '{': missing function header (old-style formal list?)
error C2672: 'slua::LuaObject::push': no matching overloaded function found
 error C2974: 'slua::LuaObject::push': invalid template argument for 'K', type expected
2>  E:\UEWorkspaces\UEClient\Plugins\slua_unreal\Source\slua_unreal\Public\LuaObject.h(490): note: see declaration of 'slua::LuaObject::push'
 error C2974: 'slua::LuaObject::push': invalid template argument for 'T', type expected

luawrapper没有输出异常日志，
另外在 Issues50 中发现有人问自定义类无法导出的问题，回复已经修复，我用的luawrapper是从Tencent/sluaunreal tool中最新的。

**Comment by xinbay** [comment]
导出自定义类 原因找到 定义类的时候，不能加dll导出宏
FStreamableManager导出手动添加头文件引用，
'FStreamableManager::FStreamableManager(const FStreamableManager &)': attempting to reference a deleted function

看了下定义 发现有FStreamableManager& operator=(const FStreamableManager&) = delete;
构造函数被禁用了

**Comment by pangweiwei** [comment]
我们会修改代码，对于不支持的语法特性给出错误输出；
目前并不是所有的语法特性都支持。

**Comment by xinbay** [comment]
感谢帮助
